### PR TITLE
LibWeb: Copy `m_resize_observers` before iterating

### LINKED ISSUE #2011: LibWeb: Crash on pixiv.net
Crash happens consistently when loading [https://www.pixiv.net/en/artworks/95834820](https://www.pixiv.net/en/artworks/95834820)

gdb backtrace:

```sh
Thread 1 "WebContent" received signal SIGSEGV, Segmentation fault.
Web::DOM::Document::broadcast_active_resize_observations ()
    at /home/aplefull/Repos/ladybird/Userland/Libraries/LibWeb/DOM/Document.cpp:5163
5163	        observer->active_targets().clear();
(gdb) bt
#0  Web::DOM::Document::broadcast_active_resize_observations () at /home/aplefull/Repos/ladybird/Userland/Libraries/LibWeb/DOM/Document.cpp:5163
#1  0x00007a5926f4fc16 in Web::HTML::EventLoop::update_the_rendering () at /home/aplefull/Repos/ladybird/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:349
#2  0x00007a5926f51269 in AK::Function<void ()>::operator()() const () at /home/aplefull/Repos/ladybird/AK/Function.h:120
#3  Web::HTML::Task::execute () at /home/aplefull/Repos/ladybird/Userland/Libraries/LibWeb/HTML/EventLoop/Task.cpp:47
#4  0x00007a5926f5029d in Web::HTML::EventLoop::process () at /home/aplefull/Repos/ladybird/Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:176
#5  0x00007a592720dc59 in JS::SafeFunction<void ()>::operator()() const () at /home/aplefull/Repos/ladybird/Userland/Libraries/LibJS/SafeFunction.h:85
#6  operator() () at /home/aplefull/Repos/ladybird/Userland/Libraries/LibWeb/Platform/TimerSerenity.cpp:23
#7  call () at /home/aplefull/Repos/ladybird/AK/Function.h:187
#8  0x00007a59293a6522 in AK::Function<void ()>::operator()() const () at /home/aplefull/Repos/ladybird/AK/Function.h:120
#9  Core::Timer::timer_event () at /home/aplefull/Repos/ladybird/Userland/Libraries/LibCore/Timer.cpp:97
#10 0x00007a59293951bd in Core::EventReceiver::dispatch_event () at /home/aplefull/Repos/ladybird/Userland/Libraries/LibCore/EventReceiver.cpp:162
#11 0x00005c74c5cb8b9d in qt_timer_fired () at /home/aplefull/Repos/ladybird/Ladybird/Qt/EventLoopImplementationQt.cpp:227
#12 operator() () at /home/aplefull/Repos/ladybird/Ladybird/Qt/EventLoopImplementationQt.cpp:241
#13 call () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:127
#14 call<QtPrivate::List<>, void> () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:241
#15 impl () at /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs_impl.h:408
#16 0x00007a5928f83d9b in ??? () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#17 0x00007a5928f8ed6d in QTimer::timeout(QTimer::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#18 0x00007a5928f76576 in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#19 0x00007a5928f38416 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#20 0x00007a592907b7ab in QTimerInfoList::activateTimers() () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#21 0x00007a5929133a29 in ??? () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#22 0x00007a59289145b5 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007a5928973717 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007a5928913a53 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007a59291315ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()

```

### PR DESCRIPTION
**Pull request by yyny**
An inopportune garbage collection may cause collected `ResizeObserver`s to unregister themselves from `m_resize_observers` while we are iterating over it, resulting in a use-after-free.

Copy the vector to avoid this scenario.

Fixes #2011.

A better solution might be to queue `ResizeObserver` de-registrations, or to `swap_remove` unregistered `ResizeObserver`s in such a way that indexed iteration remains well-defined (assuming the order of `ResizeObserver` in `m_resize_observers` is irrelevant).

> **EDIT**: The order of resize observers _is_ relevant. It is possible to still keep well-defined indexed iteration _without_ `swap_remove` or memory allocations, though, with:
> ```c++
> GC::Ptr<ResizeObserver> observer;
> for (size_t i=0; i < m_resize_observers.size(); i += size_t(observer.ptr() == m_resize_observers[i].ptr()) {
>     observer = m_resize_observers[i];
>     // ...
> }
> ```
> but perhaps that is just a _bit_ too fragile.

### CODE REVIEW

File: Libraries/LibWeb/DOM/Document.cpp [hunk 1]
```diff
@@ -5160,7 +5160,7 @@ size_t Document::broadcast_active_resize_observations()
     auto shallowest_target_depth = NumericLimits<size_t>::max();
 
     // 2. For each observer in document.[[resizeObservers]] run these steps:
-    for (auto const& observer : m_resize_observers) {
+    for (auto resize_observers = m_resize_observers; auto const& observer : resize_observers) {
```
Comment (awesomekling) [inline Libraries/LibWeb/DOM/Document.cpp:5163]: This is not enough; the copy here will be a `Vector<GC::Ref<ResizeObserver>>` but nothing visits those.
We need to use either `Vector<GC::Root<ResizeObserver>>` or `MarkedVector<GC::Ref<ResizeObserver>>`

**Comment by rmg-x** [comment]
This will supersede PR #2449 and also fix issue #2475 too :)

**Comment by yyny** [comment]
Could this also be considered a bug in the spec? I found this step, which also seems to exists solely to provide stable iteration.

> Let notifySet be a clone of the surrounding agent’s mutation observers.

**Comment by yyny** [comment]
I'm a bit surprised that `ResizeObserver`s can be collected in the first place when they should still be reachable in `document.[[resizeObservers]]`. The only place where `ResizeObserver`s are ever unregistered is in `ResizeObserver::finalize`.

Might be the same issue as https://github.com/w3c/csswg-drafts/issues/3703, i.e. a `ResizeObserver` on another `Document`.

Also, https://github.com/w3c/csswg-drafts/issues/4518 suggests an explicit copy step of the list to guarantee well-defined iteration, so I guess this issue is already known.

And finally there is https://bugzilla.mozilla.org/show_bug.cgi?id=1596992#c10, which we might also want to do to avoid an ever growing `document.[[resizeObservers]]`.
