### PR TITLE
WebContent+headless-browser: Implement mismatch conditions for ref tests

### LINKED ISSUE #2712: ./Meta/WPT.sh import fails to categorise mismatch tests
### Summary

The test importer is categorising WPT tests with only a mismatch link as a text test NOT a ref test.

### Operating system

macOS

### Steps to reproduce

1. Run ./Meta/WPT.sh import css/css-pseudo/file-selector-button-001.html
2. See that the test is shown as being of type Text not Ref
3.

### Expected behavior

The importer needs to look for links with rel mismatch aswell as links with rel match.

### Actual behavior

It only looks for links with rel match.

### URL for a reduced test case

https://example.com

### HTML/SVG/etc. source for a reduced test case

```html
https://example.com
```

### Log output and (if possible) backtrace

```shell
Importing test from css/css-pseudo/file-selector-button-001.html
Identified https://wpt.live/css/css-pseudo/file-selector-button-001.html as type TestType.REF, ref file-selector-button-001-notref.html
Downloading https://wpt.live/css/css-pseudo/file-selector-button-001.html to /Users/luke/Development/BrowserEngines/ladybird/Tests/LibWeb/Ref/input/wpt-import/css/css-pseudo/file-selector-button-001.html
Downloading https://wpt.live/css/css-pseudo/file-selector-button-001-notref.html to /Users/luke/Development/BrowserEngines/ladybird/Tests/LibWeb/Ref/expected/wpt-import/css/css-pseudo/file-selector-button-001-notref.html
Fontconfig error: Cannot load default config file: No such file: (null)
Running 1 tests...
Done!
==========================================================
Pass: 0, Fail: 1, Skipped: 0, Timeout: 0, Crashed: 0
==========================================================
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by tcl3**
Ref tests can now have a `<link rel="mismatch">` condition. The test will pass if the expectation page doesn't match the test page.

The WPT test importer has also been modified to allow importing WPT reftests with mismatch conditions. Note that we currently don't support multiple conditions, the first condition found will be the only one that's checked.

NOTE: This change won't be able to detect certain types of issues that we may have with WPT reftests, since the mechanism the WPT test runner uses to compare reftests is significantly different to ours.

Fixes #2712

### CODE REVIEW

File: Services/WebContent/ConnectionFromClient.cpp [hunk 1]
```diff
@@ -411,13 +411,31 @@ void ConnectionFromClient::debug_request(u64 page_id, ByteString const& request,
...
+            }();
+
             if (maybe_link.is_error() || !maybe_link.value()) {
                 // To make sure that we fail the ref-test if the link is missing, load the error page->
                 load_html(page_id, "<h1>Failed to find &lt;link rel=&quot;match&quot; /&gt; in ref test page!</h1> Make sure you added it.");
             } else {
                 auto link = maybe_link.release_value();
                 auto url = document->parse_url(link->get_attribute_value(Web::HTML::AttributeNames::href));
+                if (has_mismatch_selector)
+                    url.set_query("mismatch"_string);
```
Comment (AtkinsSJ) [inline Services/WebContent/ConnectionFromClient.cpp:437]: I think it's very unlikely that any test would set its own query string on its match url, but just in case, can we add an error message somewhere?

File: Services/WebContent/ConnectionFromClient.cpp [hunk 2]
```diff
@@ -411,13 +411,31 @@ void ConnectionFromClient::debug_request(u64 page_id, ByteString const& request,
...
+                    has_mismatch_selector = maybe_mismatch_link.value();
+                    return maybe_mismatch_link;
+                }
+
+                return nullptr;
+            }();
+
             if (maybe_link.is_error() || !maybe_link.value()) {
                 // To make sure that we fail the ref-test if the link is missing, load the error page->
                 load_html(page_id, "<h1>Failed to find &lt;link rel=&quot;match&quot; /&gt; in ref test page!</h1> Make sure you added it.");
```
Comment (AtkinsSJ) [inline Services/WebContent/ConnectionFromClient.cpp:432]: Maybe mention `rel="mismatch"` here too.

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]

**Comment by tcl3** [comment]
My latest push adds a small change to the importer to explicitly disallow importing tests with multiple match/mismatch links. Our local test runner doesn't support this, so explicitly disallowing it in the importer avoids potential confusion.

**Review by AtkinsSJ — APPROVED** [review]
