### PR TITLE
LibWeb/HTML: Fix some bugs related to commands

### LINKED ISSUE #8585: Commands are sent, even when the button or target are not attached
### Summary

When a button or the command target is not part of the document tree in ladybird, the command is still sent and processed. Other browsers do not send commands when either button or target is not attached.

### Operating system

Linux

### Steps to reproduce

1. Open the reduced test case

### Expected behavior

Only the command from "button" to "target" is sent.

### Actual behavior

The command is sent every time.

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
<!doctype html>
<button id="button"></button>
<div id="target"></div>
<script>
    const logEvent = e => console.log(`${e.command}: ${e.source.id} -> ${e.target.id}`);

    target.addEventListener("command", logEvent);
    const detachedTarget = document.createElement("div");
    detachedTarget.id = "detachedTarget";
    detachedTarget.addEventListener("command", logEvent);

    const detachedButton = document.createElement("button");
    detachedTarget.id = "detachedButton";

    function testEvent(button, target) {
        button.command = "--test";
        button.commandForElement = target;
        button.click();
    }

    testEvent(button, target);
    testEvent(button, detachedTarget);
    testEvent(detachedButton, target);
    testEvent(detachedButton, detachedTarget);
</script>

```

### Log output and (if possible) backtrace

```shell
2023.684 WebContent(26438): (js log) "--test: button -> target"
2023.684 WebContent(26438): (js log) "--test: button -> detachedTarget"
2023.684 WebContent(26438): (js log) "--test: detachedButton -> target"
2023.684 WebContent(26438): (js log) "--test: detachedButton -> detachedTarget"
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [x] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by skyz1**
This PR fixes #8585 and updates the button activation behaviour steps in order to comply with spec changes.

### CODE REVIEW

File: Libraries/LibWeb/HTML/HTMLButtonElement.cpp [hunk 1]
```diff
@@ -154,6 +154,33 @@ bool HTMLButtonElement::has_activation_behavior() const
     return true;
 }
 
+static bool determine_if_a_command_is_valid_for_a_target(String command, GC::Ptr<Web::DOM::Element> target)
```
Comment (gmta) [inline Libraries/LibWeb/HTML/HTMLButtonElement.cpp:158]: Please add a spec link here

File: Libraries/LibWeb/HTML/HTMLButtonElement.cpp [hunk 2]
```diff
@@ -154,6 +154,33 @@ bool HTMLButtonElement::has_activation_behavior() const
...
+    //    - Toggle Popover
+    //    - Show Popover
+    //    - Hide Popover
+    //    then return true.
+    if (command == "toggle-popover"sv || command == "show-popover"sv || command == "hide-popover"sv)
+        return true;
+
+    // 5. If this standard does not define is valid command steps for target's local name, then return false.
+    // 6. Otherwise, return the result of running target's corresponding is valid command steps given command.
+    return as<HTMLElement>(target.ptr())->is_valid_command(command);
```
Comment (gmta) [inline Libraries/LibWeb/HTML/HTMLButtonElement.cpp]: Step 3 establishes that `target` is not a nullptr, so you can do `as<HTMLElement>(*target)` here (or use `as_if<HTMLElement>` over at step 3).
