### PR TITLE
UI/Qt: Fix dragging tab pass the + button, closes #1124

### LINKED ISSUE #1124: Dragging a tab goes pass the `+` button
[Screencast from 08-19-2024 01:42:12 PM.webm](https://github.com/user-attachments/assets/7eb76530-eb38-483f-bb80-41113085f657)

Currently the tabs, when dragged, can go pass the `+` button but Firefox and Chrome do not allow this to happen

### PR DESCRIPTION
**Pull request by PiyushXCoder**
Before this change, if would a tab it will pass the add new tab button (+ button).

**Before:**

https://github.com/user-attachments/assets/d36f89ab-3673-4304-a11c-2e712cfbb73a

**After:**

https://github.com/user-attachments/assets/56c85cd9-30d6-410c-932f-3e27b696b7c2

### CODE REVIEW

**Review by tcl3 — COMMENTED** [review]
Welcome to the Ladybird project. Thanks for working on this!

One small thing I noticed is that ` m_boundary_limit_for_dragging_tab` isn't updated when a new tab is opened programmatically.  You can see the issue with the following script if a new tab is opened while an existing tab is being dragged:

```html
<!DOCTYPE html>
<script>
    setInterval(() => { window.open(); }, 3000);
</script>
```
NB: You'll need to run ladybird with `--allow-popups` for the above page to work correctly.

Rather than setting `m_boundary_limit_for_dragging_tab` when the mouse is clicked would it be possible to set it whenever a new tab is opened or closed?

**Comment by PiyushXCoder** [comment]
I have pushed the changes.
Previously the draggable boundary was calculated while drag would start. This used to prevent user move tab to very end where tab is added. 
Now, The draggable boundary is calculated everytime the mouse moves while dragging. And the position of mouse in selected tab is stored, which is beacause the draggable boundary depends on position of mouse in selected tab.

File: Ladybird/Qt/TabBar.cpp [hunk 1]
```diff
@@ -45,6 +45,39 @@ void TabBar::contextMenuEvent(QContextMenuEvent* event)
         tab->context_menu()->exec(event->globalPos());
 }
 
+void TabBar::mousePressEvent(QMouseEvent* event)
+{
+    event->ignore();
+
+    auto rect_of_current_tab = tabRect(tabAt(event->pos()));
+    m_position_in_selected_tab_while_dragging = QPoint(event->pos().x() - rect_of_current_tab.x(), event->pos().x() - rect_of_current_tab.x());
```
Comment (tcl3) [inline Ladybird/Qt/TabBar.cpp:53]: The x co-ordinate is being repeated here. Could you store just the X position since that's all we're interested in?

```c++
m_x_position_in_selected_tab_while_dragging = event->pos().x() - rect_of_current_tab.x();
```

**Review by tcl3 — COMMENTED** [review]
Looks good! Just a few small things from me.

Please squash the changes you've made after review into the relevant preceding commit instead of adding them as a separate commit.

There is a typo in your commit title: `pass -> past`. Generally it's better to avoid overly broad words like "fix" - the PR title should explain the change being made. Something like:

> UI/Qt: Don't allow tabs to be dragged past the new tab button

would be better in this case. The `closes #1124` part can be put into the PR description.

**Review by tcl3 — APPROVED** [review]
Thanks for this!
