### PR TITLE
LibGfx+LibWeb: Move Skia backend context to process level singleton

### LINKED ISSUE #8493: Crash when calling toBlob() on canvas in a detached document
### Summary

A SIGSEGV crash occurs in `Web::HTML::HTMLCanvasElement::get_bitmap_from_surface`.

### Operating system

macOS

### Steps to reproduce

1. Load the attached test case
2. Ladybird crashes

### Expected behavior

Should not crash (return a reasonable value or throw an appropriate exception)

### Actual behavior

Crashes

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
<!DOCTYPE html>
<body><script>
var doc = document.implementation.createHTMLDocument('');
var canvas = doc.createElement('canvas');
canvas.width = 100; canvas.height = 100;
doc.body.appendChild(canvas);
canvas.toBlob(function() {}, 'image/png');
</script></body>
```

### Log output and (if possible) backtrace

```shell
Fontconfig error: Cannot load default config file: No such file: (null)

CRASH: Received signal SIGSEGV (11)
Stack trace (most recent call first):
#0  0x00000001954b9763 in __sigtramp + 55 at /usr/lib/system/libsystem_platform.dylib
#1  0x0000000106f1646f in Web::HTML::HTMLCanvasElement::get_bitmap_from_surface() + 295 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#2  0x0000000106f1646f in Web::HTML::HTMLCanvasElement::get_bitmap_from_surface() + 295 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#3  0x0000000106f160c7 in Web::HTML::HTMLCanvasElement::to_blob(GC::Ref<Web::WebIDL::CallbackType>, AK::StringView, JS::Value) + 79 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#4  0x00000001078c41ff in Web::Bindings::HTMLCanvasElementPrototype::to_blob(JS::VM&) + 443 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#5  0x0000000103c19ea7 in JS::NativeFunction::call() + 131 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#6  0x0000000103c19ca7 in JS::NativeFunction::internal_call(JS::ExecutionContext&, JS::Value) + 231 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#7  0x0000000103ad8cb7 in JS::ThrowCompletionOr<void> JS::Bytecode::Op::execute_call<(JS::Bytecode::Op::CallType)0>(JS::Bytecode::Interpreter&, JS::Value, JS::Value, AK::Span<JS::Bytecode::Operand const>, JS::Bytecode::Operand, AK::Optional<JS::Bytecode::StringTableIndex>, JS::Strict) + 647 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#8  0x0000000103ace113 in JS::Bytecode::Op::Call::execute_impl(JS::Bytecode::Interpreter&) const + 79 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#9  0x0000000103a77fd7 in _asm_slow_path_call + 55 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#10 0x0000000103d361ef in .Lasm_Call.call_slow + 11 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#11 0x0000000103ad6bfb in JS::Bytecode::Interpreter::run_executable(JS::ExecutionContext&, JS::Bytecode::Executable&, AK::Optional<unsigned long>) + 159 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#12 0x0000000103acaeff in JS::Bytecode::Interpreter::run(JS::Script&, GC::Ptr<JS::Environment>) + 631 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#13 0x000000010701056f in Web::HTML::ClassicScript::run(Web::HTML::ClassicScript::RethrowErrors, GC::Ptr<JS::Environment>) + 147 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#14 0x0000000106f8ad83 in Web::HTML::HTMLScriptElement::execute_script() + 559 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#15 0x0000000106f8bf07 in Web::HTML::HTMLScriptElement::prepare_script() + 4151 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#16 0x0000000106feace7 in Web::HTML::HTMLParser::handle_text(Web::HTML::HTMLToken&) + 707 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#17 0x0000000106fe5093 in Web::HTML::HTMLParser::run(Web::HTML::HTMLTokenizer::StopAtInsertionPoint) + 703 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#18 0x0000000106fe6283 in Web::HTML::HTMLParser::run(URL::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) + 143 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#19 0x0000000106db7053 in AK::Function<void ()>::CallableWrapper<Web::load_html_document(Web::HTML::NavigationParams const&, AK::NonnullRefPtr<Core::Promise<AK::Empty, AK::Error>>)::$_0::operator()(AK::Detail::ByteBuffer<32ul>)::'lambda'()>::call() + 139 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#20 0x0000000107195223 in AK::Function<void ()>::CallableWrapper<Web::Platform::EventLoopPlugin::deferred_invoke(GC::Root<GC::Function<void ()>>)::$_0>::call() + 107 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#21 0x000000010323db03 in Core::ThreadEventQueue::process() + 419 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-core.0.0.0.dylib
#22 0x000000010323f4cb in Core::EventLoopImplementationUnix::exec() + 71 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-core.0.0.0.dylib
#23 0x000000010322e053 in Core::EventLoop::exec() + 67 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-core.0.0.0.dylib
#24 0x00000001026dcc6f in ladybird_main(Main::Arguments) + 3527 at /Users/johandahlin/dev/ladybird-2/Build/release/bin/Ladybird.app/Contents/MacOS/WebContent
#25 0x000000010278ba93 in _main at /Users/johandahlin/dev/ladybird-2/Build/release/bin/Ladybird.app/Contents/MacOS/WebContent
#26 0x00000001950e5d53 in start + 7183 at /usr/lib/dyld
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### LINKED ISSUE #8498: Crash when calling putImageData() on canvas in a detached document
### Summary

A SIGSEGV crash occurs in `Web::HTML::CanvasRenderingContext2D::allocate_painting_surface_if_needed`.

### Operating system

macOS

### Steps to reproduce

1. Load the attached test case
2. Ladybird crashes

### Expected behavior

Should not crash (return a reasonable value or throw an appropriate exception)

### Actual behavior

Crashes

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
<!DOCTYPE html>
<body><script>
var doc = document.implementation.createHTMLDocument('');
var canvas = doc.createElement('canvas');
canvas.width = 100; canvas.height = 100;
doc.body.appendChild(canvas);
var ctx = canvas.getContext('2d');
if (ctx) {
  var data = new ImageData(10, 10);
  ctx.putImageData(data, 0, 0);
}
</script></body>
```

### Log output and (if possible) backtrace

```shell
Fontconfig error: Cannot load default config file: No such file: (null)

CRASH: Received signal SIGSEGV (11)
Stack trace (most recent call first):
#0  0x00000001954b9763 in __sigtramp + 55 at /usr/lib/system/libsystem_platform.dylib
#1  0x000000010761094b in Web::HTML::CanvasRenderingContext2D::allocate_painting_surface_if_needed() + 151 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#2  0x000000010761094b in Web::HTML::CanvasRenderingContext2D::allocate_painting_surface_if_needed() + 151 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#3  0x000000010760f5df in Web::HTML::CanvasRenderingContext2D::painter() + 43 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#4  0x0000000107612547 in Web::HTML::CanvasRenderingContext2D::put_image_data(Web::HTML::ImageData&, float, float) + 71 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#5  0x0000000107f91853 in Web::Bindings::CanvasRenderingContext2DPrototype::put_image_data0(JS::VM&) + 315 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#6  0x0000000107f8bb2b in Web::Bindings::CanvasRenderingContext2DPrototype::put_image_data(JS::VM&) + 99 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#7  0x0000000104355ea7 in JS::NativeFunction::call() + 131 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#8  0x0000000104355ca7 in JS::NativeFunction::internal_call(JS::ExecutionContext&, JS::Value) + 231 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#9  0x0000000104214cb7 in JS::ThrowCompletionOr<void> JS::Bytecode::Op::execute_call<(JS::Bytecode::Op::CallType)0>(JS::Bytecode::Interpreter&, JS::Value, JS::Value, AK::Span<JS::Bytecode::Operand const>, JS::Bytecode::Operand, AK::Optional<JS::Bytecode::StringTableIndex>, JS::Strict) + 647 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#10 0x000000010420a113 in JS::Bytecode::Op::Call::execute_impl(JS::Bytecode::Interpreter&) const + 79 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#11 0x00000001041b3fd7 in _asm_slow_path_call + 55 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#12 0x00000001044721ef in .Lasm_Call.call_slow + 11 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#13 0x0000000104212bfb in JS::Bytecode::Interpreter::run_executable(JS::ExecutionContext&, JS::Bytecode::Executable&, AK::Optional<unsigned long>) + 159 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#14 0x0000000104206eff in JS::Bytecode::Interpreter::run(JS::Script&, GC::Ptr<JS::Environment>) + 631 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-js.0.0.0.dylib
#15 0x000000010774c56f in Web::HTML::ClassicScript::run(Web::HTML::ClassicScript::RethrowErrors, GC::Ptr<JS::Environment>) + 147 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#16 0x00000001076c6d83 in Web::HTML::HTMLScriptElement::execute_script() + 559 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#17 0x00000001076c7f07 in Web::HTML::HTMLScriptElement::prepare_script() + 4151 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#18 0x0000000107726ce7 in Web::HTML::HTMLParser::handle_text(Web::HTML::HTMLToken&) + 707 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#19 0x0000000107721093 in Web::HTML::HTMLParser::run(Web::HTML::HTMLTokenizer::StopAtInsertionPoint) + 703 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#20 0x0000000107722283 in Web::HTML::HTMLParser::run(URL::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) + 143 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#21 0x00000001074f3053 in AK::Function<void ()>::CallableWrapper<Web::load_html_document(Web::HTML::NavigationParams const&, AK::NonnullRefPtr<Core::Promise<AK::Empty, AK::Error>>)::$_0::operator()(AK::Detail::ByteBuffer<32ul>)::'lambda'()>::call() + 139 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#22 0x00000001078d1223 in AK::Function<void ()>::CallableWrapper<Web::Platform::EventLoopPlugin::deferred_invoke(GC::Root<GC::Function<void ()>>)::$_0>::call() + 107 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-web.0.0.0.dylib
#23 0x0000000103851b03 in Core::ThreadEventQueue::process() + 419 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-core.0.0.0.dylib
#24 0x00000001038534cb in Core::EventLoopImplementationUnix::exec() + 71 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-core.0.0.0.dylib
#25 0x0000000103842053 in Core::EventLoop::exec() + 67 at /Users/johandahlin/dev/ladybird-2/Build/release/lib/liblagom-core.0.0.0.dylib
#26 0x0000000102d08c6f in ladybird_main(Main::Arguments) + 3527 at /Users/johandahlin/dev/ladybird-2/Build/release/bin/Ladybird.app/Contents/MacOS/WebContent
#27 0x0000000102db7a93 in _main at /Users/johandahlin/dev/ladybird-2/Build/release/bin/Ladybird.app/Contents/MacOS/WebContent
#28 0x00000001950e5d53 in start + 7183 at /usr/lib/dyld
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by tcl3**
The skia backed context is stored on the traversable navigable, which is null for detached documents. We now fall back to CPU rendering when creating bitmaps for a canvas on a detached document, avoiding this crash.

Fixes #8493
Fixes #8498

### CODE REVIEW

File: Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
Comment (gmta) [inline Libraries/LibWeb/HTML/HTMLCanvasElement.cpp:1]: Commit message typo: "backed" -> "backend"

File: Libraries/LibWeb/HTML/HTMLCanvasElement.cpp [hunk 1]
```diff
@@ -307,13 +307,15 @@ Gfx::IntSize HTMLCanvasElement::bitmap_size_for_canvas(size_t minimum_width, siz
...
+    // It is possible the canvas doesn't have an associated bitmap so create one
     allocate_painting_surface_if_needed();
     auto surface = this->surface();
     auto size = bitmap_size_for_canvas();
     if (!surface && !size.is_empty()) {
         // If the context is not initialized yet, we need to allocate transparent surface for serialization
-        auto skia_backend_context = navigable()->traversable_navigable()->skia_backend_context();
+        RefPtr<Gfx::SkiaBackendContext> skia_backend_context;
+        if (auto navigable = this->navigable())
+            skia_backend_context = navigable->traversable_navigable()->skia_backend_context();
```
Comment (gmta) [inline Libraries/LibWeb/HTML/HTMLCanvasElement.cpp]: 🤔 maybe the context shouldn't live on a TraversableNavigable, but somewhere else entirely? Feels weird not to be able to make use of a perfectly good context that just happens to not be "reachable" from a document.

Comment (tcl3) [reply Libraries/LibWeb/HTML/HTMLCanvasElement.cpp]: I've moved the Skia backend context to a singleton accessed with `SkiaBackendContext::the()`, which allows allows it to be used here.

File: Services/WebContent/main.cpp [hunk 2]
```diff
@@ -198,6 +199,8 @@ ErrorOr<int> ladybird_main(Main::Arguments arguments)
     Web::set_browser_process_executable_path(executable_path);
 
     // Always use the CPU backend for tests, as the GPU backend is not deterministic
+    if (!force_cpu_painting)
+        Gfx::SkiaBackendContext::initialize_gpu_backend();
     WebContent::PageClient::set_use_skia_painter(force_cpu_painting ? WebContent::PageClient::UseSkiaPainter::CPUBackend : WebContent::PageClient::UseSkiaPainter::GPUBackendIfAvailable);
```
Comment (gmta) [inline Services/WebContent/main.cpp]: Maybe combine the `if (!force_cpu_painting)` and the ternary for readability?

```cpp
if (force_cpu_painting) {
    WebContent::PageClient::set_use_skia_painter(WebContent::PageClient::UseSkiaPainter::CPUBackend);
} else {
    Gfx::SkiaBackendContext::initialize_gpu_backend();
    WebContent::PageClient::set_use_skia_painter(WebContent::PageClient::UseSkiaPainter::GPUBackendIfAvailable);
}

**Comment by jdahlin** [comment]
@tcl3 tests from #8468 might be useful, they used to crash before this

**Comment by tcl3** [comment]
I've simplified some of the tests from #8468 and included them. AFAICT the `canvas-text-in-detached-doc.html` test would require the `CanvasTextDrawingStyles.cpp` change from #8473 to pass, so I haven't included it here.

File: Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp [hunk 3]
```diff
@@ -248,8 +248,7 @@ void CanvasRenderingContext2D::allocate_painting_surface_if_needed()
 
     auto color_type = m_context_attributes.alpha ? Gfx::BitmapFormat::BGRA8888 : Gfx::BitmapFormat::BGRx8888;
 
-    auto skia_backend_context = canvas_element().navigable()->traversable_navigable()->skia_backend_context();
-    m_surface = Gfx::PaintingSurface::create_with_size(skia_backend_context, canvas_element().bitmap_size_for_canvas(), color_type, Gfx::AlphaType::Premultiplied);
+    m_surface = Gfx::PaintingSurface::create_with_size(Gfx::SkiaBackendContext::the(), canvas_element().bitmap_size_for_canvas(), color_type, Gfx::AlphaType::Premultiplied);
```
Comment (gmta) [inline Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp]: Do we still have a reason to pass in the context to `::create_with_size()` as an argument every time? Seems like we can now just access `Gfx::SkiaBackendContext::the()` directly :)

Comment (tcl3) [reply Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp]: Of course! I found a few more places that could be simplified too.

File: Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp [hunk 4]
```diff
@@ -97,8 +93,8 @@ static SkM44 to_skia_matrix4x4(Gfx::FloatMatrix4x4 const& matrix)
 
 void DisplayListPlayerSkia::flush()
 {
-    if (m_context)
-        m_context->flush_and_submit(&surface().sk_surface());
+    if (Gfx::SkiaBackendContext::the())
+        Gfx::SkiaBackendContext::the()->flush_and_submit(&surface().sk_surface());
```
Comment (gmta) [inline Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp]: I'm wondering if this should have stayed `m_context` in order to make these hot paths as simple as possible - a `GC::Ref` dereference seems lighter than two calls.

Comment (tcl3) [reply Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp]: `m_context` no longer exists and `SkiaBackendContext::the()` is a static variable getter. I've changed this to an if-init statement for readability.
