### PR TITLE
LibWeb: Fix font-style to slope conversion

### LINKED ISSUE #4808: `@font-face` doesn't respect `font-style`
### Summary

When a website uses `@font-face` with two fonts, which are same `font-family` but differing `font-style`s, the first `@font-face`'s `url()` is used regardless of `font-style` in all places where the font is used.

### Operating system

Linux

### Steps to reproduce

1. Open the provided reduced test case with Ladybird
2. Observe the first line in comparison to the second line

### Expected behavior

1. The first line is `font-style: normal` so it should render normal (**not** *italic*).
2. The second line should also render as `font-style: normal`.

Image

### Actual behavior

1. The first line does **not** render with the normal font, and instead renders the *italic* variant
2. The second line looks correct.

Image

### URL for a reduced test case

https://jsfiddle.net/d8x1g2w5/

### HTML/SVG/etc. source for a reduced test case

```html
<style>
    .broken {
        font-family: Overpass;
        font-style: normal;
    }
    .not-broken {
        font-family: sans-serif;
        font-style: normal;
    }
    @font-face {
      font-family: 'Overpass';
      font-style: italic;
      /* this is the `italic` variant */
      src: url(https://fonts.gstatic.com/s/overpass/v16/qFdB35WCmI96Ajtm81GgY9nqxw.woff2) format('woff2');
    }
    @font-face {
      font-family: 'Overpass';
      font-style: normal;
      /* this is the `normal` variant */
      src: url(https://fonts.gstatic.com/s/overpass/v16/qFdH35WCmI96Ajtm81GlU9s.woff2) format('woff2');
    }
</style>
<p class="broken">This should be normal font-style</p>
<p class="not-broken">This is normal font-style, for reference</p>
```

### Log output and (if possible) backtrace

```shell
N/A
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [x] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by lionkor**
In a recent refactor of font styles (#4552), the new FontStyleStyleValue was introduced; however, the `to_font_slope()` function was not changed to understand this new type. When it tries to convert such a font style to a keyword, it fails. We then rendered the wrong font-style.

This bug caused text to render with the wrong font style, for example `font-style: italic` simply didn't render italic unless the font itself was italic.

*also* Fixes #4808

### CODE REVIEW

File: Libraries/LibWeb/CSS/CSSStyleValue.cpp [hunk 1]
```diff
@@ -457,7 +457,21 @@ int CSSStyleValue::to_font_slope() const
...
         case Keyword::Normal:
         default:
-            break;
+            static int normal_slope = Gfx::name_to_slope("Normal"sv);
+            return normal_slope;
+        }
+    } else if (is_font_style()) {
+        switch (as_font_style().font_style()) {
+        case FontStyle::Italic:
+            static int italic_slope = Gfx::name_to_slope("Italic"sv);
```
Comment (ADKaster) [inline Libraries/LibWeb/CSS/CSSStyleValue.cpp:466]: wow, this pattern is jank. that's a lot of static ints. A proper refactor to a better set of helper methods seems out of scope of the bugfix though.

Comment (AtkinsSJ) [reply Libraries/LibWeb/CSS/CSSStyleValue.cpp:466]: Agreed. In this PR though, we can get rid of the keyword-handling branch. [`Parser::parse_font_style_value()`](https://github.com/LadybirdBrowser/ladybird/blob/e2fa8cf7a862dc615cfa6c23716ed83ab1f8598e/Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp#L2613) only produces `FontStyleStyleValue`s now.

Once that's done, this is good to go! If you're interested in working on this further, that'd be good, but let's get this simple fix in first. :^)

Comment (lionkor) [reply Libraries/LibWeb/CSS/CSSStyleValue.cpp:466]: It's jank, yeah. I also just noticed that `Normal` isn't even an allowed `font_slope_name`, and `Oblique` doesn't use the actual slope specified in the `oblique` style...? Maybe a small refactor would fit in here.

**Comment by AtkinsSJ** [comment]
Oh actually, it'd also be good to get a test here to avoid this breaking again. :thonk:

**Comment by lionkor** [comment]
This would need a screenshot test, presumably, as I don't see anything else dumping the style of the text, right? New to this ;)

**Comment by lionkor** [comment]
> Oh actually, it'd also be good to get a test here to avoid this breaking again. :thonk:

I wrote screenshot tests, however they can never fail as SerenitySans doesn't provide an *italic* version. Is there a preferred font that I could add to the repo? Or is simply linking to googlefonts or similar in a css style sheet fine (I would guess not)?

**Comment by AtkinsSJ** [comment]
The commit linter is unhappy that your commit message has a line that's too long. You can install the commit hook to have that checked locally automatically: https://github.com/LadybirdBrowser/ladybird/blob/master/CONTRIBUTING.md#commit-hooks

Not sure what to do about testing fonts right now, so I think we can leave the test until later.

**Review by AtkinsSJ — APPROVED** [review]
Thank you for working on it!
