### PR TITLE
LibRegex: Prevent empty matches in optional quantifiers

### LINKED ISSUE #7117: LibRegex: Lookahead in optional quantified group captures incorrectly
### Summary

We fail to match these correctly:

`"abc".match(/(?:(?=(abc)))?a/);`
`"abc".match(/(?:(?=(abc))){0,1}a/);`

Should be `["a", undefined]`, but we get `["a","abc"]`. From what I can tell, we don't handle Step 4 from [here](https://tc39.es/ecma262/#sec-runtime-semantics-repeatmatcher-abstract-operation), but I couldn't figure out how to do this properly :(

### Operating system

Linux

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### URL for a reduced test case

https://codepen.io/aplefull/pen/jEqREqO?editors=0012

### HTML/SVG/etc. source for a reduced test case

```html
<script>
  console.log("abc".match(/(?:(?=(abc)))?a/));
  console.log("abc".match(/(?:(?=(abc))){0,1}a/));
</script>
```

### Log output and (if possible) backtrace

```shell
N/A
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### LINKED ISSUE #7332: LibRegex: Optional capture group returns empty string for non-participating match
With js REPL:

```
> new RegExp('^(.*)(.*)?$').exec('Shannon')[2]
""
```

Expected:

```
> new RegExp('^(.*)(.*)?$').exec('Shannon')[2]
undefined
```

cc @aplefull / @alimpfard

### PR DESCRIPTION
**Pull request by aplefull**
Step 2.b of the RepeatMatcher states that once minimum repetitions are satisfied, empty matches should not be considered for further repetitions. This was not being enforced for quantifiers that allow 0 matches,  like `?`, so we had extra capture group matches.

Fixes #7332 
Fixes #7117 

Test 262:
```
    test/built-ins/RegExp/S15.10.2.8_A3_T17.js                 ❌ -> ✅
    test/built-ins/RegExp/lookahead-quantifier-match-groups.js ❌ -> ✅
    test/staging/sm/RegExp/exec.js                             ❌ -> ✅
    test/staging/sm/RegExp/sticky.js                           ❌ -> ✅
```

### CODE REVIEW

File: Libraries/LibRegex/RegexByteCode.h [hunk 1]
```diff
@@ -715,6 +754,7 @@ class REGEX_API ByteCode : public ByteCodeBase
         // FORKJUMP _END  (FORKSTAY -> Greedy)
         // CHECKPOINT _C
         // REGEXP
+        // FAILIFEMPTY _C
         // JUMP_NONEMPTY _C _START JUMP
```
Comment (alimpfard) [inline Libraries/LibRegex/RegexByteCode.h:758]: This can then be a jump.

Comment (aplefull) [reply Libraries/LibRegex/RegexByteCode.h:758]: Will change! Yeah, I also wasn't sure about the new op, but I've had multiple attempts at trying to do that cleanly without it and couldn't make it work nicely. Oh, and I forgot to rebaseline WPT...

Comment (alimpfard) [reply Libraries/LibRegex/RegexByteCode.h:758]: Eh, we have the opcode space, might as well use it.

Comment (aplefull) [reply Libraries/LibRegex/RegexByteCode.h:758]: Ok, updated WPT expectations, should be good now
