### PR TITLE
LibWeb/CSS: Serialize shorthands with `var()` to original value

### LINKED ISSUE #7194: Crash when serializing shorthand with unresolved `var()` value
The browser crashes when clicking on one of the short videos on https://bbc.co.uk. I was able to recreate the crash with this snippet:
```html
<!DOCTYPE html>
<style>
div {
    transition: var(--foo);
}
</style>
<script>
    const declaration = document.styleSheets[0].cssRules[0].style;
    console.log(declaration.getPropertyValue("transition"));
</script>
```

Which produces this stack trace:
```
#0  0x000071bacefef9f6 in as_value_list at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/StyleValues/StyleValue.cpp:134:1
#1  0x000071bacefea69d in operator() at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp:82:70
#2  0x000071bacefe6228 in to_string at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp:859:16
#3  0x000071bacee32f6f in get_property_value at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/C
SSStyleProperties.cpp:358:39
#4  (inlined)          in operator() at /home/tim/repos/ladybird/Build/release/Lagom/Libraries/LibWeb/Bindings/CSSStyleDeclarationPrototype.cpp:297:36
#5  (inlined)          in throw_dom_exception_if_needed<(lambda at /home/tim/repos/ladybird/Build/release/Lagom/Libraries/LibWeb/Bindings/CSSStyleDeclarationPrototype.cpp:297:36), AK::String, AK::String> at /home/tim/repos/ladybird/Libraries/LibWeb/Bindings/ExceptionOrUtils.h:110:16
#6  0x000071bacf769bb3 in get_property_value at /home/tim/repos/ladybird/Build/release/Lagom/Libraries/LibWeb/Bindings/CSSStyleDeclarationPrototype.cpp:297:36
#7  (inlined)          in operator() at /home/tim/repos/ladybird/AK/Function.h:148:25
#8  0x000071bace15925b in call at /home/tim/repos/ladybird/Libraries/LibJS/Runtime/NativeFunction.cpp:219:12
#9  0x000071bace15905a in internal_call at /home/tim/repos/ladybird/Libraries/LibJS/Runtime/NativeFunction.cpp:156:19
#10 0x000071bacdfdf932 in execute_call<(JS::Bytecode::Op::CallType)0> at /home/tim/repos/ladybird/Libraries/LibJS/Bytecode/Interpreter.cpp:2484:18
#11 (inlined)          in execute_impl at /home/tim/repos/ladybird/Libraries/LibJS/Bytecode/Interpreter.cpp:2492:12
#12 0x000071bacdfcf48a in run_bytecode at /home/tim/repos/ladybird/Libraries/LibJS/Bytecode/Interpreter.cpp:475:13
#13 0x000071bacdfde5f7 in run_executable at /home/tim/repos/ladybird/Libraries/LibJS/Bytecode/Interpreter.cpp:668:5
#14 (inlined)          in run_executable at /home/tim/repos/ladybird/Libraries/LibJS/Bytecode/Interpreter.h:42:16
#15 0x000071bacdfcda73 in run at /home/tim/repos/ladybird/Libraries/LibJS/Bytecode/Interpreter.cpp:184:18
#16 0x000071bacf2e688a in run at /home/tim/repos/ladybird/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp:103:57
#17 0x000071bacf24e72f in execute_script at /home/tim/repos/ladybird/Libraries/LibWeb/HTML/HTMLScriptElement.cpp:169:67
#18 0x000071bacf24fdc1 in prepare_script at /home/tim/repos/ladybird/Libraries/LibWeb/HTML/HTMLScriptElement.cpp:630:13
#19 (inlined)          in prepare_script<Web::HTML::HTMLParser> at /home/tim/repos/ladybird/Libraries/LibWeb/HTML/HTMLScriptElement.h:42:37
#20 0x000071bacf2bd41a in handle_text at /home/tim/repos/ladybird/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:3379:17
#21 0x000071bacf2b7519 in run at /home/tim/repos/ladybird/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:251:13
#22 0x000071bacf2b876d in run at /home/tim/repos/ladybird/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:277:5
#23 (inlined)          in operator() at /home/tim/repos/ladybird/Libraries/LibWeb/DOM/DocumentLoading.cpp:102:25
#24 0x000071bacf043c2e in call at /home/tim/repos/ladybird/AK/Function.h:225:20
#25 (inlined)          in operator() at /home/tim/repos/ladybird/AK/Function.h:148:25
#26 (inlined)          in operator() at /home/tim/repos/ladybird/Libraries/LibWeb/Platform/EventLoopPluginSerenity.cpp:29:9
#27 0x000071bacf4add74 in call at /home/tim/repos/ladybird/AK/Function.h:225:20
#28 (inlined)          in operator() at /home/tim/repos/ladybird/AK/Function.h:148:25
#29 0x000071bacdd248c2 in process at /home/tim/repos/ladybird/Libraries/LibCore/ThreadEventQueue.cpp:135:17
#30 (inlined)          in pump at /home/tim/repos/ladybird/Libraries/LibCore/EventLoopImplementationUnix.cpp:308:40
#31 0x000071bacdd2a1eb in exec at /home/tim/repos/ladybird/Libraries/LibCore/EventLoopImplementationUnix.cpp:300:9
#32 0x000071bacdd146f6 in exec at /home/tim/repos/ladybird/Libraries/LibCore/EventLoop.cpp:100:20
#33 0x00005e6409e0c4d6 in ladybird_main at /home/tim/repos/ladybird/Services/WebContent/main.cpp:213:23
#34 0x00005e6409ee107f in main at /home/tim/repos/ladybird/Libraries/LibMain/Main.cpp:46:19
#35 0x000071bacc82a577 in __libc_start_call_main at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#36 0x000071bacc82a63a in __libc_start_main_impl at ./csu/../csu/libc-start.c:360:3
#37 0x00005e6409e0aeb4 in _start at /home/tim/repos/ladybird/Build/release/libexec/WebContent
```

The error occurs when a PendingSubstitutionValue is encountered where a value list is expected.

### PR DESCRIPTION
**Pull request by tcl3**
This PR fixes serialization of shorthand properties when `var()` is used.

To achieve this I've made `PendingSubstitutionStyleValue` store its original value.

Prevents a crash when clicking on the short videos on https://bbc.co.uk/news (the videos don't play yet, but let's take one step at a time)

Fixes #7194

### CODE REVIEW

File: Libraries/LibWeb/CSS/CSSStyleProperties.cpp [hunk 1]
```diff
@@ -486,6 +487,30 @@ Optional<StyleProperty> CSSStyleProperties::get_property_internal(PropertyNameAn
                 last_important_flag = declaration->important;
             }
 
+            // https://www.w3.org/TR/css-variables-1/#variables-in-shorthands
+            // If all of the component longhand properties for a given shorthand are pending-substitution values from
+            // the same original shorthand value, the shorthand property must serialize to that original
+            // (var()-containing) value.
+            // Otherwise, if any of the component longhand properties for a given shorthand are pending-substitution
+            // values, or contain var() functions of their own that have not yet been substituted, the shorthand
+            // property must serialize to the empty string.
```
Comment (tcl3) [inline Libraries/LibWeb/CSS/CSSStyleProperties.cpp]: I couldn't find this text in the current draft spec at: https://drafts.csswg.org/css-values-5/#pending-substitution-value. I'm not sure of the current spec would expect a test like the one I added here: `Tests/LibWeb/Text/input/css/getPropertyValue-shorthand-with-var.html` to output the empty string but this doesn't seem to be how other engines behave.

Comment (tcl3) [reply Libraries/LibWeb/CSS/CSSStyleProperties.cpp]: It turns out the relevant text is in the current draft spec. I've updated the text to match the current spec.

Reading is hard :sweat_smile:

**Review by AtkinsSJ — APPROVED** [review]
Very nice!
