### PR TITLE
LibRegex: Only search start of line if pattern begins with ^

### LINKED ISSUE #700: LibRegex: Searching for anchored patterns like /^b/ should fail early if possible
If we're looking for `/^b/` in the string `aaaaaa` (and multi-line mode is not enabled), we should be smarter than to scan through every single `a` before bailing.

Reduction from https://fragrantica.com/

```js
const mb = 100;
console.log("Create " + mb + "MB string");
let s = "a".repeat(mb * 1048576);

let re = /^b/
console.log("Search for " + re + " in string");
for (let i = 0; i < 10_000; ++i) {
    console.log(re.test(s));
}
```

## Funding

- We're using [Polar.sh](https://polar.sh/LadybirdBrowser) to allow folks to offer a reward for completing this issue.
- The contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/LadybirdBrowser/ladybird/issues/700">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/LadybirdBrowser/ladybird/issues/700/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by Gingeh**
Partially fixes #700.

If the first opcode is `CheckBegin` then the pattern can only ever match the start of each line.
This doesn't apply when the multiline flag is enabled.

Speeds up the example in #700 to 151ms 
(I'd include a 'before' time but I'm not patient enough to wait several hours)

If the example is tweaked to check a 10 MB string only 100 times then the execution time goes from 9815ms to 11ms.

### CODE REVIEW

File: Userland/Libraries/LibRegex/RegexOptimizer.cpp [hunk 1]
```diff
@@ -36,6 +36,11 @@ void Regex<Parser>::run_optimization_passes()
     // e.g. a*b -> (ATOMIC a*)b
     attempt_rewrite_loops_as_atomic_groups(blocks);
 
+    MatchState state;
+    auto& opcode = parser_result.bytecode.get_opcode(state);
+    if (opcode.opcode_id() == OpCodeId::CheckBegin)
+        parser_result.optimization_data.only_start_of_line = true;
```
Comment (alimpfard) [inline Userland/Libraries/LibRegex/RegexOptimizer.cpp:42]: There are a few more conditions this can be true in (e.g. within an arbitrarily nested capture group), but let's defer that to when it shows up in practice.

File: Userland/Libraries/LibRegex/RegexParser.h [hunk 2]
```diff
@@ -58,6 +58,7 @@ class Parser {
 
         struct {
             Optional<ByteString> pure_substring_search;
+            bool only_start_of_line;
```
Comment (alimpfard) [inline Userland/Libraries/LibRegex/RegexParser.h:61]: Please initialise all primitives.

**Review by alimpfard — COMMENTED** [review]
Looks right, but please add a test (your 10M sample is a good candidate for a benchmark case as well, see other optimisation tests/benchmarks)

File: Userland/Libraries/LibRegex/RegexOptimizer.cpp (hunk 1 above)
Comment (Gingeh) [reply Userland/Libraries/LibRegex/RegexOptimizer.cpp:42]: I should probably add a FIXME comment, then

**Comment by alimpfard** [comment]
Thank you for working on this.
