### PR TITLE
LibXML+LibWeb: XML related fixes

### LINKED ISSUE #612: LibWeb: Exception when getting innerHTML of SVG parsed by DOMParser
Reduced from https://jupyter.org/try-jupyter/lab/ (missing buttons in the "launcher")
```html
<!DOCTYPE html>
<body></body>
<script>
    const svgstr = `<svg xmlns="http://www.w3.org/2000/svg">PASS</svg>`;
    const svg = new DOMParser().parseFromString(svgstr, 'image/svg+xml').documentElement;
    console.log(svg.innerHTML);
</script>
```

Should print `PASS`, instead throws `InvalidStateError: Attribute's local name is 'xmlns' and the attribute has no namespace`.

### PR DESCRIPTION
**Pull request by sppmacd**
First commit makes "launcher" buttons appear on https://jupyter.org/try-jupyter/lab/.
The second one is just to make `innerHTML` actually return the same string on Ladybird as on Firefox / Chromium.

Before:
image

After:
image

Fixes #612.

### CODE REVIEW

File: Userland/Libraries/LibWeb/DOM/Node.cpp [hunk 1]
```diff
@@ -1490,6 +1490,17 @@ WebIDL::ExceptionOr<String> Node::serialize_fragment(DOMParsing::RequireWellForm
         return HTML::HTMLParser::serialize_html_fragment(*this, HTML::HTMLParser::SerializableShadowRoots::No, {}, fragment_serialization_mode);
 
     // 3. Return the XML serialization of node given require well-formed.
+    // AD-HOC: XML serialization algorithm returns the "outer" XML serialization of the node.
+    //         For inner, concatenate the serialization of all children.
+    if (fragment_serialization_mode == FragmentSerializationMode::Inner) {
```
Comment (sppmacd) [inline Userland/Libraries/LibWeb/DOM/Node.cpp:1495]: Is this maybe a spec bug? The [XML serializing an Element node](https://w3c.github.io/DOM-Parsing/#xml-serializing-an-element-node) algorithm is (almost) directly called from the `innerHTML` getter even though it serializes the outer XML...

File: Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp [hunk 2]
```diff
@@ -86,8 +86,15 @@ void XMLDocumentBuilder::element_start(const XML::Name& name, HashMap<XML::Name,
         MUST(m_current_node->append_child(node));
     }
 
-    for (auto const& attribute : attributes)
+    for (auto const& attribute : attributes) {
+        // https://www.w3.org/TR/xml-names/#ns-decl
```
Comment (sppmacd) [inline Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp:90]: I couldn't find any better source for this... but this is what other browsers do apparently.

Comment (alimpfard) [reply Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp:90]: This is fine, just link to the newer version ([Declaring Namespace](https://www.w3.org/TR/2006/REC-xml-names11-20060816/#ns-decl)) to avoid confusion, some behaviours _are_ gated behind xml 1.0 compat mode.

File: Userland/Libraries/LibWeb/DOM/Node.cpp (hunk 1 above)
Comment (alimpfard) [reply Userland/Libraries/LibWeb/DOM/Node.cpp:1495]: The spec does indeed expect the fragment serializing algorithm to return the contents rather than the node itself (see <https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#the-outerhtml-property>).
I'd call that a spec bug.

Comment (sideshowbarker) [reply Userland/Libraries/LibWeb/DOM/Node.cpp:1495]: Please consider raising a spec issue at https://github.com/whatwg/html/issues/new/choose

Comment (ADKaster) [reply Userland/Libraries/LibWeb/DOM/Node.cpp:1495]: ...and linking the spec bug here. We've got that pattern in a few places throughout LibWeb already.

Comment (sppmacd) [reply Userland/Libraries/LibWeb/DOM/Node.cpp:1495]: https://github.com/whatwg/html/issues/10478

**Review by dilshsnwaruna — APPROVED** [review]
