### PR TITLE
LibWeb: Reimplement transform interpolation according to spec

### LINKED ISSUE #6774: HTML getting into ImageDecoder somehow
I'm currently trying to understand why https://vincentgarreau.com/particles.js/ is not showing any particles.

I started debugging and it lead me on a wild ride:

1. We start with `ImageDecoderClient: Failed to decode image with ID 3: Decoding failed: Could not find suitable image decoder plugin for data` in `ImageDecider::ConnectionFromClient::decode_image_to_details()`
2. It is failing to find a suitable decode for it which is extremely sus but does not allow for much debugging, so I opted to dump the bytes to analyze them externally with `dbgln("Dump data:\n{}" ReadonlyBytes{encoded_buffer.data<u8>(), encoded_buffer.size()});`
3. This dumps the bytes in hex to console and I can look at them in cyberchef
4. The bytes are a somehow whole HTML document and I'm completely lost how they ended in the image decoder at all

These are the dumped bytes:
```
3c21444f43545950452068746d6c3e0a3c68746d6c206c616e673d22656e223e0a3c686561643e0a20203c6d65746120636861727365743d227574662d38223e0a20203c7469746c653e7061727469636c65732e6a73202d2041206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c65733c2f7469746c653e0a20200a20203c6d657461206e616d653d226465736372697074696f6e2220636f6e74656e743d227061727469636c65732e6a732069732061206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c65732e223e0a20203c6d657461206e616d653d22617574686f722220636f6e74656e743d2256696e63656e74204761727265617522202f3e0a20203c6d657461206e616d653d2276696577706f72742220636f6e74656e743d2277696474683d6465766963652d77696474682c20696e697469616c2d7363616c653d312e302c206d696e696d756d2d7363616c653d312e302c206d6178696d756d2d7363616c653d312e302c20757365722d7363616c61626c653d6e6f223e0a20200a20203c6c696e6b2072656c3d2273686f72746375742069636f6e2220747970653d22696d6167652f782d69636f6e2220687265663d2268747470733a2f2f76696e63656e74676172726561752e636f6d2f6173736574732f696d672f66617669636f6e2e69636f22202f3e0a20203c6c696e6b20687265663d2768747470733a2f2f666f6e74732e676f6f676c65617069732e636f6d2f6373733f66616d696c793d536f757263652b53616e732b50726f3a3430302c373030272072656c3d277374796c6573686565742720747970653d27746578742f637373273e0a20203c6c696e6b2072656c3d227374796c65736865657422206d656469613d2273637265656e2220687265663d226173736574732f5f6275696c642f6373732f6d61737465722e637373223e0a0a20203c6d657461206e616d653d22747769747465723a636172642220636f6e74656e743d2273756d6d6172795f6c617267655f696d616765223e0a20203c6d657461206e616d653d22747769747465723a63726561746f722220636f6e74656e743d224056696e63656e744761727265656175223e0a20203c6d657461206e616d653d22747769747465723a696d6167653a7372632220636f6e74656e743d2268747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a732f6173736574732f696d672f7061727469636c65736a732d6f672e706e67223e0a20203c6d6574612070726f70657274793d226f673a7469746c652220636f6e74656e743d227061727469636c65732e6a73202d2041206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c657322202f3e0a20203c6d6574612070726f70657274793d226f673a736974655f6e616d652220636f6e74656e743d227061727469636c65732e6a7322202f3e0a20203c6d6574612070726f70657274793d226f673a75726c2220636f6e74656e743d2268747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a732f22202f3e0a20203c6d6574612070726f70657274793d226f673a6465736372697074696f6e2220636f6e74656e743d2241206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c65732e22202f3e0a20203c6d6574612070726f70657274793d226f673a696d6167652220636f6e74656e743d2268747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a732f6173736574732f696d672f7061727469636c65736a732d6f672e706e6722202f3e0a3c2f686561643e0a3c626f64793e0a0a3c212d2d2069636f6e73202d2d3e0a3c73766720646973706c61793d226e6f6e65222077696474683d223022206865696768743d2230222076657273696f6e3d22312e312220786d6c6e733d22687474703a2f2f7777772e77332e6f72672f323030302f7376672220786d6c6e733a786c696e6b3d22687474703a2f2f7777772e77332e6f72672f313939392f786c696e6b223e0a3c646566733e0a3c73796d626f6c2069643d2269636f6e2d636f646570656e2d627574746f6e222076696577426f783d2230203020313532332031303234223e0a20203c7469746c653e636f646570656e2d627574746f6e3c2f7469746c653e0a20203c7061746820636c6173733d2270617468312220643d224d3838302e353938203436312e363231683430392e3433317639332e303931682d3430392e343331762d39332e3039317a223e3c2f706174683e0a20203c7061746820636c6173733d2270617468322220643d224d313236332e383032203530382e313636632d36382e3039322d36382e3039322d3130302e3534372d3230322e3734342d3130332e3231322d3239362e3136342039332e333533203132352e343237203231342e363736203233342e383138203336312e343535203239362e3136342d3134362e3737392035382e37342d3236322e373533203137342e3734392d3336312e343535203239362e31363420382e3031342d3130302e3033302033322e3435352d3232312e343535203130332e3231322d3239362e31363476307a223e3c2f706174683e0a20203c7061746820636c6173733d2270617468332220643d224d3234372e393639203436322e3938337639302e3338336c36372e3535392d34352e3139312d36372e3535392d34352e3139317a223e3c2f706174683e0a20203c7061746820636c6173733d2270617468342220643d224d3438312e313632203339372e3338762d3132352e3935326c2d3231312e353739203134312e3034312039342e3531332036332e323236203131372e3036362d37382e3331357a223e3c2f706174683e0a20203c7061746820636c6173733d2270617468352220643d224d3734362e3735203431322e3436396c2d3231312e3537392d3134312e303431763132352e3935326c3131372e3037352037382e3331352039342e3530342d36332e3232367a223e3c2f706174683e0a20203c7061746820636c6173733d2270617468362220643d224d3236392e353833203630332e3837326c3231312e353739203134312e303431762d3132352e3934346c2d3131372e3036362d37382e3239382d39342e3531332036332e327a223e3c2f706174683e0a20203c7061746820636c6173733d2270617468372220643d224d3533352e313731203631382e3937763132352e3934346c3231312e3537392d3134312e3034312d39342e3530342d36332e322d3131372e3037352037382e3239387a223e3c2f706174683e0a20203c7061746820636c6173733d2270617468382220643d224d3530382e313636203434342e3238396c2d39352e3530332036332e3838362039352e3530332036332e3838362039352e3531312d36332e3838362d39352e3531312d36332e3838367a223e3c2f706174683e0a20203c7061746820636c6173733d2270617468392220643d224d3530382e3136362030632d3238302e36343420302d3530382e313636203232372e3531342d3530382e313636203530382e313735733232372e353233203530382e313636203530382e313636203530382e313636633238302e3636312030203530382e3137352d3232372e353036203530382e3137352d3530382e313636732d3232372e3531342d3530382e3137352d3530382e3137352d3530382e31373576307a4d3832322e333734203630332e393036633020312e3139332d302e30383520322e3336312d302e32333720332e3533372d302e30353920302e3338312d302e31353220302e3737392d302e32313220312e3135392d302e31343420302e3736322d302e32373120312e3532332d302e34373420322e3236382d302e31313820302e3434392d302e32373920302e38382d302e34323320312e3330332d302e32313220302e36362d302e34333220312e33322d302e36393420312e39382d302e31373820302e3434392d302e34303620302e38382d302e36303120312e3330332d302e32383820302e3630392d302e35383420312e32312d302e39313420312e3830332d302e32333720302e3431352d302e35313620302e3832392d302e373720312e3233362d302e33363420302e3535392d302e37333620312e3130392d312e31343220312e3633332d302e32393620302e3431352d302e36303120302e3739362d302e39333120312e3137362d302e34323320302e3439392d302e38373220302e39392d312e33333720312e3435362d302e33353520302e3336342d302e37303220302e3732382d312e30373520312e3035382d302e34393120302e3434392d312e30303720302e38382d312e353420312e3238362d302e33393820302e3331332d302e37393620302e3632362d312e32313920302e3932322d302e31363120302e3130322d302e32393620302e3232382d302e34353720302e33336c2d3238372e323032203139312e343838632d342e35333620332e3032312d392e37343920342e3534352d31342e39383820342e3534352d352e32313320302d31302e3433352d312e3532332d31342e3937392d342e3534356c2d3238372e3139342d3139312e343731632d302e3135322d302e3130322d302e3238382d302e3232382d302e34342d302e33332d302e3432332d302e3239362d302e3832392d302e3630392d312e3232372d302e3932322d302e3532352d302e3431352d312e3034312d302e3834362d312e3533322d312e3238362d302e3337322d302e33332d302e3732382d302e3639342d312e3038332d312e3035382d302e3437342d302e3436352d302e3930362d302e3935362d312e3334362d312e3435362d302e3331332d302e3338312d302e3632362d302e3736322d302e3932322d312e3137362d302e3339382d302e3532352d302e3737392d312e3037352d312e3133342d312e3633332d302e3237312d302e3431352d302e3532352d302e3832392d302e3737392d312e3233362d302e33332d302e3539322d302e3632362d312e3139332d302e3931342d312e3830332d302e3230332d302e3433322d302e3431352d302e3836332d302e3630312d312e3330332d302e3236322d302e36362d302e3439312d312e33322d302e3639342d312e39382d302e3135322d302e3433322d302e3239362d302e3836332d302e3432332d312e3330332d302e3139352d302e3734352d302e33332d312e3530362d302e3437342d322e3236382d302e3036382d302e3338312d302e3136392d302e3737392d302e3231322d312e3135392d302e3136312d312e3137362d302e3234352d322e3334342d302e3234352d332e353337762d3139312e34383863302d312e31393320302e3039332d322e33363120302e3234352d332e35323120302e3035312d302e33393820302e3135322d302e37373920302e3231322d312e31373620302e3134342d302e37363220302e3237312d312e35323320302e3437342d322e32363820302e3132372d302e34343920302e3237312d302e383820302e3432332d312e33303320302e3230332d302e363620302e3433322d312e333220302e3639342d312e39363320302e3138362d302e34343920302e3339382d302e38383920302e3630312d312e333220302e3238382d302e36303920302e3538342d312e323120302e3931342d312e37383620302e3234352d302e34333220302e3530382d302e38343620302e3737392d312e32353220302e3335352d302e35353920302e3733362d312e31303920312e3133342d312e36333320302e3239362d302e33393820302e3630392d302e37393620302e3932322d312e31373620302e34342d302e34393920302e38382d302e393920312e3334362d312e34353620302e3335352d302e33363420302e3731312d302e37323820312e3038332d312e30353820302e3439312d302e34343920302e3939392d302e383820312e3533322d312e32383620302e3339382d302e33313320302e3830342d302e36323620312e3232372d302e39323220302e3135322d302e31303220302e3238382d302e32323820302e34342d302e33336c3238372e3231312d3139312e34373163392e3037322d362e3035312032302e3838362d362e3035312032392e39353820306c3238372e323032203139312e34373163302e31363120302e31303220302e32393620302e32323820302e34353720302e333320302e34323320302e32393620302e38323120302e36303920312e32313920302e39323220302e35323520302e34313520312e30343920302e38343620312e353420312e32383620302e33373220302e333320302e37313920302e36393420312e30373520312e30353820302e34373420302e34363520302e39313420302e39353620312e33333720312e34353620302e333320302e33383120302e36333520302e37373920302e39333120312e31373620302e34303620302e35323520302e37373920312e30373520312e31343220312e36333320302e32353420302e34313520302e35323520302e38323920302e373720312e32353220302e333320302e35373520302e36323620312e31373620302e39313420312e37383620302e31393520302e34333220302e34323320302e383820302e36303120312e333220302e32363220302e36343320302e34383220312e33303320302e36393420312e39363320302e31343420302e34333220302e33303520302e38363320302e34323320312e33303320302e31393520302e37343520302e333320312e35303620302e34373420322e32363820302e30363820302e33393820302e31363120302e37373920302e32313220312e31373620302e31363120312e31353920302e32333720322e33323720302e32333720332e353231763139312e343731682d302e3030387a223e3c2f706174683e0a20203c7061746820636c6173733d227061746831302220643d224d3736382e333732203535332e333636762d39302e3338336c2d36372e35352034352e3139312036372e35352034352e3139317a223e3c2f706174683e0a3c2f73796d626f6c3e0a3c73796d626f6c2069643d2269636f6e2d646f776e6c6f6164222076696577426f783d2230203020313032342031303234223e0a20203c7469746c653e646f776e6c6f61643c2f7469746c653e0a20203c7061746820636c6173733d2270617468312220643d224d313032342035313263302d3238322e37372d3232392e32332d3531322d3531322d353132732d353132203232392e32332d35313220353132203232392e3233203531322035313220353132203531322d3232392e3233203531322d3531327a4d39362035313263302d3232392e3735203138362e32352d343136203431362d34313673343136203138362e323520343136203431362d3138362e3235203431362d343136203431362d3431362d3138362e32352d3431362d3431367a4d3535372e323534203831332e3235366c3235362d3235362e3030326332342e3939342d32342e3939322032342e3939342d36352e35313420302d39302e353038732d36352e3531362d32342e3939342d39302e353120306c2d3134362e373434203134362e373434762d3335372e343963302d33352e3334362d32382e3635342d36342d36342d3634732d36342032382e3635342d3634203634763335372e34396c2d3134362e3734342d3134362e373436632d32342e3939342d32342e3939342d36352e3531382d32342e3939342d39302e35313220302d31322e3439362031322e3439382d31382e3734342032382e3837382d31382e3734342034352e32353673362e3234382033322e3735382031382e3734342034352e3235346c323536203235362e3030326332342e3939342032342e3939322036352e3531382032342e3939322039302e353120307a223e3c2f706174683e0a3c2f73796d626f6c3e0a3c73796d626f6c2069643d2269636f6e2d676974687562222076696577426f783d2230203020313032342031303234223e0a20203c7469746c653e6769746875623c2f7469746c653e0a20203c7061746820636c6173733d2270617468312220643d224d3531322030632d3238322e373720302d353132203232392e32332d35313220353132733232392e3233203531322035313220353132203531322d3232392e3233203531322d3531322d3232392e32332d3531322d3531322d3531327a4d3831362e303536203831362e303536632d33392e3531382033392e3531362d38352e3531322037302e3533322d3133362e3730382039322e3138362d31332e30303620352e352d32362e3231342031302e3332382d33392e362031342e343932762d37362e37333463302d34302e3333342d31332e3833342d37302d34312e352d38392031372e3333342d312e3636362033332e32352d342034372e37352d377332392e3833342d372e3333342034362d31332033302e3636362d31322e3431362034332e352d32302e32352032352e3136362d31382033372d33302e352032312e37352d32362e3636362032392e37352d34322e352031342e3333342d33342e3833342031392d353720372d34362e35383420372d37332e323563302d35312e3636362d31362e3833342d39352e3636362d35302e352d3133322031352e3333342d34302031332e3636362d38332e352d352d3133302e356c2d31322e352d312e35632d382e3636362d312d32342e323520322e3636362d34362e3735203131732d34372e37352032322d37352e3735203431632d33392e3636362d31312d38302e3833342d31362e352d3132332e352d31362e352d343320302d383420352e352d3132332031362e352d31372e3636362d31322d33342e3431362d32312e3931362d35302e32352d32392e3735732d32382e352d31332e3136362d33382d31362d31382e3333342d342e3538342d32362e352d352e32352d31332e3431362d302e3833342d31352e37352d302e352d3420302e3636362d352031632d31382e3636362034372e3333342d32302e3333342039302e3833342d35203133302e352d33332e3636362033362e3333342d35302e352038302e3333342d35302e352031333220302032362e36363620322e3333342035312e30383420372037332e32357331312034312e3136362031392035372031372e3931362033302032392e37352034322e352032342e3136362032322e3636362033372033302e352032372e3333342031342e3538342034332e352032302e32352033312e352031302034362031332033302e34313620352e3333342034372e37352037632d32372e3333342031382e3636362d34312034382e3333342d34312038397637382e3233632d31352e3039382d342e3439342d32392e39382d392e3830342d34342e362d31352e3938382d35312e3139342d32312e3635342d39372e3138382d35322e36372d3133362e3730362d39322e3138362d33392e3531362d33392e3531382d37302e3533342d38352e3531322d39322e3138362d3133362e3730382d32322e3339382d35322e3935382d33332e3735362d3130392e3236322d33332e3735362d3136372e3334387331312e3335382d3131342e33392033332e3735382d3136372e33356332312e3635342d35312e3139342035322e36372d39372e3138382039322e3138362d3133362e3730367338352e3531322d37302e353334203133362e3730362d39322e3138366335322e39362d32322e34203130392e3236342d33332e373538203136372e33352d33332e373538733131342e33392031312e333538203136372e33352033332e3735386335312e3139362032312e3635342039372e31392035322e3637203133362e3730382039322e3138362033392e3531362033392e3531362037302e3533322038352e3531322039322e313836203133362e3730362032322e3339382035322e39362033332e373536203130392e3236342033332e373536203136372e3335732d31312e333538203131342e33392d33332e373538203136372e3335632d32312e3635342035312e3139342d35322e36372039372e31392d39322e313836203133362e3730367a223e3c2f706174683e0a3c2f73796d626f6c3e0a3c2f646566733e0a3c2f7376673e0a0a3c212d2d2070616e656c202d2d3e0a3c64697620636c6173733d2270616e656c223e0a093c68313e7061727469636c65732e6a733c2f68313e0a20203c7370616e20636c6173733d22722d76657273696f6e223e76322e302e303c2f7370616e3e0a093c68323e41206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c65733c2f68323e0a093c756c3e0a09093c6c69206f6e636c69636b3d226761282773656e64272c20276576656e74272c2027476974487562272c2027636c69636b27293b223e0a2020202020203c6120687265663d2268747470733a2f2f6769746875622e636f6d2f56696e63656e74476172726561752f7061727469636c65732e6a732f22207461726765743d225f626c616e6b223e0a20202020202020203c7370616e20636c6173733d226c6162656c223e4769744875623c2f7370616e3e0a20202020202020203c64697620636c6173733d227376672d77726170223e0a202020202020202020203c73766720636c6173733d2269636f6e2d676974687562223e0a2020202020202020202020203c75736520786d6c6e733a786c696e6b3d22687474703a2f2f7777772e77332e6f72672f313939392f786c696e6b2220786c696e6b3a687265663d222369636f6e2d676974687562223e3c2f7573653e0a202020202020202020203c2f7376673e0a20202020202020203c2f6469763e0a2020202020203c2f613e0a202020203c2f6c693e0a09093c6c69206f6e636c69636b3d226761282773656e64272c20276576656e74272c2027446f776e6c6f6164272c2027636c69636b27293b223e0a2020202020203c6120646f776e6c6f616420687265663d2268747470733a2f2f6769746875622e636f6d2f56696e63656e74476172726561752f7061727469636c65732e6a732f617263686976652f6d61737465722e7a6970223e0a20202020202020203c7370616e20636c6173733d226c6162656c223e446f776e6c6f61643c2f7370616e3e0a20202020202020203c64697620636c6173733d227376672d77726170223e0a202020202020202020203c73766720636c6173733d2269636f6e2d646f776e6c6f6164223e0a2020202020202020202020203c75736520786d6c6e733a786c696e6b3d22687474703a2f2f7777772e77332e6f72672f313939392f786c696e6b2220786c696e6b3a687265663d222369636f6e2d646f776e6c6f6164223e3c2f7573653e0a202020202020202020203c2f7376673e0a20202020202020203c2f6469763e0a2020202020203c2f613e0a202020203c2f6c693e0a093c2f756c3e0a090a3c2f6469763e0a0a3c212d2d206d61736b202d2d3e0a3c212d2d203c696d67207372633d2268747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f31393538303434302f7061727469636c65736a732d6173736574732f776f726c646d61702d6d61736b2e706e6722207374796c653d22646973706c61793a626c6f636b3b706f736974696f6e3a6162736f6c7574653b7a2d696e6465783a3130303b746f703a303b6c6566743a303b77696474683a313030252220616c743d22223e202d2d3e0a0a3c212d2d207061727469636c65732e6a7320636f6e7461696e6572202d2d3e0a3c6469762069643d227061727469636c65732d6a73223e3c2f6469763e0a0a3c212d2d20636f756e74207061727469636c6573202d2d3e0a3c64697620636c6173733d22636f756e742d7061727469636c6573223e0a20203c7370616e20636c6173733d226a732d636f756e742d7061727469636c6573223e2d2d3c2f7370616e3e207061727469636c65730a3c2f6469763e0a0a3c64697620636c6173733d22626f782d746f70223e0a20200a20203c64697620636c6173733d22626f782d70726573657473223e0a202020203c7370616e20636c6173733d2273656c6563742d6c6162656c206a732d64702d6c6162656c206a732d64702d6c6162656c2d707265736574732220646174612d64703d2270726573657473223e2d2d3c2f7370616e3e0a202020203c756c2069643d226a732d73656c6563742d7072657365742220636c6173733d2273656c6563742d64726f70646f776e206a732d64702d64726f70646f776e2220646174612d64703d2270726573657473223e0a2020202020203c6c6920646174612d76616c3d2264656661756c74223e44656661756c743c2f6c693e0a2020202020203c6c6920646174612d76616c3d226e617361223e4e4153413c2f6c693e0a2020202020203c6c6920646174612d76616c3d22627562626c65223e427562626c653c2f6c693e0a2020202020203c6c6920646174612d76616c3d22736e6f77223e536e6f773c2f6c693e0a2020202020203c6c6920646174612d76616c3d226e79616e63617432223e4e79616e204361743c2f6c693e0a202020203c2f756c3e0a20203c2f6469763e0a0a20203c64697620636c6173733d22626f782d636f646570656e206a732d626f782d636f646570656e223e0a202020203c7370616e20636c6173733d22636f646570656e2d6c6162656c223e436f646550656e3c2f7370616e3e0a202020203c64697620636c6173733d22636f646570656e2d627574746f6e206a732d636f646570656e2d627574746f6e223e0a2020202020203c64697620636c6173733d227376672d77726170223e0a20202020202020203c73766720636c6173733d2269636f6e2d636f646570656e2d627574746f6e223e0a202020202020202020203c75736520786d6c6e733a786c696e6b3d22687474703a2f2f7777772e77332e6f72672f313939392f786c696e6b2220786c696e6b3a687265663d222369636f6e2d636f646570656e2d627574746f6e223e3c2f7573653e0a20202020202020203c2f7376673e0a2020202020203c2f6469763e0a202020203c2f6469763e0a202020203c666f726d20616374696f6e3d2268747470733a2f2f636f646570656e2e696f2f70656e2f646566696e6522206d6574686f643d22504f535422207461726765743d225f626c616e6b223e0a2020202020203c696e7075742069643d22646174612d696e7075742220747970653d2268696464656e22206e616d653d2264617461222076616c75653d22223e0a2020202020203c696e70757420636c6173733d22636f646570656e2d7375626d69742d62742220747970653d227375626d6974223e0a202020203c2f666f726d3e0a20203c2f6469763e0a0a20203c64697620636c6173733d22626f782d7368617265223e0a202020203c7370616e20636c6173733d2273656c6563742d6c6162656c206a732d64702d6c6162656c2220646174612d64703d227368617265223e53686172653c2f7370616e3e0a202020203c756c2069643d226a732d73686172652220636c6173733d2273656c6563742d64726f70646f776e206a732d64702d64726f70646f776e2220646174612d64703d227368617265223e0a2020202020203c6c693e0a20202020202020203c61207461726765743d225f626c616e6b2220687265663d22687474703a2f2f747769747465722e636f6d2f3f7374617475733d7061727469636c65732e6a73202d2041206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c65732068747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a73202532336a617661736372697074202532337061727469636c65732025323368746d6c352025323377656264657369676e223e547769747465723c2f613e0a2020202020203c2f6c693e0a2020202020203c6c693e0a20202020202020203c61207461726765743d225f626c616e6b2220687265663d2268747470733a2f2f7777772e66616365626f6f6b2e636f6d2f6469616c6f672f666565643f6170705f69643d37393938383034393031303235353626616d703b6c696e6b3d68747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a7326616d703b706963747572653d68747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a732f6173736574732f696d672f7061727469636c65736a732d6f672e706e6726616d703b6e616d653d7061727469636c65732e6a7326616d703b6465736372697074696f6e3d7061727469636c65732e6a73202d2041206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c657326616d703b72656469726563745f7572693d68747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a73223e46616365626f6f6b3c2f613e0a2020202020203c2f6c693e0a2020202020203c6c693e0a20202020202020203c61207461726765743d225f626c616e6b2220687265663d2268747470733a2f2f706c75732e676f6f676c652e636f6d2f73686172653f75726c3d68747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a73223e476f6f676c652b3c2f613e0a2020202020203c2f6c693e0a2020202020203c6c693e0a20202020202020203c61207461726765743d225f626c616e6b2220687265663d2268747470733a2f2f7777772e6c696e6b6564696e2e636f6d2f736861726541727469636c653f6d696e693d747275652675726c3d68747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a73267469746c653d7061727469636c65732e6a732673756d6d6172793d412532306c696768747765696768742532304a6176615363726970742532306c696272617279253230666f722532306372656174696e672532307061727469636c657326736f757263653d68747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a73223e4c696e6b6564496e3c2f613e0a2020202020203c2f6c693e0a2020202020203c6c693e0a20202020202020203c61207461726765743d225f626c616e6b2220687265663d22687474703a2f2f7777772e70696e7465726573742e636f6d2f70696e2f6372656174652f627574746f6e2f3f75726c3d68747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a7326616d703b6d656469613d68747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a732f6173736574732f696d672f7061727469636c65736a732d6f672e706e6726616d703b6465736372697074696f6e3d7061727469636c65732e6a73202d2041206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c65732068747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a732220646174612d70696e2d646f3d22627574746f6e50696e2220646174612d70696e2d636f6e6669673d2261626f7665223e50696e7465726573743c2f613e0a2020202020203c2f6c693e0a2020202020203c6c693e0a20202020202020203c61207461726765743d225f626c616e6b2220687265663d226d61696c746f3a7374657665406a6f62732e636f6d3f7375626a6563743d7061727469636c65732e6a73202d2041206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c657326616d703b626f64793d7061727469636c65732e6a73202d2041206c69676874776569676874204a617661536372697074206c69627261727920666f72206372656174696e67207061727469636c65732068747470733a2f2f76696e63656e74676172726561752e636f6d2f7061727469636c65732e6a73223e456d61696c3c2f613e0a2020202020203c2f6c693e0a202020203c2f756c3e0a20203c2f6469763e0a0a3c2f6469763e0a0a3c64697620636c6173733d22626f782d626f74746f6d206a732d626f782d626f74746f6d223e0a202020200a20203c64697620636c6173733d22626f782d676974687562223e0a202020203c6120687265663d2268747470733a2f2f6769746875622e636f6d2f56696e63656e74476172726561752f7061727469636c65732e6a732f22207461726765743d225f626c616e6b223e0a2020202020203c7370616e20636c6173733d226c6162656c223e7061727469636c65732e6a733c2f7370616e3e0a2020202020203c64697620636c6173733d227376672d77726170223e0a20202020202020203c73766720636c6173733d2269636f6e2d676974687562223e0a202020202020202020203c75736520786d6c6e733a786c696e6b3d22687474703a2f2f7777772e77332e6f72672f313939392f786c696e6b2220786c696e6b3a687265663d222369636f6e2d676974687562223e3c2f7573653e0a20202020202020203c2f7376673e0a2020202020203c2f6469763e0a202020203c2f613e0a20203c2f6469763e0a0a3c2f6469763e0a0a0a3c212d2d206c6f61646572202d2d3e0a3c6469762069643d226c6f61646572223e3c2f6469763e0a0a3c212d2d206c6962202d2d3e0a3c736372697074207372633d226173736574732f5f6275696c642f6a732f6c69622f7061727469636c65732e6a73223e3c2f7363726970743e0a3c736372697074207372633d226173736574732f5f6275696c642f6a732f6c69622f73746174732e6a73223e3c2f7363726970743e0a3c736372697074207372633d226173736574732f5f6275696c642f6a732f6c69622f6461742e6775692e6a73223e3c2f7363726970743e0a3c736372697074207372633d2268747470733a2f2f616a61782e676f6f676c65617069732e636f6d2f616a61782f6c6962732f6a71756572792f322e312e332f6a71756572792e6d696e2e6a73223e3c2f7363726970743e0a0a3c212d2d206461742e4755492061707020636f6e666967202d2d3e0a3c736372697074207372633d226173736574732f5f6275696c642f6a732f6775692e6a73223e3c2f7363726970743e0a0a3c212d2d20436f646550656e20636f6e666967202d2d3e0a3c736372697074207372633d226173736574732f5f6275696c642f6a732f636f646570656e2e6a73223e3c2f7363726970743e0a0a0a3c212d2d20616e616c7974696373202d2d3e0a3c7363726970743e0a20202866756e6374696f6e28692c732c6f2c672c722c612c6d297b695b27476f6f676c65416e616c79746963734f626a656374275d3d723b695b725d3d695b725d7c7c66756e6374696f6e28297b0a202028695b725d2e713d695b725d2e717c7c5b5d292e7075736828617267756d656e7473297d2c695b725d2e6c3d312a6e6577204461746528293b613d732e637265617465456c656d656e74286f292c0a20206d3d732e676574456c656d656e747342795461674e616d65286f295b305d3b612e6173796e633d313b612e7372633d673b6d2e706172656e744e6f64652e696e736572744265666f726528612c6d290a20207d292877696e646f772c646f63756d656e742c27736372697074272c272f2f7777772e676f6f676c652d616e616c79746963732e636f6d2f616e616c79746963732e6a73272c27676127293b0a0a202067612827637265617465272c202755412d393633313736362d38272c20276175746f27293b0a20206761282773656e64272c2027706167657669657727293b0a3c2f7363726970743e0a3c2f626f64793e0a3c2f68746d6c3e0a
```

The decode to this html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>particles.js - A lightweight JavaScript library for creating particles</title>
  
  <meta name="description" content="particles.js is a lightweight JavaScript library for creating particles.">
  <meta name="author" content="Vincent Garreau" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  
  <link rel="shortcut icon" type="image/x-icon" href="https://vincentgarreau.com/assets/img/favicon.ico" />
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" media="screen" href="assets/_build/css/master.css">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:creator" content="@VincentGarreeau">
  <meta name="twitter:image:src" content="https://vincentgarreau.com/particles.js/assets/img/particlesjs-og.png">
  <meta property="og:title" content="particles.js - A lightweight JavaScript library for creating particles" />
  <meta property="og:site_name" content="particles.js" />
  <meta property="og:url" content="https://vincentgarreau.com/particles.js/" />
  <meta property="og:description" content="A lightweight JavaScript library for creating particles." />
  <meta property="og:image" content="https://vincentgarreau.com/particles.js/assets/img/particlesjs-og.png" />
</head>
<body>

<!-- icons -->
<svg display="none" width="0" height="0" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<defs>
<symbol id="icon-codepen-button" viewBox="0 0 1523 1024">
  <title>codepen-button</title>
  <path class="path1" d="M880.598 461.621h409.431v93.091h-409.431v-93.091z"></path>
  <path class="path2" d="M1263.802 508.166c-68.092-68.092-100.547-202.744-103.212-296.164 93.353 125.427 214.676 234.818 361.455 296.164-146.779 58.74-262.753 174.749-361.455 296.164 8.014-100.030 32.455-221.455 103.212-296.164v0z"></path>
  <path class="path3" d="M247.969 462.983v90.383l67.559-45.191-67.559-45.191z"></path>
  <path class="path4" d="M481.162 397.38v-125.952l-211.579 141.041 94.513 63.226 117.066-78.315z"></path>
  <path class="path5" d="M746.75 412.469l-211.579-141.041v125.952l117.075 78.315 94.504-63.226z"></path>
  <path class="path6" d="M269.583 603.872l211.579 141.041v-125.944l-117.066-78.298-94.513 63.2z"></path>
  <path class="path7" d="M535.171 618.97v125.944l211.579-141.041-94.504-63.2-117.075 78.298z"></path>
  <path class="path8" d="M508.166 444.289l-95.503 63.886 95.503 63.886 95.511-63.886-95.511-63.886z"></path>
  <path class="path9" d="M508.166 0c-280.644 0-508.166 227.514-508.166 508.175s227.523 508.166 508.166 508.166c280.661 0 508.175-227.506 508.175-508.166s-227.514-508.175-508.175-508.175v0zM822.374 603.906c0 1.193-0.085 2.361-0.237 3.537-0.059 0.381-0.152 0.779-0.212 1.159-0.144 0.762-0.271 1.523-0.474 2.268-0.118 0.449-0.279 0.88-0.423 1.303-0.212 0.66-0.432 1.32-0.694 1.98-0.178 0.449-0.406 0.88-0.601 1.303-0.288 0.609-0.584 1.21-0.914 1.803-0.237 0.415-0.516 0.829-0.77 1.236-0.364 0.559-0.736 1.109-1.142 1.633-0.296 0.415-0.601 0.796-0.931 1.176-0.423 0.499-0.872 0.99-1.337 1.456-0.355 0.364-0.702 0.728-1.075 1.058-0.491 0.449-1.007 0.88-1.54 1.286-0.398 0.313-0.796 0.626-1.219 0.922-0.161 0.102-0.296 0.228-0.457 0.33l-287.202 191.488c-4.536 3.021-9.749 4.545-14.988 4.545-5.213 0-10.435-1.523-14.979-4.545l-287.194-191.471c-0.152-0.102-0.288-0.228-0.44-0.33-0.423-0.296-0.829-0.609-1.227-0.922-0.525-0.415-1.041-0.846-1.532-1.286-0.372-0.33-0.728-0.694-1.083-1.058-0.474-0.465-0.906-0.956-1.346-1.456-0.313-0.381-0.626-0.762-0.922-1.176-0.398-0.525-0.779-1.075-1.134-1.633-0.271-0.415-0.525-0.829-0.779-1.236-0.33-0.592-0.626-1.193-0.914-1.803-0.203-0.432-0.415-0.863-0.601-1.303-0.262-0.66-0.491-1.32-0.694-1.98-0.152-0.432-0.296-0.863-0.423-1.303-0.195-0.745-0.33-1.506-0.474-2.268-0.068-0.381-0.169-0.779-0.212-1.159-0.161-1.176-0.245-2.344-0.245-3.537v-191.488c0-1.193 0.093-2.361 0.245-3.521 0.051-0.398 0.152-0.779 0.212-1.176 0.144-0.762 0.271-1.523 0.474-2.268 0.127-0.449 0.271-0.88 0.423-1.303 0.203-0.66 0.432-1.32 0.694-1.963 0.186-0.449 0.398-0.889 0.601-1.32 0.288-0.609 0.584-1.21 0.914-1.786 0.245-0.432 0.508-0.846 0.779-1.252 0.355-0.559 0.736-1.109 1.134-1.633 0.296-0.398 0.609-0.796 0.922-1.176 0.44-0.499 0.88-0.99 1.346-1.456 0.355-0.364 0.711-0.728 1.083-1.058 0.491-0.449 0.999-0.88 1.532-1.286 0.398-0.313 0.804-0.626 1.227-0.922 0.152-0.102 0.288-0.228 0.44-0.33l287.211-191.471c9.072-6.051 20.886-6.051 29.958 0l287.202 191.471c0.161 0.102 0.296 0.228 0.457 0.33 0.423 0.296 0.821 0.609 1.219 0.922 0.525 0.415 1.049 0.846 1.54 1.286 0.372 0.33 0.719 0.694 1.075 1.058 0.474 0.465 0.914 0.956 1.337 1.456 0.33 0.381 0.635 0.779 0.931 1.176 0.406 0.525 0.779 1.075 1.142 1.633 0.254 0.415 0.525 0.829 0.77 1.252 0.33 0.575 0.626 1.176 0.914 1.786 0.195 0.432 0.423 0.88 0.601 1.32 0.262 0.643 0.482 1.303 0.694 1.963 0.144 0.432 0.305 0.863 0.423 1.303 0.195 0.745 0.33 1.506 0.474 2.268 0.068 0.398 0.161 0.779 0.212 1.176 0.161 1.159 0.237 2.327 0.237 3.521v191.471h-0.008z"></path>
  <path class="path10" d="M768.372 553.366v-90.383l-67.55 45.191 67.55 45.191z"></path>
</symbol>
<symbol id="icon-download" viewBox="0 0 1024 1024">
  <title>download</title>
  <path class="path1" d="M1024 512c0-282.77-229.23-512-512-512s-512 229.23-512 512 229.23 512 512 512 512-229.23 512-512zM96 512c0-229.75 186.25-416 416-416s416 186.25 416 416-186.25 416-416 416-416-186.25-416-416zM557.254 813.256l256-256.002c24.994-24.992 24.994-65.514 0-90.508s-65.516-24.994-90.51 0l-146.744 146.744v-357.49c0-35.346-28.654-64-64-64s-64 28.654-64 64v357.49l-146.744-146.746c-24.994-24.994-65.518-24.994-90.512 0-12.496 12.498-18.744 28.878-18.744 45.256s6.248 32.758 18.744 45.254l256 256.002c24.994 24.992 65.518 24.992 90.51 0z"></path>
</symbol>
<symbol id="icon-github" viewBox="0 0 1024 1024">
  <title>github</title>
  <path class="path1" d="M512 0c-282.77 0-512 229.23-512 512s229.23 512 512 512 512-229.23 512-512-229.23-512-512-512zM816.056 816.056c-39.518 39.516-85.512 70.532-136.708 92.186-13.006 5.5-26.214 10.328-39.6 14.492v-76.734c0-40.334-13.834-70-41.5-89 17.334-1.666 33.25-4 47.75-7s29.834-7.334 46-13 30.666-12.416 43.5-20.25 25.166-18 37-30.5 21.75-26.666 29.75-42.5 14.334-34.834 19-57 7-46.584 7-73.25c0-51.666-16.834-95.666-50.5-132 15.334-40 13.666-83.5-5-130.5l-12.5-1.5c-8.666-1-24.25 2.666-46.75 11s-47.75 22-75.75 41c-39.666-11-80.834-16.5-123.5-16.5-43 0-84 5.5-123 16.5-17.666-12-34.416-21.916-50.25-29.75s-28.5-13.166-38-16-18.334-4.584-26.5-5.25-13.416-0.834-15.75-0.5-4 0.666-5 1c-18.666 47.334-20.334 90.834-5 130.5-33.666 36.334-50.5 80.334-50.5 132 0 26.666 2.334 51.084 7 73.25s11 41.166 19 57 17.916 30 29.75 42.5 24.166 22.666 37 30.5 27.334 14.584 43.5 20.25 31.5 10 46 13 30.416 5.334 47.75 7c-27.334 18.666-41 48.334-41 89v78.23c-15.098-4.494-29.98-9.804-44.6-15.988-51.194-21.654-97.188-52.67-136.706-92.186-39.516-39.518-70.534-85.512-92.186-136.708-22.398-52.958-33.756-109.262-33.756-167.348s11.358-114.39 33.758-167.35c21.654-51.194 52.67-97.188 92.186-136.706s85.512-70.534 136.706-92.186c52.96-22.4 109.264-33.758 167.35-33.758s114.39 11.358 167.35 33.758c51.196 21.654 97.19 52.67 136.708 92.186 39.516 39.516 70.532 85.512 92.186 136.706 22.398 52.96 33.756 109.264 33.756 167.35s-11.358 114.39-33.758 167.35c-21.654 51.194-52.67 97.19-92.186 136.706z"></path>
</symbol>
</defs>
</svg>

<!-- panel -->
<div class="panel">
	<h1>particles.js</h1>
  <span class="r-version">v2.0.0</span>
	<h2>A lightweight JavaScript library for creating particles</h2>
	<ul>
		<li onclick="ga('send', 'event', 'GitHub', 'click');">
      <a href="https://github.com/VincentGarreau/particles.js/" target="_blank">
        <span class="label">GitHub</span>
        <div class="svg-wrap">
          <svg class="icon-github">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-github"></use>
          </svg>
        </div>
      </a>
    </li>
		<li onclick="ga('send', 'event', 'Download', 'click');">
      <a download href="https://github.com/VincentGarreau/particles.js/archive/master.zip">
        <span class="label">Download</span>
        <div class="svg-wrap">
          <svg class="icon-download">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-download"></use>
          </svg>
        </div>
      </a>
    </li>
	</ul>
	
</div>

<!-- mask -->
<!-- <img src="https://dl.dropboxusercontent.com/u/19580440/particlesjs-assets/worldmap-mask.png" style="display:block;position:absolute;z-index:100;top:0;left:0;width:100%" alt=""> -->

<!-- particles.js container -->
<div id="particles-js"></div>

<!-- count particles -->
<div class="count-particles">
  <span class="js-count-particles">--</span> particles
</div>

<div class="box-top">
  
  <div class="box-presets">
    <span class="select-label js-dp-label js-dp-label-presets" data-dp="presets">--</span>
    <ul id="js-select-preset" class="select-dropdown js-dp-dropdown" data-dp="presets">
      <li data-val="default">Default</li>
      <li data-val="nasa">NASA</li>
      <li data-val="bubble">Bubble</li>
      <li data-val="snow">Snow</li>
      <li data-val="nyancat2">Nyan Cat</li>
    </ul>
  </div>

  <div class="box-codepen js-box-codepen">
    <span class="codepen-label">CodePen</span>
    <div class="codepen-button js-codepen-button">
      <div class="svg-wrap">
        <svg class="icon-codepen-button">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-codepen-button"></use>
        </svg>
      </div>
    </div>
    <form action="https://codepen.io/pen/define" method="POST" target="_blank">
      <input id="data-input" type="hidden" name="data" value="">
      <input class="codepen-submit-bt" type="submit">
    </form>
  </div>

  <div class="box-share">
    <span class="select-label js-dp-label" data-dp="share">Share</span>
    <ul id="js-share" class="select-dropdown js-dp-dropdown" data-dp="share">
      <li>
        <a target="_blank" href="http://twitter.com/?status=particles.js - A lightweight JavaScript library for creating particles https://vincentgarreau.com/particles.js %23javascript %23particles %23html5 %23webdesign">Twitter</a>
      </li>
      <li>
        <a target="_blank" href="https://www.facebook.com/dialog/feed?app_id=799880490102556&amp;link=https://vincentgarreau.com/particles.js&amp;picture=https://vincentgarreau.com/particles.js/assets/img/particlesjs-og.png&amp;name=particles.js&amp;description=particles.js - A lightweight JavaScript library for creating particles&amp;redirect_uri=https://vincentgarreau.com/particles.js">Facebook</a>
      </li>
      <li>
        <a target="_blank" href="https://plus.google.com/share?url=https://vincentgarreau.com/particles.js">Google+</a>
      </li>
      <li>
        <a target="_blank" href="https://www.linkedin.com/shareArticle?mini=true&url=https://vincentgarreau.com/particles.js&title=particles.js&summary=A%20lightweight%20JavaScript%20library%20for%20creating%20particles&source=https://vincentgarreau.com/particles.js">LinkedIn</a>
      </li>
      <li>
        <a target="_blank" href="http://www.pinterest.com/pin/create/button/?url=https://vincentgarreau.com/particles.js&amp;media=https://vincentgarreau.com/particles.js/assets/img/particlesjs-og.png&amp;description=particles.js - A lightweight JavaScript library for creating particles https://vincentgarreau.com/particles.js" data-pin-do="buttonPin" data-pin-config="above">Pinterest</a>
      </li>
      <li>
        <a target="_blank" href="mailto:steve@jobs.com?subject=particles.js - A lightweight JavaScript library for creating particles&amp;body=particles.js - A lightweight JavaScript library for creating particles https://vincentgarreau.com/particles.js">Email</a>
      </li>
    </ul>
  </div>

</div>

<div class="box-bottom js-box-bottom">
    
  <div class="box-github">
    <a href="https://github.com/VincentGarreau/particles.js/" target="_blank">
      <span class="label">particles.js</span>
      <div class="svg-wrap">
        <svg class="icon-github">
          <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-github"></use>
        </svg>
      </div>
    </a>
  </div>

</div>


<!-- loader -->
<div id="loader"></div>

<!-- lib -->
<script src="assets/_build/js/lib/particles.js"></script>
<script src="assets/_build/js/lib/stats.js"></script>
<script src="assets/_build/js/lib/dat.gui.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<!-- dat.GUI app config -->
<script src="assets/_build/js/gui.js"></script>

<!-- CodePen config -->
<script src="assets/_build/js/codepen.js"></script>


<!-- analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-9631766-8', 'auto');
  ga('send', 'pageview');
</script>
</body>
</html>
```

Anyone with an idea what is happening here would be a great help.

CC @gmta because we spoke about this not working before.

### PR DESCRIPTION
**Pull request by gmta**
We had a partial implementation of transformation function interpolation that did not support numerical interpolation of simple functions (e.g. `scale(0)` -> `scale(1)`). This refactors the interpolation to follow the spec more closely.

Gains us 267 WPT subtest passes in `css/css-transforms`.

Fixes #6774.

CC: @fdellwing

### CODE REVIEW

**Comment by fdellwing** [comment]
@gmta While it *kind of* works on the demo page (still looks nothing close to as it does in Firefox), it is still completely broken on the live website.

(I also ran into a WebContent crash with the demo page, but that is unrelated to this and might be working on master)

**Comment by gmta** [comment]
@fdellwing these are my results on this branch:

| Firefox | Ladybird |
|--|--|
| image | image |

Mind sharing your results?

**Comment by fdellwing** [comment]
Firefox (lots of lines with dots moving around and connecting to new dots)
grafik


LB (a few feint lines, flickering all the time, no dots at all)
grafik

File: Libraries/LibWeb/CSS/Interpolation.cpp [hunk 1]
```diff
@@ -1037,20 +963,373 @@ RefPtr<StyleValue const> interpolate_transform(DOM::Element& element, StyleValue
...
+        return KeywordStyleValue::create(Keyword::None);
+    }
+
+    // * Treating none as a list of zero length, if Va or Vb differ in length:
+    auto style_value_to_transformations = [](StyleValue const& style_value)
+        -> Vector<NonnullRefPtr<TransformationStyleValue const>> {
+        if (style_value.is_transformation())
+            return { style_value.as_transformation() };
+
+        // LB-NOTE: This encompasses both the allowed value "none" and any invalid values.
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/Interpolation.cpp]: I think we've settled on using `// NB:` for our own notes.

Comment (gmta) [reply Libraries/LibWeb/CSS/Interpolation.cpp]: Oh! When/where did we?

File: Libraries/LibWeb/CSS/Interpolation.cpp [hunk 2]
```diff
@@ -1037,20 +963,373 @@ RefPtr<StyleValue const> interpolate_transform(DOM::Element& element, StyleValue
...
+        if (!style_value.is_value_list())
+            return {};
+
+        Vector<NonnullRefPtr<TransformationStyleValue const>> result;
+        for (auto const& value : style_value.as_value_list().values()) {
+            if (value->is_transformation())
+                result.append(value->as_transformation());
+        }
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/Interpolation.cpp:1000]: This feels a bit odd to me... If we somehow have a non-TransformationStyleValue in our list, we ignore it, which makes the following behaviour incorrect. I don't think we *can* have one though, currently, as this only runs for `transform` and that either has a list of those, or just `none` on its own.

Eventually I think we need to interpolate registered custom properties, which might contains transformation functions, but even in that case we'd need to handle this differently.

I'm not entirely familiar with interpolation, but I think either this should VERIFY or it needs to fall back to discrete interpolation if there's a non-transformation in there.

File: Libraries/LibWeb/CSS/Interpolation.cpp [hunk 3]
```diff
@@ -1037,20 +963,373 @@ RefPtr<StyleValue const> interpolate_transform(DOM::Element& element, StyleValue
...
+    auto is_3d_transform = [&is_2d_transform, &is_3d_primitive](TransformFunction function) {
+        return is_2d_transform(function)
+            || is_3d_primitive(function)
+            || first_is_one_of(function,
+                TransformFunction::RotateX,
+                TransformFunction::RotateY,
+                TransformFunction::RotateZ,
+                TransformFunction::ScaleZ,
+                TransformFunction::TranslateZ);
+    };
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/Interpolation.cpp:1049]: I'd be inclined to put these categories in TransformFunctions.json.

File: Libraries/LibWeb/CSS/Interpolation.cpp [hunk 4]
```diff
@@ -1037,20 +963,373 @@ RefPtr<StyleValue const> interpolate_transform(DOM::Element& element, StyleValue
...
+            // LB-NOTE: 3D primitives do not need value expansion like their 2D counterparts do, so we check if they are
+            //          already a primitive first.
+            if (!is_3d_primitive(from_function))
+                from_transformation = convert_3d_transform_to_primitive(from_transformation);
+            if (!is_3d_primitive(to_function))
+                to_transformation = convert_3d_transform_to_primitive(to_transformation);
+        } else if (from_function != to_function) {
+            // LB-NOTE: We failed to convert both arguments to their primitives. This happens when trying to
+            //          interpolate two functions such as matrix() and translate() that cannot be interpolated
+            //          between numerically. Break here so the next loop can take care of the remaining functions.
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/Interpolation.cpp]: The `matrix[3d]()` functions are handled above, at line 1185. The only functions that would reach here are the skews I think? I'm not sure what's special about those but I'm not a maths person. :sweat_smile:

File: Libraries/LibWeb/CSS/Interpolation.cpp [hunk 5]
```diff
@@ -1037,20 +963,373 @@ RefPtr<StyleValue const> interpolate_transform(DOM::Element& element, StyleValue
...
+            result.append(*interpolated_rotation);
+        } else {
+            StyleValueVector interpolated;
+            interpolated.ensure_capacity(from_values.size());
+            for (size_t i = 0; i < from_values.size(); ++i) {
+                auto interpolated_value = interpolate_value(element, calculation_context, from_values[i], to_values[i],
+                    delta, AllowDiscrete::No);
+                if (!interpolated_value)
+                    break;
+                interpolated.append(*interpolated_value);
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/Interpolation.cpp]: You can do an unchecked append.

File: Libraries/LibWeb/CSS/Interpolation.cpp [hunk 6]
```diff
@@ -1037,20 +963,373 @@ RefPtr<StyleValue const> interpolate_transform(DOM::Element& element, StyleValue
...
+            }
+            if (interpolated.size() != from_values.size())
+                break;
+            result.append(TransformationStyleValue::create(PropertyID::Transform, from_function, move(interpolated)));
+        }
+    }
+
+    static constexpr auto make_transformation = [](TransformationStyleValue const& transformation) -> Optional<Transformation> {
+        Vector<TransformValue> values;
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/Interpolation.cpp]: I think you could ensure_capacity() for this too.

File: Libraries/LibWeb/CSS/Interpolation.cpp [hunk 7]
```diff
@@ -1037,20 +963,373 @@ RefPtr<StyleValue const> interpolate_transform(DOM::Element& element, StyleValue
...
+    auto to_matrix = post_multiply_remaining_transformations(index, to_transformations);
+
+    auto maybe_interpolated_matrix = interpolate_matrices(from_matrix, to_matrix, delta);
+    if (maybe_interpolated_matrix.has_value()) {
+        auto interpolated_matrix = maybe_interpolated_matrix.release_value();
+        StyleValueVector values;
+        values.ensure_capacity(16);
+        for (int i = 0; i < 16; i++)
+            values.append(NumberStyleValue::create(interpolated_matrix[i % 4, i / 4]));
+        result.append(TransformationStyleValue::create(PropertyID::Transform, TransformFunction::Matrix3d, move(values)));
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/Interpolation.cpp]: Unchecked appends again (though this was existing code).

File: Libraries/LibWeb/CSS/StyleValues/TransformationStyleValue.cpp [hunk 8]
```diff
@@ -23,14 +23,79 @@
...
 #include <LibWeb/CSS/StyleValues/LengthStyleValue.h>
 #include <LibWeb/CSS/StyleValues/NumberStyleValue.h>
 #include <LibWeb/CSS/StyleValues/PercentageStyleValue.h>
+#include <LibWeb/CSS/StyleValues/TransformationStyleValue.h>
 #include <LibWeb/CSS/Transformation.h>
 #include <LibWeb/Geometry/DOMMatrix.h>
 
 namespace Web::CSS {
 
+ValueComparingNonnullRefPtr<TransformationStyleValue const> TransformationStyleValue::identity_transformation(
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/StyleValues/TransformationStyleValue.cpp:36]: This could maybe be generated too, but that might be more code than this is. :sweat_smile:

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]

File: Libraries/LibWeb/CSS/Interpolation.cpp (hunk 1 above)
Comment (AtkinsSJ) [reply Libraries/LibWeb/CSS/Interpolation.cpp]: Huh, looks like I'm misremembering. I did find https://discord.com/channels/1247070541085671459/1247090064480014443/1314383261266345994 but it's hardly conclusive.

Doing a search though for NB, Spec-note and LB-NOTE (all insensitive just in case), NB is the most common... though it looks like it's almost entirely me writing those. :laughing: So feel free to disregard this, though we should probably come to some kind of standard.

Comment (gmta) [reply Libraries/LibWeb/CSS/Interpolation.cpp]: Let's deal with it here: #6841

Comment (nico) [reply Libraries/LibWeb/CSS/Interpolation.cpp]: (It's short for NotyBird.)

File: Libraries/LibWeb/CSS/Interpolation.cpp (hunk 3 above)
Comment (gmta) [reply Libraries/LibWeb/CSS/Interpolation.cpp:1049]: Their reusability is extremely low though, that's why I made them lambdas in the first place. As far as I can see, they're only used here specifically and generating anything from TransformFunctions.json will take many more lines of code to achieve exactly the same result.

File: Libraries/LibWeb/CSS/StyleValues/TransformationStyleValue.cpp (hunk 8 above)
Comment (gmta) [reply Libraries/LibWeb/CSS/StyleValues/TransformationStyleValue.cpp:36]: Yeah definitely more code, don't think it's worth it.

File: Libraries/LibWeb/CSS/Interpolation.cpp (hunk 4 above)
Comment (gmta) [reply Libraries/LibWeb/CSS/Interpolation.cpp]: That comment was out of date, and that entire `else if` block could be dropped anyway - we check its condition again a couple of lines down with a better description of what's going on.

File: Libraries/LibWeb/CSS/Interpolation.cpp (hunk 2 above)
Comment (gmta) [reply Libraries/LibWeb/CSS/Interpolation.cpp:1000]: > I don't think we can have one though

That's right

> but I think either this should VERIFY

I agree! This was lifted/moved from existing code, but we can simplify it a bit.

**Comment by gmta** [comment]
@fdellwing what platform are you building and running Ladybird on?

I've tried Ladybird on Linux x86_64 as well, looks fine to me:

image

**Comment by gmta** [comment]
@fdellwing the company website on Linux x86_64, Ladybird (left) and Chrome (right):

image

**Comment by fdellwing** [comment]
I'm running it on WSL2 + Ubuntu 22.04 + VcXsrv

**Comment by gmta** [comment]
@fdellwing 

> VcXsrv

I suppose this means no GPU acceleration; if I force CPU painting I see some flickering but the effect is clearly there. I'm 99% sure the issues I'm seeing are not related to the changes in this PR.

**Comment by fdellwing** [comment]
It is clearly better than without this PR.

I will try on native Ubuntu tomorrow. Had no such problems with my Windows setup in the past though.

**Comment by fdellwing** [comment]
@gmta Ok, the demo does work on native Ubuntu.

I tried a lot of things with WSL2 today, even switching to WSLg, but I will not get hardware acceleration with my current GPU. So, this is a CPU renderer problem.

The company website mouse hover does not work in native Ubuntu though, but the passive animation works.
