### PR TITLE
LibWasm: Disable direct threading entirely if musttail is not available

### LINKED ISSUE #7009: copy.sh/v86 crashes Ladybird
### Summary

When I try to launch SerenityOS in v86 in Ladybird via https://copy.sh/v86/?profile=serenity, Ladybird crashes.

Source code: https://github.com/copy/v86

### Operating system

Linux 6.17.8 #1-NixOS SMP PREEMPT_DYNAMIC Thu Nov 13 20:37:49 UTC 2025

```
ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20251124.1c8ba8d"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_END="2025-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"
```

### Steps to reproduce

1. Go to https://copy.sh/v86/?profile=serenity
2. Wait for download to finish
3. After a few seconds, it crashes with "Ladybird flew off-course!"

### Expected behavior

The VM would start and run

### Actual behavior

The website crashes before the VM is visible.

### URL for a reduced test case

https://copy.sh/v86/?profile=serenity

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
2532.763 Ladybird(73580): WebContent process crashed! Last page loaded: https://copy.sh/v86/?profile=serenity
2532.763 Ladybird(73580): Consider raising an issue at https://github.com/LadybirdBrowser/ladybird/issues/new/choose
2532.767 WebContent(74770): FIXME: Handle null navigation_request in navigation response Content Security Policy check.
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

Launched using:

```
nix run github:NixOS/nixpkgs/master#ladybird
```

rev: a0e85ff7490e554dade846937267d034fda7d49d

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### LINKED ISSUE #7038: Crash when loading LifeViewer Pro
### Summary

Attempting to go to https://lazyslug.com/lifeviewer/pro/ will cause Ladybird to crash before loading of page content concludes.

### Operating system

Linux

### Steps to reproduce

1. Open Ladybird
2. Navigate to https://lazyslug.com/lifeviewer/pro/
3. Wait

### Expected behavior

LifeViewer Pro would load as expected.

### Actual behavior

We instead crash before it appears.

### URL for a reduced test case

https://lazyslug.com/lifeviewer/pro/

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
./Meta/ladybird.py run
ninja: Entering directory `/home/conputer/other-dev/ladybird/20250807210822/ladybird/Build/release'
ninja: no work to do.
Ladybird PID file '/run/user/1000/Ladybird.pid' exists with PID 14824, but process cannot be found
5283.097 WebContent(15027): (js log) "WebAssembly instantiated: 102 functions (161857 bytes), 1792Mb heap, time 636.8ms"
5283.170 WebContent(15027): (js log) "refresh rate" "165Hz Auto"
5283.301 WebContent(15027): (js) "read embedded: 0.105 seconds"
5283.301 WebContent(15027): (js) "page scan: 0.131 seconds"
5283.301 WebContent(15027): (js log) "1 embedded and 0 popup (0 unsafe)"
5284.510 Ladybird(15004): WebContent process crashed! Last page loaded: https://lazyslug.com/lifeviewer/pro/
5284.510 Ladybird(15004): Consider raising an issue at https://github.com/LadybirdBrowser/ladybird/issues/new/choose
5284.511 WebContent(15044): FIXME: Handle null navigation_request in navigation response Content Security Policy check.
```

### Screenshots or screen recordings

Image

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by alimpfard**
Otherwise we can end up crashing due to stack overflow (see #7009).

fixes #7009
fixes #7038

### CODE REVIEW

File: Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp [hunk 1]
```diff
@@ -38,7 +38,8 @@ using namespace AK::SIMD;
 // ASAN allocates frames for all the not-explicitly-tail-called functions,
 // which blows out the stack. So disable direct threading when ASAN is enabled.
 // We use the explicit annotation where available, so allow it there.
-#if defined(HAS_ADDRESS_SANITIZER) && !defined(HAS_TAILCALL)
+// Also disable direct threading when tail calls are not supported at all (gcc < 15).
+#if defined(HAS_ADDRESS_SANITIZER) || !defined(HAS_TAILCALL)
```
Comment (R-Goc) [inline Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp]: Doesn't this disable direct threading for the sanitizer build even with tailcall support?

Comment (alimpfard) [reply Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp]: yeah that was silly, `!defined(HAS_TAILCALL)` is enough :sweat_smile:

Comment (rcorsi) [reply Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp]: Right, shouldn't it just be
`#if !defined(HAS_TAILCALL)`

Comment (rcorsi) [reply Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp]: And I guess the comment above can be expanded to cover a large wasm can also blow out the stack, for example with GNU 14 that doesn't support musttail.

Comment (rcorsi) [reply Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp]: What is the impact of this change, wasm will be slower, but stack won't get huge.

**Comment by rcorsi** [comment]
Looks good. Let me try it!

Those build issues in CI, I was getting them last night too. I don't think they are related to your change. Can you rerun the jobs that are failing, eventually they will pass.

**Comment by rcorsi** [comment]
```
$ readelf -p .comment ./Build/release/bin/Ladybird 

String dump of section '.comment':
  [     0]  GCC: (Ubuntu 14.2.0-19ubuntu2) 14.2.0
```

Just tested the site from #7009 and it works, no core dumping.

Also tested site from #7038 and it works

and same for #7032 

and same for #7025

Looks really good!

**Comment by rcorsi** [comment]
@alimpfard in the main description section, could you edit and add

fixes: #7009
fixes: #7038

So that they are auto-closed when you merge the PR.  I guess that is how it happens the auto closing, or does the person doing the merging have to do something extra?!?

For the other two issues, maybe the original posters might want some follow up on other issues uncovered, so maybe leave them out for now.

**Comment by alimpfard** [comment]
I'll add them to the PR description, works either way.
