### PR TITLE
LibWeb: Handle special cases of PseudoElement::Type correctly

### LINKED ISSUE #2904: Crash on Dashdot website
### Summary

When I launch any website, that is provided by [dashdot](https://github.com/MauriceNino/dashdot) it crashes, see e.g. [their](https://getdashdot.com/) [demo site](https://dash.mauz.dev/)

### Operating system

Linux

### Steps to reproduce

1. Open a dashdot website e.g. `https://dash.mauz.dev/` 
2. Wait a few seconds, or less
3. It crashes

### Expected behavior

The website should work

### Actual behavior

It crashes

### URL for a reduced test case

https://dash.mauz.dev/

### HTML/SVG/etc. source for a reduced test case

❌ 

### Log output and (if possible) backtrace

```shell
VERIFICATION FAILED: index < size() at ~/Code/ladybird/AK/Array.h:62
~/Code/ladybird/Build/release/lib/liblagom-ak.so.0(ak_trap+0x35) [0x71c3a5d6ae55]
~/Code/ladybird/Build/release/lib/liblagom-ak.so.0(+0x2a17f) [0x71c3a5d6b17f]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0(+0xb1fd42) [0x71c3a711fd42]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::CSS::ResolvedCSSStyleDeclaration::property(Web::CSS::PropertyID) const 0x42) [0x71c3a70695f2]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::CSS::CSSStyleDeclaration::get_property_value(AK::StringView) const 0x3b3) [0x71c3a6fb70f3]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::Bindings::GeneratedCSSStyleProperties::display() const 0x24) [0x71c3a75dbdf4]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::Bindings::CSSStyleDeclarationPrototype::display_regular_getter(JS::VM&) 0xfb) [0x71c3a7779b8b]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0(+0x3b32ab) [0x71c3a63b32ab]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::NativeFunction::internal_call(JS::Value, AK::Span<JS::Value const>) 0x1a7) [0x71c3a63b2ed7]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Object::internal_get(JS::PropertyKey const&, JS::Value, JS::CacheablePropertyMetadata*, JS::Object::PropertyLookupPhase) const 0x31e) [0x71c3a63bd88e]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Object::internal_get(JS::PropertyKey const&, JS::Value, JS::CacheablePropertyMetadata*, JS::Object::PropertyLookupPhase) const 0x205) [0x71c3a63bd775]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0(+0x215c09) [0x71c3a6215c09]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x1afc) [0x71c3a61f23dc]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_construct(AK::Span<JS::Value const>, JS::FunctionObject&) 0x336) [0x71c3a631b036]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0(+0x2176db) [0x71c3a62176db]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x316a) [0x71c3a61f3a4a]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::call_impl(JS::VM&, JS::Value, JS::Value, AK::Span<JS::Value const>) 0x58) [0x71c3a62a0ab8]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::BoundFunction::internal_call(JS::Value, AK::Span<JS::Value const>) 0x1d7) [0x71c3a62f56f7]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::call_impl(JS::VM&, JS::Value, JS::Value, AK::Span<JS::Value const>) 0x58) [0x71c3a62a0ab8]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::BoundFunction::internal_call(JS::Value, AK::Span<JS::Value const>) 0x1d7) [0x71c3a62f56f7]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_bytecode(unsigned long) 0x3798) [0x71c3a61f4078]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) 0x1cb) [0x71c3a61f05eb]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() 0x160) [0x71c3a631aaa0]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) 0x24d) [0x71c3a631a24d]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::WebIDL::invoke_callback(Web::WebIDL::CallbackType&, AK::Optional<JS::Value>, GC::MarkedVector<JS::Value, 0ul>) 0xd9) [0x71c3a7573b99]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 JS::Completion Web::WebIDL::invoke_callback<Web::DOM::Event*&>(Web::WebIDL::CallbackType&, AK::Optional<JS::Value>, Web::DOM::Event*&) 0x138) [0x71c3a7141ae8]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::DOM::EventTarget::process_event_handler_for_event(AK::FlyString const&, Web::DOM::Event&) 0x231) [0x71c3a71405b1]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0(+0xb40e4a) [0x71c3a7140e4a]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0(+0x3b32ab) [0x71c3a63b32ab]
~/Code/ladybird/Build/release/lib/liblagom-js.so.0 JS::NativeFunction::internal_call(JS::Value, AK::Span<JS::Value const>) 0x1a7) [0x71c3a63b2ed7]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::WebIDL::call_user_object_operation(Web::WebIDL::CallbackType&, AK::String const&, AK::Optional<JS::Value>, GC::MarkedVector<JS::Value, 0ul>) 0xf0) [0x71c3a7572f90]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 JS::Completion Web::WebIDL::call_user_object_operation<Web::DOM::Event*&>(Web::WebIDL::CallbackType&, AK::String const&, AK::Optional<JS::Value>, Web::DOM::Event*&) 0x136) [0x71c3a713e086]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::DOM::EventDispatcher::inner_invoke(Web::DOM::Event&, AK::Vector<GC::Root<Web::DOM::DOMEventListener>, 0ul>&, Web::DOM::Event::Phase, bool, bool&) 0x234) [0x71c3a713cf44]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::DOM::EventDispatcher::invoke(Web::DOM::Event::PathEntry&, Web::DOM::Event&, Web::DOM::Event::Phase, bool&) 0x1d9) [0x71c3a713d1f9]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::DOM::EventDispatcher::dispatch(GC::Ref<Web::DOM::EventTarget>, Web::DOM::Event&, bool, bool&) 0x9aa) [0x71c3a713dd6a]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::DOM::EventDispatcher::dispatch(GC::Ref<Web::DOM::EventTarget>, Web::DOM::Event&, bool) 0x1c) [0x71c3a713d39c]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::HTML::MessagePort::post_message_task_steps(Web::HTML::SerializedTransferRecord&) 0x31c) [0x71c3a72d5d2c]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0(+0x8d4f7f) [0x71c3a6ed4f7f]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0 Web::HTML::EventLoop::process() 0x51) [0x71c3a7230a01]
~/Code/ladybird/Build/release/lib/liblagom-web.so.0(+0x8d4f7f) [0x71c3a6ed4f7f]
~/Code/ladybird/Build/release/lib/liblagom-core.so.0(+0x2e11f) [0x71c3a65d911f]
~/Code/ladybird/Build/release/lib/liblagom-core.so.0 Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) 0x85) [0x71c3a65d83c5]
~/Code/ladybird/Build/release/lib/liblagom-webview.so.0(+0x106c1a) [0x71c3a83d4c1a]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x1ba5c4) [0x71c3a85ba5c4]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimer::timeout(QTimer::QPrivateSignal) 0x3d) [0x71c3a85bde7d]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QObject::event(QEvent*) 0x1b9) [0x71c3a85a3919]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QCoreApplication::notifyInternal2(QObject*, QEvent*) 0xee) [0x71c3a85666ee]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QTimerInfoList::activateTimers() 0x4e6) [0x71c3a86b53a6]
/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x374a81) [0x71c3a8774a81]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x5f397) [0x71c3a5110397]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xbfdc7) [0x71c3a5170dc7]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x71c3a510f8b3]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x73) [0x71c3a8773253]
/lib/x86_64-linux-gnu/libQt6Core.so.6 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) 0x2db) [0x71c3a8570b5b]
~/Code/ladybird/Build/release/lib/liblagom-core.so.0 Core::EventLoop::exec() 0x37) [0x71c3a65d63f7]
~/Code/ladybird/Build/release/libexec/WebContent(+0x8a0ec) [0x5ca869d990ec]
~/Code/ladybird/Build/release/libexec/WebContent(+0x14cd4f) [0x5ca869e5bd4f]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a3b8) [0x71c3a562a3b8]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x71c3a562a47b]
~/Code/ladybird/Build/release/libexec/WebContent(+0x88855) [0x5ca869d97855]
37868.339 Ladybird(2233855): WebContent process crashed! Last page loaded: https://dash.mauz.dev/
``
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [X] I’ll contribute a patch for this myself.

#### Note

This has to do with 'unknown -webkit- pseudo-elements'.

### PR DESCRIPTION
**Pull request by Totto16**
Their are some special values for CSS::Selector::PseudoElement::Type which are after `KnownPseudoElementCount` and therefore not present in various arrays of pseudo elements, this leads to some errors, if a type after `KnownPseudoElementCount` is used without checking first. This adds explicit checks to all usages

Possible related PR #1362

Fixes #2904 

## Note

[dashdot](https://github.com/MauriceNino/dashdot) uses react and [simplebar-react](https://www.npmjs.com/package/simplebar-react) which internally does some compatibility checks for 

```js
getComputedStyle(el, "::-webkit-scrollbar").display
```

(where `el` is any element)
and that crashes, as per #2904

### CODE REVIEW

File: Libraries/LibWeb/CSS/Selector.h [hunk 1]
```diff
@@ -68,7 +68,13 @@ class Selector : public RefCounted<Selector> {
...
         static Optional<PseudoElement> from_string(FlyString const&);
 
-        static StringView name(Selector::PseudoElement::Type pseudo_element);
+        [[nodiscard]] static bool is_known_pseudo_element_type(Type type)
+        {
+            return to_underlying(type) < to_underlying(CSS::Selector::PseudoElement::Type::KnownPseudoElementCount);
+        }
+
+        static StringView
+        name(Selector::PseudoElement::Type pseudo_element);
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/Selector.h:77]: You accidentally split this onto two lines, please remove that change.

File: Libraries/LibWeb/Animations/Animatable.cpp [hunk 2]
```diff
@@ -187,14 +187,14 @@ void Animatable::visit_edges(JS::Cell::Visitor& visitor)
 
 GC::Ptr<CSS::CSSStyleDeclaration const> Animatable::cached_animation_name_source(Optional<CSS::Selector::PseudoElement::Type> pseudo_element) const
 {
-    if (pseudo_element.has_value())
+    if (pseudo_element.has_value() && CSS::Selector::PseudoElement::is_known_pseudo_element_type(pseudo_element.value()))
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Animations/Animatable.cpp:190]: This change means that requesting the animation name source for a fake pseudo-elements will give you its element's one instead, which is wrong - it should give you nothing.

The same for the other places you've added this check. It's not correct to fall back to returning the element's data.

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
Please combine the first two commits: the second is a refactor of the first.

File: Libraries/LibWeb/Animations/Animatable.cpp (hunk 2 above)
Comment (Totto16) [reply Libraries/LibWeb/Animations/Animatable.cpp:190]: That makes sense, that is not as easy, as there arise a few question on how to do that in the best way:
- The setters `set_cached_animation_name_animation` and `set_cached_animation_name_source`  need to be checked too, as far as I understand, or am I wrong?
- the getters return a `GC::Ptr`, is it okay to return `{}` (alias empty Ptr alias "nullptr")

I did this in a separate commit, so that it can be seen, what the changes were, I'll squash it, when it's correct 😄

**Review by AtkinsSJ — COMMENTED** [review]
This is looking good now I think! That last commit just needs squashing like you said.

**Comment by Totto16** [comment]
I squashed it now 👍🏼

**Comment by Totto16** [comment]
> Something went wrong with the squash - the test gets added in the first commit now, and removed in the second.

Yes, I just noticed, I used the git GUI and messed up, fixed it in the terminal now, 😓 😂 

It should be correct now

**Review by AtkinsSJ — APPROVED** [review]
