### PR TITLE
LibWeb: Remove associated transitions when clearing transitions

### LINKED ISSUE #1481: Crash in CSS transitions when loading nextjs.org
To reproduce, open https://nextjs.org/

cc @AtkinsSJ @mattco98 

```
VERIFICATION FAILED: m_associated_transitions.contains(property_id) at /Users/kling/src/ladybird/Userland/Libraries/LibWeb/Animations/Animatable.cpp:147
0   liblagom-ak.0.0.0.dylib             0x00000001030c8838 ak_verification_failed + 216
1   liblagom-web.0.0.0.dylib            0x0000000104b05b90 Web::Animations::Animatable::clear_transitions() + 0
2   liblagom-web.0.0.0.dylib            0x0000000104c0236c Web::CSS::StyleComputer::start_needed_transitions(Web::CSS::StyleProperties const&, Web::CSS::StyleProperties&, Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>) const + 2756
3   liblagom-web.0.0.0.dylib            0x0000000104c0a168 Web::CSS::StyleComputer::compute_style_impl(Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>, Web::CSS::StyleComputer::ComputeStyleMode) const + 5340
4   liblagom-web.0.0.0.dylib            0x0000000104c08c48 Web::CSS::StyleComputer::compute_style(Web::DOM::Element&, AK::Optional<Web::CSS::Selector::PseudoElement::Type>) const + 76
5   liblagom-web.0.0.0.dylib            0x0000000104c794bc Web::DOM::Element::recompute_style() + 92
6   liblagom-web.0.0.0.dylib            0x0000000104c59b5c Web::DOM::update_style_recursively(Web::DOM::Node&, Web::CSS::StyleComputer&) + 80
```

### PR DESCRIPTION
**Pull request by ChaseKnowlden**
Fixes crash on https://nextjs.org

Fixes #1481

### CODE REVIEW

**Comment by rmg-x** [comment]
After #1442, auth0.com also broke but this change fixes it as well.

**Comment by Gingeh** [comment]
This PR has also fixed a crash on github

File: Userland/Libraries/LibWeb/Animations/Animatable.cpp [hunk 1]
```diff
@@ -152,6 +152,11 @@ void Animatable::clear_transitions()
 {
     m_transition_attribute_indices.clear();
     m_transition_attributes.clear();
+
+    for (auto& property_id : m_associated_transitions.keys()) {
+        if (m_associated_transitions.contains(property_id))
+            m_associated_transitions.remove(property_id);
+    }
```
Comment (tcl3) [inline Userland/Libraries/LibWeb/Animations/Animatable.cpp:159]: Could you do: `m_associated_transitions.clear()` here instead?

Comment (ChaseKnowlden) [reply Userland/Libraries/LibWeb/Animations/Animatable.cpp]: Changed to clear.

Comment (tcl3) [reply Userland/Libraries/LibWeb/Animations/Animatable.cpp]: Please squash your latest change into the previous commit rather than adding it as a separate commit. Thanks!

Comment (ADKaster) [reply Userland/Libraries/LibWeb/Animations/Animatable.cpp]: Your updated code does the following:

```
for each (key, value in transitions_map)
  if transitions_map has a value for key
      remove every key,value pair from transitions_map
```

Compare your code to the code used to clear the other HashMap data member associated with transitions. It needs an update :)

Also, please make sure to fix-up your commits after review, instead of pushing more commits to the PR. If you don't know how to do that, refer to this video, or ask on discord. https://www.youtube.com/watch?v=ElRzTuYln0M

Comment (ChaseKnowlden) [reply Userland/Libraries/LibWeb/Animations/Animatable.cpp]: Squashed the commits.

File: Userland/Libraries/LibWeb/Animations/Animatable.cpp [hunk 2]
```diff
@@ -150,8 +150,13 @@ void Animatable::remove_transition(CSS::PropertyID property_id)
...
 {
-    m_transition_attribute_indices.clear();
-    m_transition_attributes.clear();
+    for (auto& property_id : m_associated_transitions.keys()) {
+        if (m_associated_transitions.contains(property_id)) {
+            m_associated_transitions.clear();
+            m_transition_attribute_indices.clear();
+            m_transition_attributes.clear();
+        }
+    }
```
Comment (tcl3) [inline Userland/Libraries/LibWeb/Animations/Animatable.cpp:159]: There's no need to put the `clear()` invocation inside a for loop, it just needs to be called once:
```suggestion
    m_transition_attribute_indices.clear();
    m_transition_attributes.clear();
    m_associated_transitions.clear();
```
