### PR TITLE
LibRegex: Add support for regex modifiers

### LINKED ISSUE #4284: LibRegex: Some valid expressions throw Syntax Error
### Summary

Some valid regular expressions throw SyntaxError in Ladybird, for example:
`/\k<a>(?<a>x)/`
`/^[[0-9]\q{0|2|4|9\uFE0F\u20E3}]+$/v`
`/(?-s:(?s:^.$))/s`
`/(?i:(?i:))/`
`/(?-i:\b)/iu`
`/a.a|b.b|(?s:c.c)|d.d|e.e/`
 
Full set can be found here:
[https://gist.github.com/aplefull/d50c47fd615caa32e5ba575008f22e02](https://gist.github.com/aplefull/d50c47fd615caa32e5ba575008f22e02)

### Operating system

Linux

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
Minimal example:
<script>
    'x'.match(/\k<a>(?<a>x)/);
    '0'.match(/^[[0-9]\q{0|2|4|9\uFE0F\u20E3}]+$/v);
    'a'.match(/(?-s:(?s:^.$))/s);
    ''.match(/(?i:(?i:))/);
    '\u017f'.match(/(?-i:\b)/iu);
    ''.match(/a.a|b.b|(?s:c.c)|d.d|e.e/);
</script>

And for convenience, all expressions from the test set:
<script>
    "x".match(/\k<a>(?<a>x)/);
    "0".match(/^[[0-9]\q{0|2|4|9\uFE0F\u20E3}]+$/v);
    "9️⃣".match(/^[[0-9]\q{0|2|4|9\uFE0F\u20E3}]+$/v);
    "6️⃣".match(/^[[0-9]\q{0|2|4|9\uFE0F\u20E3}]+$/v);
    "🇧🇪".match(/^[[0-9]\q{0|2|4|9\uFE0F\u20E3}]+$/v);
    "☃".match(/^[[0-9]\q{0|2|4|9\uFE0F\u20E3}]+$/v);
    "a".match(/(?-s:(?s:^.$))/s);
    "3".match(/(?-s:(?s:^.$))/s);
    "π".match(/(?-s:(?s:^.$))/s);
    "‧".match(/(?-s:(?s:^.$))/s);
    "".match(/(?-s:(?s:^.$))/s);
    "".match(/(?-s:(?s:^.$))/s);
    "".match(/(?-s:(?s:^.$))/s);
    "᠎".match(/(?-s:(?s:^.$))/s);
    "".match(/(?-s:(?s:^.$))/s);
    "".match(/(?-s:(?s:^.$))/s);
    "".match(/(?-s:(?s:^.$))/s);
    "".match(/(?-s:(?s:^.$))/s);
    "�".match(/(?-s:(?s:^.$))/s);
    "�".match(/(?-s:(?s:^.$))/s);
    "a".match(/(?-s:(?s-:^.$))/s);
    "3".match(/(?-s:(?s-:^.$))/s);
    "π".match(/(?-s:(?s-:^.$))/s);
    "‧".match(/(?-s:(?s-:^.$))/s);
    "".match(/(?-s:(?s-:^.$))/s);
    "".match(/(?-s:(?s-:^.$))/s);
    "".match(/(?-s:(?s-:^.$))/s);
    "᠎".match(/(?-s:(?s-:^.$))/s);
    "".match(/(?-s:(?s-:^.$))/s);
    "".match(/(?-s:(?s-:^.$))/s);
    "".match(/(?-s:(?s-:^.$))/s);
    "".match(/(?-s:(?s-:^.$))/s);
    "�".match(/(?-s:(?s-:^.$))/s);
    "�".match(/(?-s:(?s-:^.$))/s);
    "".match(/(?i:(?i:))/);
    "".match(/(?s:(?s:))/);
    "".match(/(?m:(?m:))/);
    "".match(/(?i:(?i:))/);
    "".match(/(?s:(?s:))/);
    "".match(/(?m:(?m:))/);
    "nope".match(/(?i:)/i);
    "nope".match(/(?s:)/s);
    "nope".match(/(?m:)/m);
    "nope".match(/(?ims:)/ims);
    "nope".match(/(?i:)/i);
    "nope".match(/(?s:)/s);
    "nope".match(/(?m:)/m);
    "nope".match(/(?ims:)/ims);
    "A".match(/(?m:^(?-i:a)$)/i);
    "a".match(/(?m:^(?-i:a)$)/i);
    "A".match(/(?m:^(?-i:a)$)/i);
    "a".match(/(?m:^(?-i:a)$)/i);
    "AB".match(/(?i:aB)/i);
    "Ab".match(/(?i:aB)/i);
    "aB".match(/(?i:aB)/i);
    "ab".match(/(?i:aB)/i);
    "AB".match(/(?i:aB)/i);
    "Ab".match(/(?i:aB)/i);
    "aB".match(/(?i:aB)/i);
    "ab".match(/(?i:aB)/i);
    "ſ".match(/(?-i:\b)/iu);
    "K".match(/(?-i:\b)/iu);
    "AA".match(/(a)(?-i:\1)/i);
    "aA".match(/(a)(?-i:\1)/i);
    "Aa".match(/(a)(?-i:\1)/i);
    "aa".match(/(a)(?-i:\1)/i);
    "es".match(/(?-i:es$)/i);
    "eS".match(/(?-i:es$)/i);
    "esz".match(/(?-i:es$)/i);
    "eSz".match(/(?-i:es$)/i);
    "es".match(/(?-i:es$)/im);
    "eS".match(/(?-i:es$)/im);
    "esz".match(/(?-i:es$)/im);
    "eSz".match(/(?-i:es$)/im);
    "ess".match(/^(?-m:es$)/m);
    "es".match(/^(?-m:es$)/m);
    "ess".match(/^(?-m:es$)/m);
    "es".match(/^(?-m:es$)/m);
    "ees".match(/(?-m:^es)$/m);
    "es".match(/(?-m:^es)$/m);
    "ees".match(/(?-m:^es)$/m);
    "es".match(/(?-m:^es)$/m);
    "aa".match(/a.a|b.b|(?s:c.c)|d.d|e.e/);
    "bb".match(/a.a|b.b|(?s:c.c)|d.d|e.e/);
    "cc".match(/a.a|b.b|(?s:c.c)|d.d|e.e/);
    "dd".match(/a.a|b.b|(?s:c.c)|d.d|e.e/);
    "ee".match(/a.a|b.b|(?s:c.c)|d.d|e.e/);
    "aa".match(/(a.a)|(?:b.b)|(?s:c.c)|(?:d.d)|(e.e)/);
    "bb".match(/(a.a)|(?:b.b)|(?s:c.c)|(?:d.d)|(e.e)/);
    "cc".match(/(a.a)|(?:b.b)|(?s:c.c)|(?:d.d)|(e.e)/);
    "dd".match(/(a.a)|(?:b.b)|(?s:c.c)|(?:d.d)|(e.e)/);
    "ee".match(/(a.a)|(?:b.b)|(?s:c.c)|(?:d.d)|(e.e)/);
    "".match(/(?-i:)/i);
    "".match(/(?-is:)/is);
    "".match(/(?-im:)/im);
    "".match(/(?-s:)/s);
    "".match(/(?-si:)/is);
    "".match(/(?-sm:)/ms);
    "".match(/(?-m:)/m);
    "".match(/(?-mi:)/im);
    "".match(/(?-ms:)/ms);
    "".match(/(?-ims:)/ims);
    "".match(/(?-ism:)/ims);
    "".match(/(?-sim:)/ims);
    "".match(/(?-smi:)/ims);
    "".match(/(?-mis:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?-msi:)/ims);
    "".match(/(?i-:)/);
    "".match(/(?is-:)/);
    "".match(/(?im-:)/);
    "".match(/(?s-:)/);
    "".match(/(?si-:)/);
    "".match(/(?sm-:)/);
    "".match(/(?m-:)/);
    "".match(/(?mi-:)/);
    "".match(/(?ms-:)/);
    "".match(/(?ims-:)/);
    "".match(/(?ism-:)/);
    "".match(/(?sim-:)/);
    "".match(/(?smi-:)/);
    "".match(/(?mis-:)/);
    "".match(/(?msi-:)/);
</script>
```

### Log output and (if possible) backtrace

```shell
18768.915 WebContent(50346): Unhandled JavaScript exception: [SyntaxError] RegExp compile error: Error during parsing of regular expression:
    \k<a>(?<a>x)
         ^---- Name of capture group is invalid. (line: 2, column: 15)

18815.463 WebContent(50346): Unhandled JavaScript exception: [SyntaxError] RegExp compile error: Error during parsing of regular expression:
    ^[[0-9]\q{0|2|4|9\uFE0F\u20E3}]+$
           ^---- [ ] imbalance. (line: 3, column: 15)


18852.786 WebContent(50346): Unhandled JavaScript exception: [SyntaxError] RegExp compile error: Error during parsing of regular expression:
    (?-s:(?s:^.$))
      ^---- Content of capture group is invalid. (line: 4, column: 15)

18907.616 WebContent(50346): Unhandled JavaScript exception: [SyntaxError] RegExp compile error: Error during parsing of regular expression:
    (?i:(?i:))
      ^---- Content of capture group is invalid. (line: 5, column: 14)

18974.585 WebContent(50346): Unhandled JavaScript exception: [SyntaxError] RegExp compile error: Error during parsing of regular expression:
    (?-i:\b)
      ^---- Content of capture group is invalid. (line: 6, column: 20)

19050.056 WebContent(50346): Unhandled JavaScript exception: [SyntaxError] RegExp compile error: Error during parsing of regular expression:
    a.a|b.b|(?s:c.c)|d.d|e.e
              ^---- Content of capture group is invalid. (line: 7, column: 14)
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by aplefull**
This PR adds support for regex modifiers. The big three already support them, so we shouldn’t fall behind :)

Also finally fixes #4284.

We now pass 64/70 tests in [regexp-modifiers 262](https://ladybirdbrowser.github.io/libjs-website/test262/per-file/?path=test/built-ins/RegExp/regexp-modifiers). The remaining six still fail because we have issues with Unicode case-insensitive matching. I’m hoping to fix that in a different PR.

Summary:
+64 ✅    -64 ❌   

```
test/built-ins/RegExp/regexp-modifiers/add-dotAll-does-not-affect-alternatives-outside.js                       ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-dotAll-does-not-affect-dotAll-property.js                            ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-dotAll-does-not-affect-ignoreCase-flag.js                            ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-dotAll-does-not-affect-multiline-flag.js                             ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-dotAll.js                                                            ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-affects-backreferences.js                                 ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-affects-characterClasses.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-affects-characterEscapes.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-does-not-affect-alternatives-outside.js                   ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-does-not-affect-dotAll-flag.js                            ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-does-not-affect-ignoreCase-property.js                    ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-ignoreCase-does-not-affect-multiline-flag.js                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-ignoreCase.js                                                        ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-multiline-does-not-affect-alternatives-outside.js                    ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-multiline-does-not-affect-dotAll-flag.js                             ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-multiline-does-not-affect-ignoreCase-flag.js                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-multiline-does-not-affect-multiline-property.js                      ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-multiline.js                                                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/add-remove-modifiers.js                                                  ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/changing-dotAll-flag-does-not-affect-dotAll-modifier.js                  ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/changing-ignoreCase-flag-does-not-affect-ignoreCase-modifier.js          ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/changing-multiline-flag-does-not-affect-multiline-modifier.js            ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nested-add-remove-modifiers.js                                           ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-add-dotAll-within-remove-dotAll.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-add-ignoreCase-within-remove-ignoreCase.js                       ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-add-multiline-within-remove-multiline.js                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-dotAll-does-not-affect-alternatives-outside.js                   ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-ignoreCase-does-not-affect-alternatives-outside.js               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-multiline-does-not-affect-alternatives-outside.js                ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-remove-dotAll-within-add-dotAll.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-remove-ignoreCase-within-add-ignoreCase.js                       ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/nesting-remove-multiline-within-add-multiline.js                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-dotAll-does-not-affect-alternatives-outside.js                    ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-dotAll-does-not-affect-dotAll-property.js                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-dotAll-does-not-affect-ignoreCase-flag.js                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-dotAll-does-not-affect-multiline-flag.js                          ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-dotAll.js                                                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-backreferences.js                              ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-characterClasses.js                            ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-characterEscapes.js                            ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-slash-lower-b.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-slash-lower-p.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-slash-lower-w.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-slash-upper-b.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-slash-upper-p.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-affects-slash-upper-w.js                               ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-does-not-affect-alternatives-outside.js                ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-does-not-affect-dotAll-flag.js                         ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-does-not-affect-ignoreCase-property.js                 ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase-does-not-affect-multiline-flag.js                      ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-ignoreCase.js                                                     ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-multiline-does-not-affect-alternatives-outside.js                 ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-multiline-does-not-affect-dotAll-flag.js                          ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-multiline-does-not-affect-ignoreCase-flag.js                      ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-multiline-does-not-affect-multiline-property.js                   ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/remove-multiline.js                                                      ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/syntax/valid/add-and-remove-modifiers-can-have-empty-remove-modifiers.js ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/syntax/valid/add-and-remove-modifiers.js                                 ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/syntax/valid/add-modifiers-when-nested.js                                ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/syntax/valid/add-modifiers-when-not-set-as-flags.js                      ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/syntax/valid/add-modifiers-when-set-as-flags.js                          ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/syntax/valid/remove-modifiers-when-nested.js                             ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/syntax/valid/remove-modifiers-when-not-set-as-flags.js                   ❌ -> ✅
test/built-ins/RegExp/regexp-modifiers/syntax/valid/remove-modifiers-when-set-as-flags.js                       ❌ -> ✅ 
```

### CODE REVIEW

File: Libraries/LibRegex/RegexByteCode.cpp [hunk 1]
```diff
@@ -19,6 +19,11 @@ constexpr static u32 const ParagraphSeparator { 0x2029 };
 
 namespace regex {
 
+static ALWAYS_INLINE AllOptions get_effective_options(MatchInput const& input, MatchState const& state)
+{
+    return state.current_options.value_or(input.regex_options);
```
Comment (alimpfard) [inline Libraries/LibRegex/RegexByteCode.cpp]: 🤔 can we have `state.current_options` always present instead? this feels like it could make char matchers quite a bit slower as-is.

File: Libraries/LibRegex/RegexMatch.h [hunk 2]
```diff
@@ -424,9 +424,12 @@ struct MatchState {
     COWVector<u64> repetition_marks;
     Vector<u64, 64> checkpoints;
     Vector<i64> step_backs;
+    Vector<FlagsUnderlyingType> modifier_stack;
```
Comment (alimpfard) [inline Libraries/LibRegex/RegexMatch.h]: Please give this an inline capacity of 1, let's not hit malloc for nothing if someone puts an inline modifier in their regex :)

File: Libraries/LibRegex/RegexByteCode.cpp (hunk 1 above)
Comment (aplefull) [reply Libraries/LibRegex/RegexByteCode.cpp]: Yup, done!
