### PR TITLE
LibWeb: Layout standalone SVG document with specified dimensions

### LINKED ISSUE #2668: Width/height attributes not respected for standalone SVG documents
### Summary

When opening in Ladybird an SVG file with specified width/height attributes  ("standalone SVG"), the svg drawing fills the whole agent viewport and does not respect the width/height. 

Chrome and Firefox respect the dimension attributes.

### Operating system

Linux

### Steps to reproduce

1. Open this in Ladybird:
https://github.com/user-attachments/assets/1b93deda-e7d3-42d9-a38a-5a45edcbb88c
2. ... then in Firefox
3. ... then Chromium

### Expected behavior

Ladybird should respect the width/height attributes of the SVG container.

### Actual behavior

The image fills the agent viewport.

### URL for a reduced test case

https://github.com/user-attachments/assets/1b93deda-e7d3-42d9-a38a-5a45edcbb88c

### HTML/SVG/etc. source for a reduced test case

```html
<svg viewBox="0 0 32 64" width="128" height="256" xmlns="http://www.w3.org/2000/svg">
    <title>white diamond on blue</title>
    <rect x="0" y="0" width="32" height="64" fill="blue"/>
    <g fill="white">
        <path d="M16 0 L32 32 L16 64 L0 32 Z" />
    </g>
</svg>
```

### Log output and (if possible) backtrace

```shell
# dump in headless browser

Viewport <#document> at (0,0) content-size 800x600 [BFC] children: not-inline
  SVGSVGBox <svg> at (0,0) content-size 800x600 [SVG] children: inline
    TextNode <#text>
    TextNode <#text>
    SVGGeometryBox <rect> at (250,0) content-size 300x600 children: not-inline
    TextNode <#text>
    SVGGraphicsBox <g> at (250,0) content-size 300x600 children: inline
      TextNode <#text>
      SVGGeometryBox <path> at (250,0) content-size 300x600 children: not-inline
      TextNode <#text>
    TextNode <#text>

ViewportPaintable (Viewport<#document>) [0,0 800x600]
  SVGSVGPaintable (SVGSVGBox<svg>) [0,0 800x600]
    SVGPathPaintable (SVGGeometryBox<rect>) [250,0 300x600]
    SVGGraphicsPaintable (SVGGraphicsBox<g>) [250,0 300x600]
      SVGPathPaintable (SVGGeometryBox<path>) [250,0 300x600]
```

### Screenshots or screen recordings

image
image
image

### Build flags or config settings

_No response_

### Contribute a patch?

- [X] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by manuel-za**
Fixes #2668 

Before:  standalone SVG documents were stretched to fit the agent
viewport, ignoring specified width / height attributes.

After this: SVG documents with specified width/height attributes are
laid out respecting these attributes.

Regarding layout of standalone SVG documents, this brings Ladybird to:
- parity with Chromium (131.0.6778.85)
- almost parity with Firefox (129.0.2) -- difference not material

### CODE REVIEW

**Comment by shlyakpavel** [comment]
Does this duplicate https://github.com/LadybirdBrowser/ladybird/pull/2806?

**Comment by manuel-za** [comment]
> Does this duplicate #2672?

Replace rather than duplicate. Deleted #2672 after I made sure CI passes on this one.

**Comment by manuel-za** [comment]
@AtkinsSJ : this should address your requirements from the previous PR #2672 :
- unit tests come after the code change
- found a reliable way to detect running in the top formatting context

NOTE: Confirming we're in the top formatting context is still kinda hacky:

> the active document in the top-level browsing context was initially `about:blank`

It may be a good idea to come back for a cleanup/streamlining of SVG layout at some point:
- SVG dimension code is spread between `BlockFormattingContext` and `SVGFormattingContext`
- there doesn't seem to be any direct "nesting" of formatting context ... or I cannot find it

I decided for a simple change here, my first Ladybird PR :smile:  . Lots of stuff still to understand.

**Comment by manuel-za** [comment]
NOTE: Confirming we're in the top formatting context is still kinda hacky:

> the active document in the top-level browsing context was not initially `about:blank`

It may be a good idea to come back for a cleanup/streamlining of SVG layout at some point:
- SVG dimension code is spread between `BlockFormattingContext` and `SVGFormattingContext`
- there doesn't seem to be any direct "nesting" of formatting context (only top down) ... or I cannot find it
- opinion: ideally, a FormattingContext for an embedded element (e.g. img/svg) should be pointing back to the layout element in the higher-level context <-- this seems like a pretty involved change, with consequences

I decided for a simple change here, my first Ladybird PR :smile:  . Lots of stuff still to understand.

**Comment by circl-lastname** [comment]
> Replace rather than duplicate. Deleted #2672 after I made sure CI passes on this one. Reason: reviewer requested reordering of commits.

For the future: Reordering commits in place using git rebase, within the original PR, is standard practice here.

**Comment by manuel-za** [comment]
CI failed: LibWeb tests timed out for `Lagom (Linux, ubuntu-24.04, NO_FUZZ, Clang, true) / CI`
I checked the log, it had actually completed ok, but took longer than 30 min (seems like the timeout cutoff for CI).
Added a minor change in a comment to bump it + get it to run CI again. Hoping. :crossed_fingers:

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 1]
```diff
@@ -28,6 +28,8 @@
 #include <LibWeb/SVG/SVGSymbolElement.h>
 #include <LibWeb/SVG/SVGUseElement.h>
 
+#include <LibWeb/Layout/Viewport.h>
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp:31]: Please put this sorted with the others above. (No newline gap.)

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 2]
```diff
@@ -176,9 +178,33 @@ void SVGFormattingContext::run(AvailableSpace const& available_space)
     // NOTE: SVG doesn't have a "formatting context" in the spec, but this is the most
     //       obvious way to drive SVG layout in our engine at the moment.
 
+    bool is_standalone_svg_document = !this->context_box()               // the [context] box
+                                           .root()                       // ...of the [root] viewport
+                                           .document()                   // ...of the document
+                                           .page()                       // ...on the page
+                                           .top_level_browsing_context() // ...in the browser
+                                           .active_document()            // the active document (in the browser)
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp:186]: Question: Would just using the `document()` work? The active document might not be the one that this element is in. (And also raises the issue of it being nullptr.)

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 3]
```diff
@@ -176,9 +178,33 @@ void SVGFormattingContext::run(AvailableSpace const& available_space)
...
 
+    if (is_standalone_svg_document) {
+        // Overwrite the content width/height with the styled node width/height (from <svg width height ...>)
+
+        // NOTE: If a height had not been provided by the svg element, it was set to the height of the container
+        //       (see BlockFormattingContext::layout_viewport)
+        if (svg_box_state.node().computed_values().width().is_length())
+            svg_box_state.set_content_width(svg_box_state.node().computed_values().width().length().absolute_length_to_px());
+        if (svg_box_state.node().computed_values().height().is_length())
+            svg_box_state.set_content_height(svg_box_state.node().computed_values().height().length().absolute_length_to_px());
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp:205]: - The length might not be absolute, so you can't call `absolute_length_to_px()` but need to use one of the `to_px()` methods.
- In SVG 2, the length can also be a percentage. You don't have to handle that now, but please at least add a FIXME comment.

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 4]
```diff
@@ -176,9 +178,33 @@ void SVGFormattingContext::run(AvailableSpace const& available_space)
...
+                                           .document()                   // ...of the document
+                                           .page()                       // ...on the page
+                                           .top_level_browsing_context() // ...in the browser
+                                           .active_document()            // the active document (in the browser)
+                                           ->is_initial_about_blank();   // is it about:blank initially?
+    //  NOTE: Given that somehow we have already made it to an SVGFormattingContext:
+    //        The browser's active document [...] is initially about:blank can only mean that we are
+    //        laying out a fragment of another document.
+    //        Rephrase: we are not laying out a standalone SVG document.
+    //        Current browser behavior seems to guarantee initial about:blank for layout of SVG fragments.
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp]: Nit-pick: There's an extra space at the start of each line of this comment.

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 5]
```diff
@@ -185,10 +185,10 @@ void SVGFormattingContext::run(AvailableSpace const& available_space)
...
                                            ->is_initial_about_blank();   // is it about:blank initially?
-    //  NOTE: Given that somehow we have already made it to an SVGFormattingContext:
-    //        The browser's active document [...] is initially about:blank can only mean that we are
-    //        laying out a fragment of another document.
-    //        Rephrase: we are not laying out a standalone SVG document.
+    //  NOTE: Given that somehow we have already made it to an SVGFormattingContext
+    //        The fact that the browser's active document [...] was initially about:blank can only mean
+    //        that we are laying out an SVG fragment of another document.
+    //        Rephrase: "We are not laying out a standalone SVG document"
     //        Current browser behavior seems to guarantee initial about:blank for layout of SVG fragments.
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp:192]: This change should be in the earlier commit that added the comment.

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp (hunk 2 above)
Comment (manuel-za) [reply Libraries/LibWeb/Layout/SVGFormattingContext.cpp:186]: > Question: Would just using the document() work?

Short answer: No. In case we're laying out a containing document with an svg fragment:
- `...document()` is the document of the svg fragment -- >`svg`
- `...top_level...active_document()` is the containing document -- >`html`

After "-->" above, I show `document_element()->local_name()` for `svg-as-image-implicit-viewbox.html` layout test input.

Comment (manuel-za) [reply Libraries/LibWeb/Layout/SVGFormattingContext.cpp:186]: > (And also raises the issue of it being nullptr.)

Good point. Guarding.

Comment (manuel-za) [reply Libraries/LibWeb/Layout/SVGFormattingContext.cpp:186]: > The active document might not be the one that this element is in.

Wow! I had not thought of this. The user may load a document (doc1) then immediately switch to a tab with another document (doc2), possibly `about:blank`.  In this case, doc1 may be rendered incorrectly.

Opinion:
- I could not find another way to determine we're in a nested `FormattingContext`.
- `SVGFormattingContext` may be due some love at some point (see my comment above)

Will add a FIXME describing the issue + let you decide whether:
- we should park this PR until streamlining `FormattingContext`
- or you know a way to find whether we're running in a nested context

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp (hunk 1 above)
Comment (ADKaster) [reply Libraries/LibWeb/Layout/SVGFormattingContext.cpp]: In the first commit, this include is still out of order. The change to sort the include should be fixup-squashed into the commit that introduced the include.

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 6]
```diff
@@ -185,11 +184,11 @@ void SVGFormattingContext::run(AvailableSpace const& available_space)
                                            .top_level_browsing_context() // ...in the browser
                                            .active_document()            // the active document (in the browser)
                                            ->is_initial_about_blank();   // is it about:blank initially?
-    //  NOTE: Given that somehow we have already made it to an SVGFormattingContext:
```
Comment (ADKaster) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp]: ` LibWeb: Correct formatting issues`

should be fixup'd into the first commit.

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 7]
```diff
@@ -177,13 +177,15 @@ void SVGFormattingContext::run(AvailableSpace const& available_space)
     // NOTE: SVG doesn't have a "formatting context" in the spec, but this is the most
     //       obvious way to drive SVG layout in our engine at the moment.
 
-    bool is_standalone_svg_document = !this->context_box()               // the [context] box
```
Comment (ADKaster) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp]: Same with `LibWeb: Protect against nullptr for active_document() `

Fixup into the first commit.

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 8]
```diff
@@ -191,6 +191,10 @@ void SVGFormattingContext::run(AvailableSpace const& available_space)
     //       that we are laying out an SVG fragment of another document.
     //       Rephrase: "We are not laying out a standalone SVG document"
     //       Current browser behavior seems to guarantee initial about:blank for layout of SVG fragments.
+    // FIXME: Find another way to determine whether we're laying out a standalone SVG document.
```
Comment (ADKaster) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp:194]: same with this fixme, squash into the first commit.

**Review by ADKaster — CHANGES_REQUESTED** [review]
Thanks for taking the time to work through the comments from Sam. As I think someone mentioned on discord, the follow-up commits you made should be fixup-squashed into the first commit.

While some projects prefer to keep follow-up commits distinct to allow for diff-based reviewing, generally reviewers for our project will go back and review the PR commit by commit. Since we're doing a rebase-based workflow where each commit from the PR is cherry-picked directly onto master, having each commit be its own atomic and complete patch is important for things like bisecting regressions.

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp (hunk 8 above)
Comment (manuel-za) [reply Libraries/LibWeb/Layout/SVGFormattingContext.cpp:194]: Noted. Squashed.

**Review by ADKaster — APPROVED** [review]

File: Libraries/LibWeb/Layout/SVGFormattingContext.cpp [hunk 9]
```diff
@@ -176,9 +177,40 @@ void SVGFormattingContext::run(AvailableSpace const& available_space)
...
 
+    auto const& active_document = this->context_box()               // the [context] box
+                                      .root()                       // ...of the [root] viewport
+                                      .document()                   // ...of the document
+                                      .page()                       // ...on the page
+                                      .top_level_browsing_context() // ...in the browser
+                                      .active_document();           // the active document (in the browser)
+
+    bool is_standalone_svg_document = (active_document != nullptr)
+        && !active_document->is_initial_about_blank();
```
Comment (awesomekling) [inline Libraries/LibWeb/Layout/SVGFormattingContext.cpp:188]: Instead of this mysterious heuristic, how about we just add a flag to `Document`, something like `is_standalone_svg_document()`? :)

Comment (manuel-za) [reply Libraries/LibWeb/Layout/SVGFormattingContext.cpp:188]: Sound.
Need to dig into the document creation code (DOM)... :eyes:

Comment (manuel-za) [reply Libraries/LibWeb/Layout/SVGFormattingContext.cpp]: Sound. Done.
Haha! Non only is it a good idea, `is_decoded_svg()` was already there! :smiley:
Good learning... I hope ...Applause!!...

**Review by AtkinsSJ — APPROVED** [review]
