### PR TITLE
LibWeb: Fix handling of SSEs split across chunks

### LINKED ISSUE #950: Long Server-Sent Events truncated
Sample server (Node.js):
```js
const http = require("http");

http.createServer((req, res) => {
	if(req.url === "/socket") {
		res.writeHead(200, {"Content-Type": "text/event-stream"});
		res.write("data: test\n\n");
		res.write("data: " + "0123456789".repeat(1000) + "\n\n");
		res.write("data: " + "0123456789".repeat(5000) + "\n\n");
		res.write("data: " + "0123456789".repeat(5250) + "\n\n");
		res.write("data: " + "0123456789".repeat(5500) + "\n\n");
		res.write("data: " + "0123456789".repeat(6000) + "\n\n");
		res.write("data: " + "0123456789".repeat(10000) + "\n\n");
	}
	else {
		res.writeHead(200, {"Content-Type": "text/html"});
		res.write(PAGE);
		res.end();
	}
}).listen(4444);

const PAGE = `
<!DOCTYPE html>
<html>
	<body>
		<h1>SSE test</h1>
		<pre id="container">
		</pre>
		<script>
			console.log("hi");

			const container = document.getElementById("container");

			const src = new EventSource("/socket");
			src.onmessage = evt => {
				console.log(evt);

				container.appendChild(document.createTextNode(evt.data.length + "\\n"));
			};
		</script>
	</body>
</html>
`;
```

Expected output:
```
		4
10000
50000
52500
55000
60000
100000
```

Output in Ladybird:
```
		4
10000
21457
36977
17229
60000
500
```
(or something similar, the actual numbers seem a bit random)

### PR DESCRIPTION
**Pull request by vpzomtrrfrt**
Should fix #950

### CODE REVIEW

**Comment by kennethmyhra** [comment]
Can we add a test for this. Also a bit more explicit in the commit description about what this actually fixes would be nice

File: Userland/Libraries/LibWeb/HTML/EventSource.cpp [hunk 1]
```diff
@@ -130,8 +130,37 @@ WebIDL::ExceptionOr<JS::NonnullGCPtr<EventSource>> EventSource::construct_impl(J
...
+                    }
+
+                    remainder = body_str.substring_view(end);
+                } else {
+                    remainder = body_str;
+                }
+
+                if (!remainder.is_empty()) {
+                    MUST(pending_line.try_append(remainder));
+                }
```
Comment (trflynn89) [inline Userland/Libraries/LibWeb/HTML/EventSource.cpp:163]: This all feels like a very verbose solution. Is the bug just that `interpret_response` will process the last line even if it does not end with a newline? If so, can we just not process that last line in `interpret_response` and hold onto the remainder there, until we receive the next chunk?

**Comment by trflynn89** [comment]
> Can we add a test for this

We unfortunately do not have the infrastructure to test SSE in our unit tests. They require running an HTTP server in the background.

File: Userland/Libraries/LibWeb/HTML/EventSource.cpp (hunk 1 above)
Comment (vpzomtrrfrt) [reply Userland/Libraries/LibWeb/HTML/EventSource.cpp:163]: I agree that it's verbose, but the reason I have it out here is that it's only relevant to the current connection. Keeping the leftovers in an instance member would require an extra step to clear it when reconnecting

Comment (vpzomtrrfrt) [reply Userland/Libraries/LibWeb/HTML/EventSource.cpp:163]: also, from my reading of `for_each_line`, it wouldn't do anything different for strings ending with newlines, so that needs to be checked outside anyway

Comment (trflynn89) [reply Userland/Libraries/LibWeb/HTML/EventSource.cpp:163]: Sorry for the delay in getting back to this, had a busy week last week.

Keeping it local to the connection callback is fine, but I'd like to massage the code a bit still. Does the following work for your test case?
```diff
diff --git a/Userland/Libraries/LibWeb/HTML/EventSource.cpp b/Userland/Libraries/LibWeb/HTML/EventSource.cpp
index a0fa53edde..7f23a267bf 100644
--- a/Userland/Libraries/LibWeb/HTML/EventSource.cpp
+++ b/Userland/Libraries/LibWeb/HTML/EventSource.cpp
@@ -130,9 +130,22 @@ WebIDL::ExceptionOr<JS::NonnullGCPtr<EventSource>> EventSource::construct_impl(J
         else {
             event_source->announce_the_connection();

-            auto process_body_chunk = JS::create_heap_function(realm.heap(), [event_source](ByteBuffer body) {
-                event_source->interpret_response(body);
+            auto process_body_chunk = JS::create_heap_function(realm.heap(), [event_source, pending_data = ByteBuffer()](ByteBuffer body) mutable {
+                if (pending_data.is_empty())
+                    pending_data = move(body);
+                else
+                    pending_data.append(body);
+
+                auto last_line_break = AK::StringUtils::find_any_of(pending_data, "\r\n"sv, AK::StringUtils::SearchDirection::Backward);
+                if (!last_line_break.has_value())
+                    return;
+
+                auto end_index = *last_line_break + 1;
+                event_source->interpret_response({ pending_data.bytes().slice(0, end_index) });
+
+                pending_data = MUST(pending_data.slice(end_index, pending_data.size() - end_index));
             });
+
             auto process_end_of_body = JS::create_heap_function(realm.heap(), []() {
                 // This case is handled by `process_event_source_end_of_body` above.
             });
```

Comment (vpzomtrrfrt) [reply Userland/Libraries/LibWeb/HTML/EventSource.cpp:163]: Seems to (actually, with both versions I occasionally see it still fail, but it's significantly more reliable than before)

Should I take this code or do you want to open a new PR?

Comment (trflynn89) [reply Userland/Libraries/LibWeb/HTML/EventSource.cpp:163]: > with both versions I occasionally see it still fail

Same here, but I'm not sure that it's an issue with the EventSource class itself - it's likely something going on with the unbuffered request handler in Fetch or our Streams implementation that passes the data up to EventSource. I've also been looking into an issue where navigating away from a page doesn't close the SSE connection.

> Should I take this code or do you want to open a new PR?

Nah, feel free to take it

Comment (vpzomtrrfrt) [reply Userland/Libraries/LibWeb/HTML/EventSource.cpp]: Replaced code as suggested

**Review by trflynn89 — APPROVED** [review]
