### PR TITLE
LibWeb: Use dimension image source for images

### LINKED ISSUE #7829: MediaWiki/Wikimedia logos at the bottom of Wikipedia pages are rendered tiny
### Summary

Scroll to the bottom of any Wikipedia page and you'll see the logos at the bottom right rendered much smaller than you'd expect them to be.

### Operating system

Linux

### Steps to reproduce

1. Go to Wikipedia
2. Scroll to the bottom
3. Look to the right

### Expected behavior

Like in other browsers, the containers for those images would be rectangles accommodating the items at a readable scale.

### Actual behavior

They instead are shrunk down to fit in square containers of the same height.

### URL for a reduced test case

https://en.wikipedia.org/wiki/One_pound_coin

### HTML/SVG/etc. source for a reduced test case

```html
any page will work but idk how to reduce this
```

### Log output and (if possible) backtrace

```shell
ninja: Entering directory `/home/conputer/other-dev/ladybird/20250807210822/ladybird/Build/release'
ninja: no work to do.
9334.688 WebContent(57078): Handling message while connection closed: WebContentServer::CloseServer
9335.233 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.234 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.235 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.235 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.236 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.237 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.238 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.238 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9335.986 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.986 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.986 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.986 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.986 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.986 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9335.987 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9336.026 WebContent(57089): (js warn) "The stream mediawiki.client.session_tick is out of sample. No event will be sent"
9336.145 WebContent(57089): (js warn) "The stream mediawiki.web_ui_actions is out of sample. No event will be sent"
9336.221 WebContent(57089): HTMLScriptElement: Refusing to run script because it has already started.
9336.221 WebContent(57089): HTMLScriptElement: Refusing to run script because it has already started.
9341.482 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9341.482 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9341.486 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9341.487 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9341.488 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9341.488 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9341.488 WebContent(57089): FIXME: HTMLImageElement.decoding = 'async' is not implemented yet
9342.305 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.305 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.305 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.305 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.305 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.305 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.306 WebContent(57089): FIXME: Implement HTMLElement::access_key_label()
9342.662 WebContent(57089): (js warn) "The stream mediawiki.web_ui_actions is out of sample. No event will be sent"
9350.256 WebContent(57089): (js warn) "The stream mediawiki.web_ui_actions is out of sample. No event will be sent"
9355.612 WebContent(57089): (js warn) "The stream mediawiki.web_ui_actions is out of sample. No event will be sent"
9402.428 WebContent(57089): (js warn) "The stream mediawiki.client.session_tick is out of sample. No event will be sent"
9462.430 WebContent(57089): (js warn) "The stream mediawiki.client.session_tick is out of sample. No event will be sent"
```

### Screenshots or screen recordings

Image

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by ChaseKnowlden**
Fixes tiny images on Wikipedia
Closes #7829

### CODE REVIEW

File: Libraries/LibWeb/HTML/HTMLImageElement.cpp [hunk 1]
```diff
@@ -102,9 +102,26 @@ void HTMLImageElement::visit_edges(Cell::Visitor& visitor)
     visitor.visit(m_current_request);
     visitor.visit(m_pending_request);
     visitor.visit(m_document_observer);
+    visitor.visit(m_dimension_attribute_source);
     visit_lazy_loading_element(visitor);
 }
 
+// https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element:dimension-attribute-source
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/HTML/HTMLImageElement.cpp]: This URL doesn't seem to link to anything. Maybe you meant https://html.spec.whatwg.org/multipage/embedded-content.html#concept-img-dimension-attribute-source ? Not sure how that happened but they do move definitions around sometimes.

File: Libraries/LibWeb/HTML/HTMLImageElement.cpp [hunk 2]
```diff
@@ -1178,10 +1195,13 @@ static void update_the_source_set(DOM::Element& element)
     VERIFY(is<HTMLImageElement>(element) || is<HTMLLinkElement>(element));
 
     // 1. Set el's source set to an empty source set.
-    if (auto* image_element = as_if<HTMLImageElement>(element))
+    if (auto* image_element = as_if<HTMLImageElement>(element)) {
         image_element->set_source_set(SourceSet {});
-    else if (is<HTMLLinkElement>(element))
+        // Reset the dimension attribute source to the img element itself.
+        image_element->set_dimension_attribute_source(nullptr);
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/HTML/HTMLImageElement.cpp]: This doesn't appear in the spec, is it required? If so, can you raise a [spec issue](https://github.com/whatwg/html/issues) about it and link it here?

File: Libraries/LibWeb/HTML/HTMLImageElement.cpp [hunk 3]
```diff
@@ -1298,8 +1318,14 @@ static void update_the_source_set(DOM::Element& element)
             // FIXME: Implement this step for link elements
         }
 
-        // FIXME: 9. If child has width or height attributes, set el's dimension attribute source to child.
-        //           Otherwise, set el's dimension attribute source to el.
+        // 9. If child has width or height attributes, set el's dimension attribute source to child.
+        //    Otherwise, set el's dimension attribute source to el.
+        if (auto* image_element = as_if<HTMLImageElement>(element)) {
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/HTML/HTMLImageElement.cpp]: From the spec note on step 5.1.11, `el` should always be an img element at this point. (The same is true for the check in step 8, and the FIXME below that.)

File: Libraries/LibWeb/HTML/HTMLImageElement.cpp (hunk 2 above)
Comment (ChaseKnowlden) [reply Libraries/LibWeb/HTML/HTMLImageElement.cpp]: Not required

File: Libraries/LibWeb/HTML/HTMLImageElement.cpp (hunk 3 above)
Comment (ChaseKnowlden) [reply Libraries/LibWeb/HTML/HTMLImageElement.cpp]: Fixed

File: Libraries/LibWeb/HTML/HTMLImageElement.cpp (hunk 1 above)
Comment (ChaseKnowlden) [reply Libraries/LibWeb/HTML/HTMLImageElement.cpp]: Updated the URL
