### PR TITLE
LibWeb: Don't assume calc() simplification worked on invalid tree

### LINKED ISSUE #4469: Regression in parsing of invalid min/max functions
The following WPTs crash after #4458:
* https://wpt.live/css/css-values/minmax-time-invalid.html
* https://wpt.live/css/css-values/minmax-length-invalid.html

Reduction
```html
<!DOCTYPE html>
<style>
    div {
        transition-delay: min(1s, 0%)
    }
</style>
<div></div>
```

Stack trace:
```
#0  ak_trap () at /home/tim/repos/ladybird/AK/Assertions.cpp:113
#1  0x000078aca16fb23f in ak_verification_failed () at /home/tim/repos/ladybird/AK/Assertions.cpp:123
#2  0x000078aca327115a in release_nonnull () at /home/tim/repos/ladybird/AK/RefPtr.h:236
#3  simplify_a_calculation_tree () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp:2930
#4  0x000078aca322319a in parse_a_calc_function_node () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/Parser/ValueParsing.cpp:3521
#5  0x000078aca320fa20 in parse_calculated_value () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/Parser/ValueParsing.cpp:3500
#6  0x000078aca320d0cb in parse_time_value () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/Parser/ValueParsing.cpp:995
#7  0x000078aca31e4f49 in parse_list_of_time_values () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp:3801
#8  0x000078aca31c6b0b in parse_css_value () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp:674
#9  0x000078aca31b1752 in parse_as_css_value () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/Parser/Parser.cpp:1659
#10 0x000078aca31a6bec in parse_css_value () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/Parser/Helpers.cpp:78
#11 0x000078aca31563b1 in set_property () at /home/tim/repos/ladybird/Libraries/LibWeb/CSS/CSSStyleProperties.cpp:233
#12 0x000078aca382ebfc in Web::Bindings::GeneratedCSSStyleProperties::set_transition_delay(AK::StringView) ()
    at /home/tim/repos/ladybird/Build/release/Lagom/Libraries/LibWeb/CSS/GeneratedCSSStyleProperties.cpp:3060
#13 0x000078aca3a9c921 in operator() () at /home/tim/repos/ladybird/Build/release/Lagom/Libraries/LibWeb/Bindings/CSSStylePropertiesPrototype.cpp:33750
#14 throw_dom_exception_if_needed<(lambda at /home/tim/repos/ladybird/Build/release/Lagom/Libraries/LibWeb/Bindings/CSSStylePropertiesPrototype.cpp:33750:62), Web::WebIDL::ExceptionOr<void>, JS::Value> () at /home/tim/repos/ladybird/Libraries/LibWeb/Bindings/ExceptionOrUtils.h:97
#15 transition_delay_dashed_setter () at /home/tim/repos/ladybird/Build/release/Lagom/Libraries/LibWeb/Bindings/CSSStylePropertiesPrototype.cpp:33750
```

CC: @awesomekling

### PR DESCRIPTION
**Pull request by awesomekling**
Fixes #4469

### CODE REVIEW

File: Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp [hunk 1]
```diff
@@ -2927,7 +2927,9 @@ NonnullRefPtr<CalculationNode const> simplify_a_calculation_tree(CalculationNode
     if (root->is_math_function_node()) {
         if (auto maybe_simplified = root->run_operation_if_possible(context, resolution_context); maybe_simplified.has_value()) {
             // NOTE: If this returns nullptr, that's a logic error in the code, so it's fine to assert that it's nonnull.
-            return make_calculation_node(maybe_simplified.release_value(), context).release_nonnull();
```
Comment (tcl3) [inline Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp:2930]: It seems like the comment above isn't valid anymore.

Comment (awesomekling) [reply Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp:2930]: Touché!

**Review by AtkinsSJ — APPROVED** [review]
