### PR TITLE
LibWeb: Create an execution context before registering import map

### LINKED ISSUE #6297: crash when raising exception when importmap is malformed
### Summary

When an importmap is malformed, Ladybird crashes, seemingly when trying to raise the appropriate exception

### Operating system

macOS

### Steps to reproduce

1. Load the test case below
2. Observe crash; I am on ba2926f8b3121e428a681451d88d77ea95be16bc

### Expected behavior

No crash

### Actual behavior

Crash every time

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
<html>
<head>
	<script type="importmap">
		0
	</script>
</head>
</html>
```

### Log output and (if possible) backtrace

```shell
VERIFICATION FAILED: !m_execution_context_stack.is_empty() at /Users/dp/ws/ladybird/Libraries/LibJS/Runtime/VM.h:145
0   liblagom-ak.0.0.0.dylib             0x0000000100d6d698 dump_backtrace + 72
1   liblagom-ak.0.0.0.dylib             0x0000000100d6d950 ak_trap + 12
2   liblagom-ak.0.0.0.dylib             0x0000000100d6d9fc ak_assertion_failed + 0
3   liblagom-web.0.0.0.dylib            0x00000001050b4468 AK::Detail::StringData::bytes() const (.cold.1) + 0
4   liblagom-web.0.0.0.dylib            0x0000000103f710f0 JS::Completion Web::Bindings::exception_to_throw_completion<AK::Variant<Web::WebIDL::SimpleException, GC::Ref<Web::WebIDL::DOMException>, JS::Completion>&>(JS::VM&, AK::Variant<Web::WebIDL::SimpleException, GC::Ref<Web::WebIDL::DOMException>, JS::Completion>&)::'lambda'(Web::WebIDL::SimpleException const&)::operator()(Web::WebIDL::SimpleException const&) const + 376
5   liblagom-web.0.0.0.dylib            0x000000010444c5a0 Web::HTML::ImportMapParseResult::register_import_map(Web::HTML::Window&) + 120
6   liblagom-web.0.0.0.dylib            0x00000001043bd510 Web::HTML::HTMLScriptElement::execute_script() + 820
7   liblagom-web.0.0.0.dylib            0x00000001043be5ac Web::HTML::HTMLScriptElement::prepare_script() + 4208
8   liblagom-web.0.0.0.dylib            0x0000000104418090 Web::HTML::HTMLParser::handle_text(Web::HTML::HTMLToken&) + 748
9   liblagom-web.0.0.0.dylib            0x000000010441255c Web::HTML::HTMLParser::run(Web::HTML::HTMLTokenizer::StopAtInsertionPoint) + 704
10  liblagom-web.0.0.0.dylib            0x0000000104413708 Web::HTML::HTMLParser::run(URL::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) + 144
11  liblagom-web.0.0.0.dylib            0x000000010420421c AK::Function<void ()>::CallableWrapper<Web::load_html_document(Web::HTML::NavigationParams const&)::$_0::operator()(AK::Detail::ByteBuffer<32ul>) const::'lambda'()>::call() + 128
12  liblagom-web.0.0.0.dylib            0x00000001045a91c8 AK::Function<void ()>::CallableWrapper<Web::Platform::EventLoopPluginSerenity::deferred_invoke(GC::Root<GC::Function<void ()>>)::$_0>::call() + 108
13  liblagom-core.0.0.0.dylib           0x00000001006853ec Core::ThreadEventQueue::process() + 508
14  liblagom-core.0.0.0.dylib           0x0000000100689e38 Core::EventLoopImplementationUnix::exec() + 44
15  liblagom-core.0.0.0.dylib           0x0000000100677784 Core::EventLoop::exec() + 68
16  WebContent                          0x00000001000c4f4c ladybird_main(Main::Arguments) + 4284
17  WebContent                          0x000000010016889c main + 184
18  dyld                                0x00000001838eeb98 start + 6076
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by danielbprice**
Fixes #6297

------

Note to reviewer: I just want to say that (a) I am new in this code base and (b) I found this fix more-or-less by trial and error.  I don't have a deep understanding of why this is fixing the issue, or if this is the best form for this fix.  It seems like an awkward fix to me.  I would be happy to iterate on it given some guidance.  I am not sure the tests are executing properly.

With this fix in place, loading the HTML in the bug report produces:

```
4405501.614 WebContent(13493): Unhandled JavaScript exception: [TypeError] The top-level value of an importmap needs to be a JSON object.
4405501.614 WebContent(13493):
```

And no extraneous output or crash.

### CODE REVIEW

File: Libraries/LibWeb/HTML/HTMLScriptElement.cpp [hunk 1]
```diff
@@ -487,6 +488,7 @@ void HTMLScriptElement::prepare_script()
         // -> "importmap"
         else if (m_script_type == ScriptType::ImportMap) {
             // 1. Let result be the result of creating an import map parse result given source text and base URL.
+            prepare_to_run_script(realm());
```
Comment (tcl3) [inline Libraries/LibWeb/HTML/HTMLScriptElement.cpp]: Elsewhere, `HTML::TemporaryExecutionContext` is used when a similar pattern to this is needed.

Does adding `HTML::TemporaryExecutionContext execution_context { global.realm() };` before the call to  `exception_to_throw_completion()` in `ImportMapParseResult::register_import_map()` work?

Comment (danielbprice) [reply Libraries/LibWeb/HTML/HTMLScriptElement.cpp]: Yes, that works perfectly.  Thanks so much.  I had experimented with `HTML::TemporaryExecutionContext` but evidently in the wrong location.  Updated review.

File: Libraries/LibWeb/HTML/HTMLScriptElement.cpp [hunk 2]
```diff
@@ -20,6 +20,7 @@
 #include <LibWeb/HTML/Scripting/ClassicScript.h>
```
Comment (trflynn89) [inline Libraries/LibWeb/HTML/HTMLScriptElement.cpp:20]: Regarding the commit message title: Per [CONTRIBUTING.md](https://github.com/LadybirdBrowser/ladybird/blob/master/CONTRIBUTING.md#code-submission-policy), please write the title in the imperative mood. That would mean something like:
`LibWeb: Create an execution context before registering import maps`

Comment (danielbprice) [reply Libraries/LibWeb/HTML/HTMLScriptElement.cpp:20]: Apologies.  Fixed!
