### PR TITLE
LibWeb: dont inject natural sizes from prepare_for_replaced_layout

### LINKED ISSUE #634: Input element not stretched inside flex container

### LINKED ISSUE #6040: <textarea> does not fill flex parent in cross-axis
demo page:
```html
<style>
  body {
    height: 100%;
    display: flex;
  }
</style>

<textarea style="width: 50%; background-color: red;"></textarea>
<div style="width: 50%; background-color: green;"></div>
```

screenshot:
Image

<sub>issue created with ladybird :3</sub>

### LINKED ISSUE #7070: Grid layout does not respect min-height on textarea children
### Summary

This:
```html
<div style="display: grid">
    <textarea style="min-height: 500px"></textarea>
    This text is rendered over top of the textarea.
</div>
```

### Operating system

Linux

### Steps to reproduce

Look at the given HTML example in Ladybird and compare to any other browser.

### Expected behavior

The textarea should take up as much vertical space as it is tall.

### Actual behavior

The text area takes up about one line, additional content is placed over top of it.

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
<div style="display: grid">
    <textarea style="min-height: 500px"></textarea>
    This text is rendered over top of the textarea.
</div>
```

### Log output and (if possible) backtrace

```shell
none
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by jonbgamble**
Instead, compute them in accessors.

Add TextAreaBox and TextInputBox to Layout so that textarea and text inputs can be stretched when auto.

Fix #634, fix #6040, fix #7070, and possibly related issues involving baseline, cross axis sizing, aspect ratio, canvas, size containment, and textarea

### CODE REVIEW

**Comment by Gingeh** [comment]
I can't comment on the implementation itself, but this patch fixes the page I opened #6040 for

**Comment by gmta** [comment]
Hi! Please check our [contribution guidelines](<https://github.com/LadybirdBrowser/ladybird/blob/master/CONTRIBUTING.md#code-submission-policy>), and particularly:

> Split your changes into separate, atomic commits (i.e. A commit per feature or fix, where the build, tests and the system are all functioning).

Basically, whenever your commit message starts to describe more than one thing, it's very likely that we'd like to see separate commits. You should split them up to discern between non-functional changes involving code cleanup, refactors to prepare for changes, bugfixes and functional changes.

**Comment by jonbgamble** [comment]
I will say this about your commit message linter - I have had more enjoyable interactions with the rust borrow checker.

**Comment by gmta** [comment]
@jonbgamble 

> I will say this about your commit message linter - I have had more enjoyable interactions with the rust borrow checker.

Did you use [pre-commit](<https://github.com/LadybirdBrowser/ladybird/blob/4249b14907ed5ecc6842bfef6d5477232195fe5f/CONTRIBUTING.md?plain=1#L133-L144>) locally to lint your commits before pushing?

If there's anything in particular that we should improve with the commit linter, feel free to raise an issue or submit a PR.

**Comment by jonbgamble** [comment]
> Did you use [pre-commit](https://github.com/LadybirdBrowser/ladybird/blob/4249b14907ed5ecc6842bfef6d5477232195fe5f/CONTRIBUTING.md?plain=1#L133-L144) locally to lint your commits before pushing?

I did not, and thanks for the heads up about it. I am just now remembering to run lint-clang-format.py

> If there's anything in particular that we should improve with the commit linter, feel free to raise an issue or submit a PR.

Oh, it was just frustration from trying to force push a bunch of pseudo-historical commits carefully constructed from manual edits of `git add -p` hunks, only to be told "such and such commit message first line ends with a period" or "commit message isn't capital after the colon".

I'm miles away from an actionable suggestion.

File: Libraries/LibWeb/Layout/TextAreaBox.cpp [hunk 1]
```diff
@@ -0,0 +1,25 @@
+/*
+ * Copyright (c) 2018-2025, Andreas Kling <andreas@ladybird.org>
```
Comment (circl-lastname) [inline Libraries/LibWeb/Layout/TextAreaBox.cpp]: You should probably credit new files to yourself, starting in 2025 (unless this new file is a result of splitting an old one)

Comment (jonbgamble) [reply Libraries/LibWeb/Layout/TextAreaBox.cpp]: Is there some kind of modification threshold for attribution of changes to an existing file (i.e. when you should add your name to the list?

Comment (circl-lastname) [reply Libraries/LibWeb/Layout/TextAreaBox.cpp]: No not really, it's usually who created the file and then who contributed to it some arbitrary amount

File: Libraries/LibWeb/SVG/SVGSVGElement.h [hunk 2]
```diff
@@ -6,6 +6,7 @@
 
 #pragma once
 
+#include "LibWeb/CSS/Sizing.h"
```
Comment (shannonbooth) [inline Libraries/LibWeb/SVG/SVGSVGElement.h]: This was fixed in a later commit, but this should be made angle include in this commit here

File: Tests/LibWeb/Layout/expected/css-line-height-zero.txt [hunk 3]
```diff
@@ -29,17 +29,17 @@ Viewport <#document> at [0,0] [0+0+0 800 0+0+0] [0+0+0 600 0+0+0] [BFC] children
 ViewportPaintable (Viewport<#document>) [0,0 800x600]
   PaintableWithLines (BlockContainer<HTML>) [0,0 800x84]
     PaintableWithLines (BlockContainer<BODY>) [8,8 784x68]
-      PaintableWithLines (BlockContainer<INPUT>#a) [8,8 202x22]
+      PaintableWithLines (TextInputBox<INPUT>#a) [8,8 202x22]
```
Comment (shannonbooth) [inline Tests/LibWeb/Layout/expected/css-line-height-zero.txt:32]: The layout test changes should be committed alongside the change which changed the layout tests

File: Libraries/LibWeb/Layout/TextInputBox.h [hunk 4]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2018-2025, Andreas Kling <andreas@ladybird.org>
+ * Copyright (c) 2018-2025, Jonathan Gamble <gamblej@gmail.com>
```
Comment (shannonbooth) [inline Libraries/LibWeb/Layout/TextInputBox.h]: This should be adjusted in the commit which adds the file (also, the copyright date are not correct)

File: Libraries/LibWeb/Layout/Box.h [hunk 5]
```diff
@@ -44,6 +45,9 @@ class WEB_API Box : public NodeWithStyleAndBoxModelMetrics {
     void set_natural_width(Optional<CSSPixels> width) { m_natural_width = width; }
     void set_natural_height(Optional<CSSPixels> height) { m_natural_height = height; }
     void set_natural_aspect_ratio(Optional<CSSPixelFraction> ratio) { m_natural_aspect_ratio = ratio; }
+    virtual CSS::SizeWithAspectRatio natural_size() const { return {}; }
+    CSS::SizeWithAspectRatio intrinsic_content_box_size() const;
```
Comment (shannonbooth) [inline Libraries/LibWeb/Layout/Box.h]: The commit says: "Add Box::intrinsic_content_box_size", but it looks to only be added in the next commit

File: Libraries/LibWeb/Layout/Box.h [hunk 6]
```diff
@@ -18,7 +18,7 @@ struct LineBoxFragmentCoordinate {
     size_t fragment_index { 0 };
 };
 
-struct IntrinsicSizes {
+struct IntrinsicMinMaxCache {
```
Comment (awesomekling) [inline Libraries/LibWeb/Layout/Box.h]: Wait why are we renaming this? This is trying to model the [intrinsic sizes concept from the CSS-SIZING spec](https://drafts.csswg.org/css-sizing/#intrinsic-sizes)

File: Libraries/LibWeb/Layout/Box.h (hunk 5 above)
Comment (awesomekling) [inline Libraries/LibWeb/Layout/Box.h]: There's no spec concept called "intrinsic content box size" as far as I know. What is this supposed to correspond to?

File: Libraries/LibWeb/Layout/FlexFormattingContext.cpp [hunk 7]
```diff
@@ -2008,13 +2008,14 @@ bool FlexFormattingContext::should_treat_cross_max_size_as_none(Box const& box)
...
+    bool cross_size_auto = should_treat_cross_size_as_auto(item.box);
     auto size = [&] {
-        if (should_treat_cross_size_as_auto(item.box))
+        if (cross_size_auto)
             return calculate_min_content_cross_size(item);
         return !is_row_layout() ? get_pixel_width(item, computed_cross_size(item.box)) : get_pixel_height(item, computed_cross_size(item.box));
     }();
 
-    if (item.box->has_preferred_aspect_ratio())
+    if (cross_size_auto && item.box->has_preferred_aspect_ratio())
```
Comment (awesomekling) [inline Libraries/LibWeb/Layout/FlexFormattingContext.cpp:2050]: Is this change covered by a test?

File: Libraries/LibWeb/Layout/FlexFormattingContext.cpp [hunk 8]
```diff
@@ -2030,13 +2031,14 @@ CSSPixels FlexFormattingContext::calculate_cross_min_content_contribution(FlexIt
...
+    bool cross_size_auto = should_treat_cross_size_as_auto(item.box);
     auto size = [&] {
-        if (should_treat_cross_size_as_auto(item.box))
+        if (cross_size_auto)
             return calculate_max_content_cross_size(item);
         return !is_row_layout() ? get_pixel_width(item, computed_cross_size(item.box)) : get_pixel_height(item, computed_cross_size(item.box));
     }();
 
-    if (item.box->has_preferred_aspect_ratio())
+    if (cross_size_auto && item.box->has_preferred_aspect_ratio())
```
Comment (awesomekling) [inline Libraries/LibWeb/Layout/FlexFormattingContext.cpp:2073]: Is this change covered by a test?

File: Libraries/LibWeb/Layout/Box.h (hunk 5 above)
Comment (jonbgamble) [reply Libraries/LibWeb/Layout/Box.h]: No, it is not a spec term.

In this (maybe misguided) framing, "intrinsic content box size" is the size of the content box for an element with a natural, default (other than 300x150), or attribute-informed size that only contributes when the corresponding axis is auto/indefinite.

It's an attempt at generalizing "natural size" to encompass elements that can be replaced-like with respect to layout like input and textarea, but do not have "natural sizes" and are not replaced. I believe that this or some similar mechanism is needed to allow length/size/cols attributes (size="10", rows="5", etc) to contribute without dominating extrinsic sizing or classifying them in the ReplaceBox hierarchy.

I realize that "intrinsic" is highly overloaded here. And the attempt at deconfliction by renaming IntrinsicSizes to IntrinsicMinMaxCache to create some distance is an example of me struggling with this and making the wrong call.

File: Libraries/LibWeb/Layout/Box.h (hunk 6 above)
Comment (jonbgamble) [reply Libraries/LibWeb/Layout/Box.h]: An overreach, see below.

File: Libraries/LibWeb/Layout/FlexFormattingContext.cpp (hunk 7 above)
Comment (jonbgamble) [reply Libraries/LibWeb/Layout/FlexFormattingContext.cpp:2050]: [definite-cross-size-overrides-preferred-aspect-ratio-contribution.html](https://github.com/jonbgamble/ladybird/blob/a85a200a6bbe235a673e44d4bf98968f548602e2/Tests/LibWeb/Layout/input/flex/definite-cross-size-overrides-preferred-aspect-ratio-contribution.html)

File: Libraries/LibWeb/Layout/FlexFormattingContext.cpp (hunk 8 above)
Comment (jonbgamble) [reply Libraries/LibWeb/Layout/FlexFormattingContext.cpp:2073]: [definite-cross-size-overrides-preferred-aspect-ratio-contribution.html](https://github.com/jonbgamble/ladybird/blob/a85a200a6bbe235a673e44d4bf98968f548602e2/Tests/LibWeb/Layout/input/flex/definite-cross-size-overrides-preferred-aspect-ratio-contribution.html)

**Comment by jonbgamble** [comment]
Now that I'm accustomed to this project's standards, commits like https://github.com/LadybirdBrowser/ladybird/pull/7028/commits/bbde3d8f168f05f1a093cce45121809e0832ab6d and https://github.com/LadybirdBrowser/ladybird/pull/7028/commits/bfee96644411b4597774a293e237b004ff12c845 will be their own PRs in the future. I could break them out of this one if it simplifies anything.

File: Libraries/LibWeb/Layout/Box.h (hunk 5 above)
Comment (jonbgamble) [reply Libraries/LibWeb/Layout/Box.h]: This term is renamed to auto_content_box_size in the latest push. Hopefully this describes the abstraction mechanics a bit better.

File: Libraries/LibWeb/Layout/Box.cpp [hunk 9]
```diff
@@ -31,32 +31,15 @@ Box::~Box()
 {
 }
 
-Optional<CSSPixels> Box::natural_width() const
+CSS::SizeWithAspectRatio Box::auto_content_box_size() const
 {
-    // https://drafts.csswg.org/css-contain-2/#containment-size
+    // https://www.w3.org/TR/css-contain-2/#containment-size
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/Box.cpp]: We generally prefer the drafts.csswg.org links, because they're more up to date. (In theory, we only need to implement "recommendation" specs. In practice, the web relies on a large number of draft features. So we might as well try and implement the newest draft.)

File: Libraries/LibWeb/Layout/FlexFormattingContext.cpp [hunk 10]
```diff
@@ -775,8 +771,9 @@ void FlexFormattingContext::determine_flex_base_size(FlexItem& item)
     //         - using stretch-fit main size if the flex basis is indefinite, there is no
     //           intrinsic size and no cross size to resolve the ratio against.
     //         - in response to cross size min/max constraints.
-    if (item.box->has_natural_aspect_ratio()) {
-        if (!item.used_flex_basis_is_definite && !item.box->has_natural_width() && !item.box->has_natural_height() && !has_definite_cross_size(item)) {
+    auto auto_size = item.box->auto_content_box_size(); // ?
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/FlexFormattingContext.cpp]: What's the `// ?` comment? If you're unsure if this is correct, a `// FIXME: ...` comment is easier to find.

File: Libraries/LibWeb/Layout/GridFormattingContext.cpp [hunk 11]
```diff
@@ -1757,7 +1757,8 @@ void GridFormattingContext::resolve_grid_item_sizes(GridDimension dimension)
         };
 
         ItemAlignment used_alignment;
-        if (item.box->is_replaced_box() && item.box->has_natural_width()) {
+        auto hint = item.box->auto_content_box_size();
+        if (item.box->is_replaced_box() && (hint.has_width() || hint.has_height())) {
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/GridFormattingContext.cpp]: This previously only checked the width, and now checks the height too. Was that intentional?

File: Libraries/LibWeb/Layout/ImageBox.cpp [hunk 12]
```diff
@@ -29,33 +29,33 @@ void ImageBox::visit_edges(JS::Cell::Visitor& visitor)
...
 {
-    set_natural_width(m_image_provider.intrinsic_width());
-    set_natural_height(m_image_provider.intrinsic_height());
-    set_natural_aspect_ratio(m_image_provider.intrinsic_aspect_ratio());
+    if (m_image_provider.is_image_available())
+        return {
+            .width = m_image_provider.intrinsic_width(),
+            .height = m_image_provider.intrinsic_height(),
+            .aspect_ratio = m_image_provider.intrinsic_aspect_ratio()
+        };
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/ImageBox.cpp]: Nit: Please wrap block contents in `{}` if it takes up multiple lines.

File: Libraries/LibWeb/Layout/SVGSVGBox.h [hunk 13]
```diff
@@ -26,12 +26,10 @@ class SVGSVGBox final : public ReplacedBox {
 
     virtual GC::Ptr<Painting::Paintable> create_paintable() const override;
 
-    virtual void prepare_for_replaced_layout() override;
-
 private:
+    // virtual CSS::SizeWithAspectRatio compute_intrinsic_box_size() const override;
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/SVGSVGBox.h]: This looks like it was left here by mistake.

File: Libraries/LibWeb/Layout/VideoBox.cpp [hunk 14]
```diff
@@ -37,18 +37,9 @@ HTML::HTMLVideoElement const& VideoBox::dom_node() const
...
-    set_natural_width(width);
-
-    CSSPixels height = dom_node().video_height();
-    set_natural_height(height);
-
-    if (width != 0 && height != 0)
-        set_natural_aspect_ratio(width / height);
-    else
-        set_natural_aspect_ratio({});
+    return { dom_node().video_width(), dom_node().video_height(), {} };
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/VideoBox.cpp]: This doesn't return an aspect-ratio, and the previous code used to set it sometimes.

File: Libraries/LibWeb/Layout/RadioButton.h [hunk 15]
```diff
@@ -20,6 +20,7 @@ class RadioButton final : public FormAssociatedLabelableNode {
     virtual ~RadioButton() override;
 
 private:
+    CSS::SizeWithAspectRatio compute_auto_content_box_size() const override { return { 12, 12, {} }; }
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/Layout/RadioButton.h:23]: The previous code used to set an aspect-ratio of 1.

File: Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/visudet/inline-block-baseline-001-ref.xht [hunk 16]
```diff
@@ -0,0 +1,22 @@
+<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
```
Comment (AtkinsSJ) [inline Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/visudet/inline-block-baseline-001-ref.xht]: This commit seems a bit wrong - the description suggests a code change but this is just adding a test. Is this a rebasing artifact maybe?

File: Libraries/LibWeb/HTML/HTMLInputElement.cpp [hunk 17]
```diff
@@ -137,16 +138,28 @@ GC::Ptr<Layout::Node> HTMLInputElement::create_layout_node(GC::Ref<CSS::Computed
...
-
-    return Element::create_layout_node_for_display_type(document(), style->display(), style, this);
+    case TypeAttributeState::Text:
+    case TypeAttributeState::Search:
+    case TypeAttributeState::URL:
+    case TypeAttributeState::Telephone:
+    case TypeAttributeState::Email:
+    case TypeAttributeState::Password:
+    case TypeAttributeState::Number:
+        // FIXME: text padding issues
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/HTML/HTMLInputElement.cpp:157]: This FIXME seems like it applies more to the code inside TextInputBox.cpp

File: Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/visudet/inline-block-baseline-001-ref.xht (hunk 16 above)
Comment (jonbgamble) [reply Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/visudet/inline-block-baseline-001-ref.xht]: Yes, @gmta fixed that one out from under me. But his fix is better.

File: Libraries/LibWeb/Layout/VideoBox.cpp (hunk 14 above)
Comment (jonbgamble) [reply Libraries/LibWeb/Layout/VideoBox.cpp]: Good catch - I think it was right before, and we do need a natural aspect ratio for VideoBox here.

In a broader sense, my intent was that auto_content_box_size does not try to calculate anything that isn't explicitly given by a provider or attribute. Elsewhere (such as input elements), I think the absence of an aspect ratio carries more information than computing it on demand.

File: Libraries/LibWeb/Layout/RadioButton.h (hunk 15 above)
Comment (jonbgamble) [reply Libraries/LibWeb/Layout/RadioButton.h:23]: But CheckBox (previously and now) used {} for aspect ratio. Is there a reason CheckBox and RadioButton should be treated differently?

File: Libraries/LibWeb/Layout/GridFormattingContext.cpp (hunk 11 above)
Comment (jonbgamble) [reply Libraries/LibWeb/Layout/GridFormattingContext.cpp]: The original code was column-centric, but this function is called on both axes. So the fear was that a replaced element where width is missing/0/unknown but height is known would erroneously fall back to fit-content / intrinsic sizing (with wrong results).

I'm going to make it more explicit by gating on dimension.

File: Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/visudet/inline-block-baseline-001-ref.xht (hunk 16 above)
Comment (jonbgamble) [reply Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/visudet/inline-block-baseline-001-ref.xht]: I commandeered this commit's slot in my rebase for the behavior changing size hint fix in grid layout, with a new test.

File: Libraries/LibWeb/HTML/HTMLInputElement.cpp (hunk 17 above)
Comment (jonbgamble) [reply Libraries/LibWeb/HTML/HTMLInputElement.cpp:157]: It applies to both TextInputBox and HTMLInputElement. The offensive padding is applied in the shadow tree, and it trickles into box considerations. I think the UA stylesheet is a better place for default padding, but when I tried to make that change the text alignment was different. And I had to stop changing code at some point...

**Comment by jonbgamble** [comment]
@AtkinsSJ YOLO!

File: Libraries/LibWeb/Layout/RadioButton.h (hunk 15 above)
Comment (AtkinsSJ) [reply Libraries/LibWeb/Layout/RadioButton.h:23]: No idea, just thought I should point out any possibly-accidental changes. It's fine.
