### PR TITLE
LibWeb: Adjust buttons computed display style

### LINKED ISSUE #2395: Buttons with `display: inline` are empty
### Summary

Putting `display: inline` on a `<button>` makes it be empty.

### Operating system

Linux

### Steps to reproduce

1. `<button style="display: inline">This is invisible.</button>`

### Expected behavior

`<button style="display: inline">This should be visible.</button>`

### Actual behavior

`<button style="display: inline">This is invisible.</button>`

### URL for a reduced test case

`data:text/html,<button style="display: inline">Hello!</button>`

### HTML/SVG/etc. source for a reduced test case

```html
<button style="display: inline">Hello!</button>
```

### Log output and (if possible) backtrace

```shell
4045.236 WebContent(6905): FIXME: InlineFormattingContext::dimension_box_on_line got unexpected box in inline context:
4045.236 WebContent(6905): BlockContainer <input> (not painted) [0+0+0 0 0+0+0] [0+0+0 0 0+0+0] children: not-inline
  BlockContainer <(anonymous)> (not painted) flex-container(column) [0+0+0 0 0+0+0] [0+0+0 0 0+0+0] [FFC] children: not-inline
    BlockContainer <(anonymous)> (not painted) [0+0+0 0 0+0+0] [0+0+0 0 0+0+0] [BFC] children: inline
      BlockContainer <span> (not painted) inline-block [0+0+0 0 0+0+0] [0+0+0 0 0+0+0] [BFC] children: inline
        TextNode <#text>
```
```


### Screenshots or screen recordings

Reduced test case in Ladybird:
![image](https://github.com/user-attachments/assets/8c1dce14-bc12-44de-adcb-0d824a49423d)

Reduced test case in Firefox:
![image](https://github.com/user-attachments/assets/c36460f5-30cb-4c5c-b1a4-28a2171a958b)


### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by lpas**
fixes #2395

### CODE REVIEW

File: Libraries/LibWeb/HTML/HTMLButtonElement.cpp [hunk 1]
```diff
@@ -29,6 +30,22 @@ void HTMLButtonElement::initialize(JS::Realm& realm)
     Base::initialize(realm);
 }
 
+void HTMLButtonElement::adjust_computed_style(CSS::ComputedProperties& style)
```
Comment (lpas) [inline Libraries/LibWeb/HTML/HTMLButtonElement.cpp:34]: this also adjusts the style of ::before & ::after pseudo elements from the button like [Tests/LibWeb/Layout/expected/button-with-before-and-after-pseudo-elements.txt‎](https://github.com/LadybirdBrowser/ladybird/pull/6481/files#diff-9bb352a8d6a5468a1e5e77dbb0df43035851b8c527b1b303ee6463dc6bb75054) shows. 

I don't know how to prevent that.

File: Libraries/LibWeb/HTML/HTMLButtonElement.cpp [hunk 2]
```diff
@@ -29,6 +31,22 @@ void HTMLButtonElement::initialize(JS::Realm& realm)
...
+{
+    // https://html.spec.whatwg.org/multipage/rendering.html#button-layout
+    // If the computed value of 'display' is 'inline-grid', 'grid', 'inline-flex', 'flex', 'none', or 'contents', then behave as the computed value.
+    auto display = style.display();
+    if (display.is_flex_inside() || display.is_grid_inside() || display.is_none() || display.is_contents()) {
+
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/HTML/HTMLButtonElement.cpp]: Nit: Put a `// No-op` comment or something in here, so it doesn't look like the code is just missing.

File: Libraries/LibWeb/HTML/HTMLButtonElement.cpp [hunk 3]
```diff
@@ -29,6 +31,22 @@ void HTMLButtonElement::initialize(JS::Realm& realm)
     Base::initialize(realm);
 }
 
+void HTMLButtonElement::adjust_computed_style(CSS::ComputedProperties& style)
+{
+    // https://html.spec.whatwg.org/multipage/rendering.html#button-layout
+    // If the computed value of 'display' is 'inline-grid', 'grid', 'inline-flex', 'flex', 'none', or 'contents', then behave as the computed value.
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/HTML/HTMLButtonElement.cpp:37]: As discussed about the "behave as" thing: Once you've raised a spec issue, you don't have to wait for that to be resolved, but make sure to link to it here and note that it's `// AD-HOC` because different browsers do it differently.

**Comment by AtkinsSJ** [comment]
I think this won't merge until the wasm issue is fixed on master and then you rebase on that. :^(
