### PR TITLE
LibWeb: Implement TextDecoderStream

### LINKED ISSUE #6769: Sourcegraph Search returns 0 results every time
### Summary

Searching for anything in [Sourcegraph](https://sourcegraph.com/search) yields zero results whereas there should be results and other browsers are able to handle the website properly.

### Operating system

Linux

### Steps to reproduce

1. Go to sourcegraph.com/search
2. Search for anything (eg. ladybird)
3. Hit enter to search

### Expected behavior

Search results with ladybird in them. (maybe repo name, text match in code etc)

### Actual behavior

Zero results are returned.

### URL for a reduced test case

https://sourcegraph.com/search?q=ladybird&patternType=keyword&sm=0

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
63399.687 WebContent(53): ResourceLoader: Filtered request to: "https://www.googletagmanager.com/gtm.js?id=GTM-TB4NLS7"
63399.688 WebContent(53): HTMLScriptElement: Refusing to run script because the element's result is null.
63399.807 WebContent(53): (js warn) "The Sentry loader you are trying to use isn't working anymore, check your configuration."
63399.812 WebContent(53): ResourceLoader: Filtered request to: "https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015"
63399.812 WebContent(53): HTMLScriptElement: Refusing to run script because the element's result is null.
63400.621 WebContent(53): ImageDecoderClient: Failed to decode image with ID 0: Decoding failed: Could not find suitable image decoder plugin for data
63402.304 WebContent(53): FIXME: Unimplemented IDL interface: 'SVGSVGElementPrototype.preserveAspectRatio'
63402.304 WebContent(53): FIXME: Unimplemented IDL interface: 'SVGSVGElementPrototype.createSVGAngle'
63402.304 WebContent(53): FIXME: Unimplemented IDL interface: 'SVGSVGElementPrototype.createSVGTransformFromMatrix'
63402.305 WebContent(53): FIXME: Unimplemented IDL interface: 'HTMLImageElementPrototype.x'
63402.305 WebContent(53): FIXME: Unimplemented IDL interface: 'HTMLImageElementPrototype.y'
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [x] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by awesomekling**
This is the streaming counterpart to `TextDecoder`, used by sites that process responses with `pipeThrough(new TextDecoderStream())` or that otherwise consume a `Response` body as decoded text.
    
The transform algorithm appends each chunk's bytes to the I/O queue and decodes them via the underlying LibTextCodec decoder, holding back  any trailing partial UTF-8 sequence so chunk boundaries don't produce spurious replacement characters. The flush algorithm emits a single replacement character if a partial sequence was still pending. For non-UTF-8 encodings the underlying decoders are stateless across calls, so each chunk is decoded in full with nothing carried over.

This makes the Reddit SPA stop swallowing link clicks so you can open the comments section for a post. :^)

Closes #6769

### CODE REVIEW

**Comment by tcl3** [comment]
If I remember correctly, this should fix #6769

File: Libraries/LibWeb/Encoding/TextDecoderStream.cpp [hunk 1]
```diff
@@ -0,0 +1,237 @@
...
+    }
+
+    // No leading byte found within the last 4 bytes. Either the buffer is shorter than that, or it ends with 4
+    // continuation bytes (malformed UTF-8). Either way, decode everything; the decoder will produce replacement
+    // characters as needed.
+    return bytes.size();
+}
+
+// https://encoding.spec.whatwg.org/#dom-textdecoderstream
+WebIDL::ExceptionOr<GC::Ref<TextDecoderStream>> TextDecoderStream::construct_impl(JS::Realm& realm, FlyString label, Optional<TextDecoderOptions> const& options)
```
Comment (shannonbooth) [inline Libraries/LibWeb/Encoding/TextDecoderStream.cpp]: If I understand correctly this can be without Optional

File: Libraries/LibWeb/Encoding/TextDecoderStream.cpp [hunk 2]
```diff
@@ -0,0 +1,237 @@
...
+}
+
+// https://encoding.spec.whatwg.org/#decode-and-enqueue-a-chunk
+WebIDL::ExceptionOr<void> TextDecoderStream::decode_and_enqueue_chunk(JS::Value chunk)
+{
+    auto& realm = this->realm();
+    auto& vm = realm.vm();
+
+    // 1. Let bufferSource be the result of converting chunk to an AllowSharedBufferSource.
+    if (!chunk.is_object() || !(is<JS::ArrayBuffer>(chunk.as_object()) || is<JS::TypedArrayBase>(chunk.as_object()) || is<JS::DataView>(chunk.as_object())))
```
Comment (shannonbooth) [inline Libraries/LibWeb/Encoding/TextDecoderStream.cpp]: is_buffer_source type helper may be useful here (though still slightly clunky)

File: Libraries/LibWeb/Encoding/TextDecoderStream.cpp [hunk 3]
```diff
@@ -0,0 +1,237 @@
...
+    String decoded;
+    if (!m_io_queue.is_empty()) {
+        decoded = "\xEF\xBF\xBD"_string;
+        m_io_queue.clear();
+    }
+
+    return enqueue_decoded_output(move(decoded));
+}
+
+WebIDL::ExceptionOr<void> TextDecoderStream::enqueue_decoded_output(String decoded)
```
Comment (shannonbooth) [inline Libraries/LibWeb/Encoding/TextDecoderStream.cpp]: nit but const&

File: Libraries/LibWeb/Encoding/TextDecoderStream.cpp [hunk 4]
```diff
@@ -0,0 +1,237 @@
...
+        }
+        return WebIDL::create_resolved_promise(realm, JS::js_undefined());
+    });
+
+    // 8. Let flushAlgorithm be an algorithm which takes no arguments and runs the flush and enqueue algorithm with this.
+    auto flush_algorithm = GC::create_function(realm.heap(), [stream]() -> GC::Ref<WebIDL::Promise> {
+        auto& realm = stream->realm();
+        auto& vm = realm.vm();
+        if (auto result = stream->flush_and_enqueue(); result.is_error()) {
+            auto throw_completion = Bindings::exception_to_throw_completion(vm, result.exception());
```
Comment (shannonbooth) [inline Libraries/LibWeb/Encoding/TextDecoderStream.cpp]: We have a nicer reject_promise_with_exception helper now to fold these two lines together
