### PR TITLE
LibWeb: Update the select label when option's children are changed

### LINKED ISSUE #2385: Select element does not react to changes to its selected option's text content
### Summary

When you modify the text in a `<select>`'s selected `<option>`, the text display on the select element should reflect that new value,
It does not.

A website that is broken by this is https://battle.crossuniverse.net/settings (see the language dropdown at the very top)

### Operating system

Linux

### Steps to reproduce

1. Make a select element.
2. Put an option in it
3. Select the option
4. Use JS to change the options `text`, `innerHTML`, `innerText`, `textContent` or to `setHTMLUnsafe()` its contents or to append or remove children from it etc...

### Expected behavior

The text on the select element should update to reflect the new content of the option element.

### Actual behavior

The select element does not update to reflect the new content of the option element.

### URL for a reduced test case

`data:text/html,<select><option id="foo"></option></select><script>foo.textContent="foo"</script>`

### HTML/SVG/etc. source for a reduced test case

```html
<select>
  <option id="foo"></option>
</select>
<script>foo.textContent = "foo";</script>
```

### Log output and (if possible) backtrace

```shell
Nothing.
```

### Screenshots or screen recordings

Ladybird:
image

Firefox:
image

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by Gingeh**
..and when the label attribute or text is changed (but that didn't fit in the message)

Partially fixes #2385 (and fixes the real world example provided in the issue).
A fully correct implementation would also need to update the label if any text descendants are changed.

### CODE REVIEW

File: Libraries/LibWeb/HTML/HTMLOptionElement.cpp [hunk 1]
```diff
@@ -147,6 +154,8 @@ String HTMLOptionElement::text() const
 void HTMLOptionElement::set_text(String const& text)
 {
     string_replace_all(text);
+
+    update_selection_label();
```
Comment (awesomekling) [inline Libraries/LibWeb/HTML/HTMLOptionElement.cpp:158]: Does the call to `string_replace_all()` here not already cause `children_changed()` to be called?

Comment (Gingeh) [reply Libraries/LibWeb/HTML/HTMLOptionElement.cpp:158]: Ah true, and the `set_attribute` call in `set_label` also triggers `attribute_changed`
