### PR TITLE
LibWeb: Disable Navigation API after `document.open()` on `about:blank`

### LINKED ISSUE #8590: document.open() crashes with Navigation::current_entry
https://github.com/LadybirdBrowser/ladybird/commit/45a87b1dbee317aa461f781fc53bc40c00516da6 appears to have caused a whole lot of crashes on WPT to happen. After some investigation, I think this was a latent bug which was exposed by calling perform_url_and_history_update_steps.

I think the root cause is related to our initial about blank document handling.

Here is an example HTML page that crashes before 45a87b1dbee317aa461f781fc53bc40c00516da6 which I believe has the same root cause as the recent crashes introduced to WPT (NOTE: needs to be loaded over HTTP!)

```html
<!DOCTYPE html>
<script src="../include.js"></script>
<script>
    async function tick() {
        await new Promise(resolve => setTimeout(resolve, 0));
    }

    asyncTest(async done => {
        const iframe = document.createElement("iframe");
        document.body.appendChild(iframe);

        const iframeDocument = iframe.contentDocument;
        const navigation = iframe.contentWindow.navigation;

        iframeDocument.open();
        iframeDocument.write("<!DOCTYPE html><p>first</p>");
        iframeDocument.close();

        println(iframe.contentDocument.body.textContent);
        println(navigation.entries().length);
        println(navigation.currentEntry);

        await tick();

        iframeDocument.open();
        iframeDocument.write("<!DOCTYPE html><p>second</p>");
        iframeDocument.close();

        println(iframe.contentDocument.body.textContent);
        println(navigation.entries().length);
        println(navigation.currentEntry);
        done();
    });
</script>
```

I'm unsure of a proper fix here, though I have found a few different things which work around the crash, but I am not convinced are correct.

### PR DESCRIPTION
**Pull request by tcl3**
This follows the Blink/WebKit approach described in this spec issue: https://github.com/whatwg/html/issues/11811

Fixes [a number of WPT crashes](https://wpt.fyi/results/html/syntax/parsing?q=ladybird%3Acrash&run_id=5081858357592064) in `html/syntax/parsing`.

Fixes #8590

### CODE REVIEW

File: Libraries/LibWeb/DOM/Document.cpp [hunk 1]
```diff
@@ -851,6 +851,11 @@ WebIDL::ExceptionOr<Document*> Document::open(Optional<String> const&, Optional<
         HTML::perform_url_and_history_update_steps(*this, move(new_url));
     }
 
+    // AD-HOC: Record that this document was an initial about:blank before document.open() cleared the flag, so the
+    //         Navigation API can keep entries and events disabled.
+    if (is_initial_about_blank())
+        as<HTML::Window>(HTML::relevant_global_object(*this)).navigation()->set_was_initial_about_blank_opened(true);
```
Comment (shannonbooth) [inline Libraries/LibWeb/DOM/Document.cpp:857]: I suppose this fixes #11811.

One question which I was not sure about here though with this though is when / if ever does the document have this flag unset

Comment (shannonbooth) [reply Libraries/LibWeb/DOM/Document.cpp:857]: Also i think you mean blink/gecko, though maybe webkit has adopted the same

Comment (shannonbooth) [reply Libraries/LibWeb/DOM/Document.cpp:857]: actually i have fully misread!

Comment (tcl3) [reply Libraries/LibWeb/DOM/Document.cpp:857]: > One question which I was not sure about here though with this though is when / if ever does the document have this flag unset

Good point. I've made sure the flag is reset when a new navigation occurs.

File: Libraries/LibWeb/HTML/Navigation.cpp [hunk 2]
```diff
@@ -1430,6 +1436,10 @@ void Navigation::initialize_the_navigation_api_entries_for_a_new_document(Vector
     // 2. Assert: navigation's current entry index is −1.
     VERIFY(m_current_entry_index == -1);
 
+    // AD-HOC: This flag is only set when an about:blank page is modified by document.open(). Reset it now that a new
+    //         navigation is happening.
+    m_was_initial_about_blank_opened = false;
```
Comment (shannonbooth) [inline Libraries/LibWeb/HTML/Navigation.cpp:1441]: I've been trying to come up with a test that demonstrates this change, but it is not triggered. Maybe this is not observable if only invoked for a new document since initial about blank document is meant to be replaced?

**Comment by awesomekling** [comment]
Merging to clean up WPT crashes
