### PR TITLE
LibWeb: Push temporary EC before rejecting failed image decode

### LINKED ISSUE #419: Crash when loading Google Maps
While browsing Google owned domains, specifically Google.com, Youtube, Gmail, Google Maps image assets are taking exceedingly long to open. Google Maps simply crashes the browser. Startpage, DuckDuckGo function fine however. 
Reviewing the terminal read out, this seems to be related to not having a decoder in place, however it is a JPEG image format, initially thinking that it might have been a WEBP instead. Startpage.com logo image is SVG formatted and loads fine however.

### PR DESCRIPTION
**Pull request by awesomekling**
Fixes #419

### CODE REVIEW

File: Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp [hunk 1]
```diff
@@ -302,6 +302,7 @@ WebIDL::ExceptionOr<JS::NonnullGCPtr<JS::Promise>> HTMLImageElement::decode() co
                 return false;
 
             auto exception = WebIDL::EncodingError::create(realm, "Current request state is broken"_fly_string);
+            HTML::TemporaryExecutionContext context(HTML::relevant_settings_object(*this));
```
Comment (ADKaster) [inline Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp:305]: This feels like a structural problem with the entire method. There's another instance in `reject_if_document_not_fully_active` where we could be in the deferred_invoke without having an execution context.

I think we should slap a context at the top of the queue_microtask, and the top of the deferred_invoke on 322, instead of only having it in two places. (and the context should have the callback flag set).

Comment (ADKaster) [reply Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp:305]: Unless it's guaranteed to have an execution context in queue_a_microtask? In which case it would only be needed in the deferred_invoke

Comment (awesomekling) [reply Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp:306]: After staring at the code for a bit, I concluded that we (probably) need to ensure a temporary context exists in all three code paths.
