### PR TITLE
LibWeb: Propagate style values in deep anonymous wrappers

### LINKED ISSUE #4676: CSS label color change on hover is not applied on button element
### Summary

See min repro below, the color of the text in the button is not changed when hovering. Possibly CSS other properties  have this issue too on hover (originated from looking at the auth buttons at the mottom of https://www.openstreetmap.org/user/new)

**Min repro screenshots**
Hovering in LB:
Image

Hovering in Chrome:
Image

### Operating system

Linux

### Steps to reproduce

See min repro and screenshots

### Expected behavior

Color of button text change

### Actual behavior

No change

### URL for a reduced test case

NN

### HTML/SVG/etc. source for a reduced test case

```html
<style>
.btn:hover {
	color:  #fff;
}
</style>

<button type="button" class="btn">BUTTON</button>
```

### Log output and (if possible) backtrace

```shell
NN
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

LB 123abe0e79354d4cfc005adc973688f6e378365a, Linux

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by lpas**
`wrap_in_button_layout_tree_if_needed` creates two nested anonymous wrapper. With this fix styles get propagated two the children.

fixes #4676

### CODE REVIEW

**Review by awesomekling — CHANGES_REQUESTED** [review]
Please wrap commit messages at 72 characters, not 50.

And more importantly, can we add a test? :)

**Comment by lpas** [comment]
> And more importantly, can we add a test? :)

I'm not sure how to Test this. This can only be seen in layout on hover over a button.

**Comment by awesomekling** [comment]
> > And more importantly, can we add a test? :)
> 
> I'm not sure how to Test this. This can only be seen in layout on hover over a button.

We can use the `internals.movePointerTo(double x, double y)` API available when running in test mode :) (See `Internals.idl` for a list of all the extra APIs you can use for testing)

**Comment by lpas** [comment]
Oh I didn't think I could use JS in screenshot/ref tests. That is a very nice test setup!
 
I added a test.

File: Libraries/LibWeb/Layout/Node.cpp [hunk 1]
```diff
@@ -913,6 +913,15 @@ void NodeWithStyle::apply_style(CSS::ComputedProperties const& computed_style)
         box_node->propagate_style_along_continuation(computed_style);
```
Comment (gmta) [inline Libraries/LibWeb/Layout/Node.cpp:922]: Commit message typos: "wrapper" -> "wrappers", "get propagated two the children" -> "get propagated to the children"

Your commit message does not really describe what's going on though: non-inherited styles did not get propagated as part of NodeWithStyle::apply_style(), _and_ we did not propagate to nested anonymous wrappers (i.e. descendants, not just children).

Comment (lpas) [reply Libraries/LibWeb/Layout/Node.cpp:922]: I updated the commit message

**Review by gmta — APPROVED** [review]
