### PR TITLE
LibRegex: Make RegexDebug resilient to empty state vectors

### LINKED ISSUE #7502: TestRegex fails in Vector when REGEX_DEBUG is ON
Found while testing #6581 with ENABLE_ALL_THE_DEBUG_MACROS

https://github.com/LadybirdBrowser/ladybird/actions/runs/21079256880/job/60628717515?pr=6581

Reproduced it with `cmake -B Build/release -DREGEX_DEBUG=ON`

Not sure exactly when this was introduced, but seems to be a recent issue. I'll try to find the commit where it started.

```
.
.
.
VERIFICATION FAILED: i < m_size at /home/bobo/projects/myladybird/AK/Vector.h:172
Stack trace (most recent call first):
#0  (inlined)          in AK::Vector<unsigned long, 0ul, (AK::FastLastAccess)0>::at(unsigned long) at /home/bobo/projects/myladybird/AK/Vector.h:172:9
#1  0x00007007d6dd66ce in AK::Vector<unsigned long, 0ul, (AK::FastLastAccess)0>::last() at /home/bobo/projects/myladybird/AK/Vector.h:220:22
#2  0x00007007d6dfc7d1 in regex::RegexDebug<regex::FlatByteCode>::print_result(regex::OpCode<regex::FlatByteCode> const&, regex::FlatByteCode const&, regex::MatchInput const&, regex::MatchState&, regex::ExecutionResult) const at /home/bobo/projects/myladybird/Libraries/LibRegex/RegexDebug.h:105:94
#3  0x00007007d6e04da5 in regex::Matcher<regex::ECMA262Parser>::execute(regex::MatchInput const&, regex::MatchState&, unsigned long&) const at /home/bobo/projects/myladybird/Libraries/LibRegex/RegexMatcher.cpp:591:33
#4  0x00007007d6e05af8 in regex::Matcher<regex::ECMA262Parser>::match(AK::Vector<regex::RegexStringView, 0ul, (AK::FastLastAccess)0> const&, AK::Optional<regex::RegexOptions<regex::ECMAScriptFlags> >) const at /home/bobo/projects/myladybird/Libraries/LibRegex/RegexMatcher.cpp:344:44
#5  0x00007007d6e064be in regex::Matcher<regex::ECMA262Parser>::match(regex::RegexStringView, AK::Optional<regex::RegexOptions<regex::ECMAScriptFlags> >) const at /home/bobo/projects/myladybird/Libraries/LibRegex/RegexMatcher.cpp:167:38
#6  0x00005e0cc08dbbe9 in regex::Regex<regex::ECMA262Parser>::match(regex::RegexStringView, AK::Optional<regex::RegexOptions<regex::ECMAScriptFlags> >) const at /home/bobo/projects/myladybird/Libraries/LibRegex/RegexMatcher.h:109:50
#7  0x00005e0cc08f7bc3 in __test_lookbehind at /home/bobo/projects/myladybird/Tests/LibRegex/TestRegex.cpp:808:9
#8  0x00005e0cc08d9e72 in AK::Function<void ()>::CallableWrapper<void (*)()>::call() at /home/bobo/projects/myladybird/AK/Function.h:225:20
#9  0x00007007d6e9c26c in AK::Function<void ()>::operator()() const at /home/bobo/projects/myladybird/AK/Function.h:148:29
#10 0x00007007d6e9a9f0 in Test::TestSuite::run(AK::Vector<AK::NonnullRefPtr<Test::TestCase>, 0ul, (AK::FastLastAccess)0> const&) at /home/bobo/projects/myladybird/Libraries/LibTest/TestSuite.cpp:195:22
#11 0x00007007d6e9b6df in Test::TestSuite::main(AK::ByteString const&, AK::Span<AK::StringView>) at /home/bobo/projects/myladybird/Libraries/LibTest/TestSuite.cpp:147:15
#12 0x00005e0cc08fa458 in main at /home/bobo/projects/myladybird/Libraries/LibTest/TestMain.cpp:33:44
#13 0x00007007d662a577 in __libc_start_call_main at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#14 0x00007007d662a63a in __libc_start_main_impl at ./csu/../csu/libc-start.c:360:3
#15 0x00005e0cc08d9a24 in _start at /home/bobo/projects/myladybird/Build/alldebug/bin/TestRegex


99% tests passed, 1 tests failed out of 120

Total Test time (real) =  71.63 sec

The following tests FAILED:
	120 - TestRegex (ILLEGAL)
Errors while running CTest

```

### PR DESCRIPTION
**Pull request by mikiubo**
Avoid crashing in RegexDebug when saved_positions or step_backs are empty.
These cases are already handled correctly by the bytecode execution, but the debug output assumed non-empty vectors.

Print a placeholder instead when no entries are present. 
This partially fixes #7502.

### CODE REVIEW

**Comment by rcorsi** [comment]
Could you change the description above and the commit message to say that this "Fixes: #7502" .  It does not 'partially' fix it, it fixes it!  :-)  Thanks!

**Comment by rcorsi** [comment]
I did find many lines with the output with `saved: <empty>`

`                |       |           |                                     | saved: <empty>                 |  `

But none with `stepString: <empty>`.


```
./Build/release/bin/TestRegex --tests 2>&1 | strings | grep "stepString: "
./Build/release/bin/TestRegex --tests 2>&1 | strings | grep "saved: "
```

I had to use the `strings` command as it was complaining about binary output.

File: Libraries/LibRegex/RegexDebug.h [hunk 1]
```diff
@@ -102,13 +102,17 @@ class RegexDebug {
...
+            ByteString saved = "saved: <empty>";
+            if (!input.saved_positions.is_empty()) {
+                saved = ByteString::formatted("saved: {}", input.saved_positions.last());
+            }
             outln(m_file, "{:15} | {:5} | {:9} | {:35} | {:30} | {:20}", "", "", "", "", saved, "");
         }
         if (is<OpCode_CheckStepBack>(opcode) || is<OpCode_IncStepBack>(opcode)) {
-            auto formatted_result = String::formatted("step: {}", state.step_backs.last());
-            ByteString stepString = formatted_result.value().to_byte_string();
+            ByteString stepString = "stepString: <empty>";
```
Comment (rcorsi) [inline Libraries/LibRegex/RegexDebug.h]: Should the text be `step: <empty>` instead of `stepString: <empty>`, to match the code inside the if statement below?

File: Libraries/LibRegex/RegexDebug.h [hunk 2]
```diff
@@ -102,13 +102,17 @@ class RegexDebug {
...
+            ByteString saved = "saved: <empty>";
+            if (!input.saved_positions.is_empty()) {
+                saved = ByteString::formatted("saved: {}", input.saved_positions.last());
+            }
             outln(m_file, "{:15} | {:5} | {:9} | {:35} | {:30} | {:20}", "", "", "", "", saved, "");
         }
         if (is<OpCode_CheckStepBack>(opcode) || is<OpCode_IncStepBack>(opcode)) {
-            auto formatted_result = String::formatted("step: {}", state.step_backs.last());
-            ByteString stepString = formatted_result.value().to_byte_string();
+            ByteString stepString = "step: <empty>";
```
Comment (trflynn89) [inline Libraries/LibRegex/RegexDebug.h]: This wasn't noticed in the last PR, but please use snake_case for variable names.

File: Libraries/LibRegex/RegexDebug.h [hunk 3]
```diff
@@ -102,13 +102,17 @@ class RegexDebug {
         outln(m_file, " | {:20}", builder.to_byte_string());
 
         if (is<OpCode_CheckSavedPosition>(opcode)) {
-            auto formatted_result = String::formatted("saved: {}", input.saved_positions.last());
-            ByteString saved = formatted_result.value().to_byte_string();
+            ByteString saved = "saved: <empty>";
+            if (!input.saved_positions.is_empty()) {
+                saved = ByteString::formatted("saved: {}", input.saved_positions.last());
+            }
```
Comment (trflynn89) [inline Libraries/LibRegex/RegexDebug.h]: You can avoid creating a temporary string with a ternary in these cases. There's also no reason to use ByteString:
```c++
auto saved = input.saved_positions.is_empty()
    ? "saved: <empty>"_string
    : MUST(String::formatted("saved: {}", input.saved_positions.last()));
```

File: Libraries/LibRegex/RegexDebug.h [hunk 4]
```diff
@@ -102,14 +102,16 @@ class RegexDebug {
...
+            auto saved = input.saved_positions.is_empty()
+                ? "saved: <empty>"_string
+                : MUST(String::formatted("saved: {}", input.saved_positions.last()));
             outln(m_file, "{:15} | {:5} | {:9} | {:35} | {:30} | {:20}", "", "", "", "", saved, "");
         }
         if (is<OpCode_CheckStepBack>(opcode) || is<OpCode_IncStepBack>(opcode)) {
-            auto formatted_result = String::formatted("step: {}", state.step_backs.last());
-            ByteString stepString = formatted_result.value().to_byte_string();
-            outln(m_file, "{:15} | {:5} | {:9} | {:35} | {:30} | {:20}", "", "", "", "", stepString, "");
+            auto step_string = state.step_backs.is_empty()
```
Comment (rcorsi) [inline Libraries/LibRegex/RegexDebug.h]: I don't think the variable name usually includes the 'type', instead of `step_string` wouldn't `last_step` or `last_step_back`  be a more descriptive name?  And above `last_saved` or `last_saved_position?

Pick names consistent across these and that are as descriptive as possible without being too long. :-)

Sorry for the nit-picking.

Comment (mikiubo) [reply Libraries/LibRegex/RegexDebug.h]: You are right with those names is more clear!
Thanks i think now i fixed

File: Libraries/LibRegex/RegexDebug.h (hunk 2 above)
Comment (mikiubo) [reply Libraries/LibRegex/RegexDebug.h]: i think i fixed
 thanks

File: Libraries/LibRegex/RegexDebug.h (hunk 3 above)
Comment (mikiubo) [reply Libraries/LibRegex/RegexDebug.h]: thanks for the suggestion!
now i think i fixed
