### PR TITLE
Meta+RequestServer: Upgrade curl and fix navigating to IPv6 addresses directly

### LINKED ISSUE #3596: Unable to load sites using a IPv6 address directly
When typing in a IPV6 address directly e.g. `https://[2606:4700:4700::1111]` I get the error "unable to resolve host"

After some investigation, we pass the serialized host to LibDNS which isn't correct since IPv6 addresses don't contain square brackets and libcurl seems to have a bug with the `CURLOPT_RESOLVE` option which I've filed a report for here: https://github.com/curl/curl/issues/16357

### PR DESCRIPTION
**Pull request by rmg-x**
After the upgrade to curl 8.13.0, the `CURLOPT_RESOLVE` option now
supports replacing IPv6 hosts. This allows us to navigate using the IPv6
address directly. Previously, you would see "an unexpected network
error occurred" message when attempting to do so.

Fixes #3596

### CODE REVIEW

File: Services/RequestServer/ConnectionFromClient.cpp [hunk 1]
```diff
@@ -487,7 +487,7 @@ void ConnectionFromClient::start_request(i32 request_id, ByteString method, URL:
             set_option(CURLOPT_HEADERFUNCTION, &on_header_received);
             set_option(CURLOPT_HEADERDATA, reinterpret_cast<void*>(request.ptr()));
 
-            auto formatted_address = build_curl_resolve_list(*dns_result, host, url.port_or_default());
+            auto formatted_address = build_curl_resolve_list(*dns_result, url.serialized_host(), url.port_or_default());
```
Comment (trflynn89) [inline Services/RequestServer/ConnectionFromClient.cpp:490]: `host` isn't used for anything else, so let's just not remove the square brackets above?

Comment (trflynn89) [reply Services/RequestServer/ConnectionFromClient.cpp:490]: ah wait, nevermind, we use it for `lookup`. In that case, if `lookup` needs the augmented host, let's just store a copy of the host before mutation instead of having to re-serialize it here?

Comment (alimpfard) [reply Services/RequestServer/ConnectionFromClient.cpp:490]: It should be used in the DNS resolve call, no?

Comment (rmg-x) [reply Services/RequestServer/ConnectionFromClient.cpp:490]: I think it should be OK to add support for square brackets in `IPv6Address:from_string` given https://datatracker.ietf.org/doc/html/rfc5952#section-6

> This style is NOT RECOMMENDED because of its
   ambiguity.  The [] style as expressed in [RFC3986] SHOULD be
   employed, and is the default unless otherwise specified.  Other
   styles are acceptable when there is exactly one style for the given
   context and cross-platform portability does not become an issue.  For
   URIs containing IPv6 address literals, [RFC3986] MUST be followed, as
   well as the rules defined in this document.

That way, the resolver doesn't need a stripped down version.

File: AK/IPv6Address.h [hunk 2]
```diff
@@ -111,7 +111,14 @@ class [[gnu::packed]] IPv6Address {
         if (string.is_null())
             return {};
 
-        auto const parts = string.split_view(':', SplitBehavior::KeepEmpty);
+        // NOTE: This supports URI syntax (square brackets) for IPv6 addresses.
+        //       See: https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2
+        if ((string.starts_with('[') && !string.ends_with(']')) || (string.ends_with(']') && !string.starts_with('[')))
+            return {};
+
+        auto const value_to_parse = string.replace("["sv, ""sv, ReplaceMode::FirstOnly).replace("]"sv, ""sv, ReplaceMode::FirstOnly);
```
Comment (trflynn89) [inline AK/IPv6Address.h:119]: Bit of needless allocations here, we can just substring the input string. Something like:
```c++
auto starts_with_bracket = string.starts_with('[');
auto ends_with_bracket = string.ends_with(']');

if (starts_with_bracket || ends_with_bracket) {
    if (!starts_with_bracket || !ends_with_bracket)
        return {};

    string = string.substring_view(1, string.length() - 2);
}
```

**Review by alimpfard — APPROVED** [review]
