### PR TITLE
LibWeb: Parse fill and stroke values

### LINKED ISSUE #776: MDN canvas example lacks color
The [tutorial for basic canvas usage](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_usage) has a sample that is rendered incorrectly. It lacks all color! The squares should be red and a transparent blue, but we're getting only black.

Tracked things down to `CanvasFillStrokeStyles.h:31` which has a FIXME and some debug info.

```
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8" />
    <title>Canvas experiment</title>
  </head>
  <body>
    <canvas id="canvas" width="150" height="150"></canvas>
    <script type="application/javascript">
      function draw() {
        const canvas = document.getElementById("canvas");
        if (canvas.getContext) {
          const ctx = canvas.getContext("2d");

          ctx.fillStyle = "rgb(200 0 0)";
          ctx.fillRect(10, 10, 50, 50);

          ctx.fillStyle = "rgb(0 0 200 / 50%)";
          ctx.fillRect(30, 30, 50, 50);
        }
      }
      draw();
    </script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by doctortheemh**
Use the CSS color data type using the CSS parser. Taking a first stab at this, would appreciate any insights or suggestions! I also believe it would be nice to add a test for this, if someone could point me in the best way to do that, I'll write that up. Looks like there is a slight progression on an existing test as well.

Resolves #776.

### CODE REVIEW

File: Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h [hunk 1]
```diff
@@ -23,17 +24,23 @@ class CanvasFillStrokeStyles {
...
-                    dbgln_if(CANVAS_RENDERING_CONTEXT_2D_DEBUG, "CanvasFillStrokeStyles: Unsupported canvas fill or stroke style \"{}\". Defaulting to Color::Black.", string);
+                auto maybe_parser = CSS::Parser::Parser::create(CSS::Parser::ParsingContext(realm), string);
+                if (maybe_parser.is_error())
+                    return default_color;
+                auto parser = maybe_parser.release_value();
 
-                return color.value_or(Color::Black);
+                auto style_value = parser.parse_as_css_value(CSS::PropertyID::Color);
+                if (style_value && style_value->is_color())
+                    return style_value->to_color(OptionalNone());
```
[the remark this answers is not in the document]
Comment (doctortheemh) [reply Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h]: I'll make this change, thanks. I'll also followup on Discord to see if I can help clean up the API.

**Comment by doctortheemh** [comment]
The failing test is LibWeb, which looks like a legit issue but perhaps unrelated. How do we capture the crash from the sanitizer and analyze? Should we create a new issue? Is there a way to retrigger CI?

**Comment by AtkinsSJ** [comment]
> The failing test is LibWeb, which looks like a legit issue but perhaps unrelated.
Yup, I actually see two failures there but neither is related to this PR.

> How do we capture the crash from the sanitizer and analyze?
I don't think you can, but someone else might know.

> Should we create a new issue?
Maybe? I posted the failures on Discord, that's usually enough.

> Is there a way to retrigger CI?
Yes, either a maintainer can re-run it, or any git push will re-run it. (So, you can `git commit --amend` without making any changes, then force push.) But we don't worry about having all :heavy_check_mark:s if the tests have all run and the failures are unrelated.

File: Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h [hunk 2]
```diff
@@ -23,17 +24,25 @@ class CanvasFillStrokeStyles {
...
+                }
+                auto parser = maybe_parser.release_value();
 
-                return color.value_or(Color::Black);
+                auto style_value = parser.parse_as_css_value(CSS::PropertyID::Color);
+                if (style_value && style_value->has_color())
+                    return style_value->to_color(OptionalNone());
+
+                dbgln_if(CANVAS_RENDERING_CONTEXT_2D_DEBUG, "CanvasFillStrokeStyles: Unsupported canvas fill or stroke style \"{}\". Defaulting to Color::Black.", string);
+                return default_color;
```
Comment (AtkinsSJ) [inline Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h:45]: A couple of general points:
- `fillStyle` and `strokeStyle`'s setters have spec algorithms [here](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-fillstyle) which we should follow. (In the "Copy out the steps as comments and then write the code that does each step" style.) It's slightly awkward having one function for both but they do the same thing so it should be fine.
- Specifically, one of those spec steps refers to using ["parse a CSS color value"](https://drafts.csswg.org/css-color/#parse-a-css-color-value) to do the parsing. We don't have that yet, but if you can add a FIXME comment about it that'd be handy.
- That spec algorithm also just returns without doing anything if the string was invalid. That's a bit tricky to do here, so it might be worth getting rid of this `to_canvas_state_fill_or_stroke_style()` function and just implementing the same steps in `set_fill_style()` and `set_stroke_style()`.
-  `CSS::Parser::Parser::create()` returning an `ErrorOr` is a bit of a relic from when we tried to handle all OOM errors, and it's not something we actually need to worry about here. I've made a note to make it not do that.

Comment (doctortheemh) [reply Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h]: I implemented this in the style of copying the spec, splitting it out into the two functions as you say. I also added the two FIXMEs.

**Comment by doctortheemh** [comment]
This is another apparent progression in one of the tests, but it's also hiding a bug. We cannot parse the `calc(infinity)` part of the color yet in the last sample, but the spec now says if parsing fails to bail out and do nothing, whereas before, we explicitly returned Black.

File: Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h [hunk 3]
```diff
@@ -23,27 +24,45 @@ class CanvasFillStrokeStyles {
...
-                if (!color.has_value())
-                    dbgln_if(CANVAS_RENDERING_CONTEXT_2D_DEBUG, "CanvasFillStrokeStyles: Unsupported canvas fill or stroke style \"{}\". Defaulting to Color::Black.", string);
+        auto& realm = static_cast<IncludingClass&>(*this).realm();
 
-                return color.value_or(Color::Black);
+        // https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-fillstyle
+        style.visit(
+            [&](String const& string) {
+                // 1. If the given value is a string, then:
+                // 1. Let context be this's canvas attribute's value, if that is an element; otherwise null.
```
Comment (AtkinsSJ) [inline Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h:35]: Having steps 1 and 1.1 at the same level is a bit confusing, maybe move the first one above the lambda?

File: Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h [hunk 4]
```diff
@@ -53,8 +72,44 @@ class CanvasFillStrokeStyles {
...
     {
-        // FIXME: 2. If the given value is a CanvasPattern object that is marked as not origin-clean, then set this's origin-clean flag to false.
-        my_drawing_state().stroke_style = to_canvas_state_fill_or_stroke_style(style);
+        auto& realm = static_cast<IncludingClass&>(*this).realm();
+
+        // https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-strokestyle
+
+        style.visit(
+            [&](String const& string) {
+                // 1. If the given value is a string, then:
```
Comment (AtkinsSJ) [inline Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h:81]: Same

**Review by AtkinsSJ — CHANGES_REQUESTED** [review]
> This is another apparent progression in one of the tests, but it's also hiding a bug. We cannot parse the calc(infinity) part of the color yet in the last sample, but the spec now says if parsing fails to bail out and do nothing, whereas before, we explicitly returned Black.

Yeah that's no good. If the tests used a different color for each step, that would work, because that would show up. Otherwise... we could reset it to black, but that uses the same parsing code so could be buggy. I think using different colors is the better option.

File: Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h (hunk 2 above)
Comment (AtkinsSJ) [reply Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h]: Thanks! Please click the `[Resolve conversation]` button on feedback like this once you've pushed a fix. :^)

File: Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h (hunk 3 above)
Comment (doctortheemh) [reply Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h:35]: Good idea!

**Comment by doctortheemh** [comment]
> > This is another apparent progression in one of the tests, but it's also hiding a bug. We cannot parse the calc(infinity) part of the color yet in the last sample, but the spec now says if parsing fails to bail out and do nothing, whereas before, we explicitly returned Black.
> 
> Yeah that's no good. If the tests used a different color for each step, that would work, because that would show up. Otherwise... we could reset it to black, but that uses the same parsing code so could be buggy. I think using different colors is the better option.

I'll try to re-implement the test with different colors to avoid that confusion.

**Review by AtkinsSJ — APPROVED** [review]
Great!
