### PR TITLE
LibWeb: Check for missing node or invalid query in obtain_theme_color

### LINKED ISSUE #3205: Ladybird crashes on https://github.com
On loading github.com, ladybird crashes with:

```
ASSERTION FAILED: m_ptr at /home/shannon/personal/ladybird/Libraries/LibGC/Ptr.h:174
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-ak.so.0(ak_trap+0x35) [0x7f2e7bda81a5]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-ak.so.0(+0x1556f) [0x7f2e7bda856f]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0(+0x8e1d88) [0x7f2e7d03dd88]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0(+0x8e1ade) [0x7f2e7d03dade]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0(+0x8e1ade) [0x7f2e7d03dade]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::DOM::Document::obtain_theme_color() 0x4e) [0x7f2e7d027d5e]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::HTML::HTMLMetaElement::update_metadata(AK::Optional<AK::String> const&) 0x46) [0x7f2e7d1f0346]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::HTML::HTMLMetaElement::inserted() 0x38) [0x7f2e7d1f0438]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0(+0x9342fe) [0x7f2e7d0902fe]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::DOM::Node::insert_before(GC::Ref<Web::DOM::Node>, GC::Ptr<Web::DOM::Node>, bool) 0x8b6) [0x7f2e7d08f6f6]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::HTML::HTMLParser::insert_an_element_at_the_adjusted_insertion_location(GC::Ref<Web::DOM::Element>) 0x107) [0x7f2e7d25ea07]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::HTML::HTMLParser::insert_html_element(Web::HTML::HTMLToken const&) 0x5d) [0x7f2e7d25eccd]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::HTML::HTMLParser::handle_in_head(Web::HTML::HTMLToken&) 0x1c1) [0x7f2e7d256b01]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::HTML::HTMLParser::run(Web::HTML::HTMLTokenizer::StopAtInsertionPoint) 0x34e) [0x7f2e7d25429e]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0 Web::HTML::HTMLParser::run(URL::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) 0x119) [0x7f2e7d255499]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0(+0x8f74f3) [0x7f2e7d0534f3]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-web.so.0(+0xcb7221) [0x7f2e7d413221]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-core.so.0 Core::ThreadEventQueue::process() 0x20a) [0x7f2e7bf44d8a]
/home/shannon/personal/ladybird/Build/debug/lib/liblagom-webview.so.0 WebView::EventLoopManagerQt::event_target_received_event(AK::Badge<WebView::EventLoopImplementationQtEventTarget>, QEvent*) 0x2f) [0x7f2e7e62aa7f]
```

### PR DESCRIPTION
**Pull request by Gingeh**
Fixes #3205.

### CODE REVIEW

File: Libraries/LibWeb/DOM/Document.cpp [hunk 1]
```diff
@@ -1490,7 +1490,7 @@ void Document::obtain_theme_color()
             auto media = element.attribute(HTML::AttributeNames::media);
             if (media.has_value()) {
                 auto query = parse_media_query(context, media.value());
-                if (window() && !query->evaluate(*window()))
+                if (query.is_null() || (window() && !query->evaluate(*window())))
```
Comment (tcl3) [inline Libraries/LibWeb/DOM/Document.cpp:1493]: Should we be continuing here if `window()` is null? I would have thought we'd want something like: `if (!(query && window() && query->evaluate(*window())))` here.

**Review by tcl3 — COMMENTED** [review]
Is there some kind of minimal in-tree test you could add for this? I can't reproduce the original crash.

File: Libraries/LibWeb/DOM/Document.cpp (hunk 1 above)
Comment (Gingeh) [reply Libraries/LibWeb/DOM/Document.cpp:1493]: That would make more sense, I kept the `window && !evaluate` because that's what the initial implementation did.

**Comment by Gingeh** [comment]
> Is there some kind of minimal in-tree test you could add for this? I can't reproduce the original crash.

Done, note that the crash only occurs in debug builds because it's hitting an `ASSERT(m_ptr)`

**Comment by shannonbooth** [comment]
> > Is there some kind of minimal in-tree test you could add for this? I can't reproduce the original crash.
> 
> Done, note that the crash only occurs in debug builds because it's hitting an `ASSERT(m_ptr)`

Oh right, yeah I only ever compile with debug, I find the assertion in GC::Ptr too useful to not have it

**Review by tcl3 — APPROVED** [review]
