### PR TITLE
LibGfx: Fix inverted color channels in ICO-embedded BMP images

### LINKED ISSUE #4435: Inverted Favicon Colours On Some Websites Using "image/x-icon" Favicons
### Summary

Currently, on some websites that use an "image/x-icon" the colours are inverted. One example would be this frontend [yt2009](https://github.com/ftde0/yt2009) and the demo site below. 

The example favicon is in "image/x-icon".

This zip should have the favicon, and a simple HTML page to show the issue. 

[example_site.zip](https://github.com/user-attachments/files/19860809/example_site.zip)

(.ico ffprobe log)
[favicon_ffprobe.txt](https://github.com/user-attachments/files/19860943/favicon_ffprobe.txt)

### Operating system

Linux

### Steps to reproduce

1. Go to either a yt2009 instance or https://theworldofnick.neocities.org/ladybird-favicon-bug/
2. That's it!

### Expected behavior

The favicon is meant to be red, like here.

Image

### Actual behavior

The colours are inverted here.

Image

### URL for a reduced test case

https://theworldofnick.neocities.org/ladybird-favicon-bug/

### HTML/SVG/etc. source for a reduced test case

```html
<!DOCTYPE html>
<html>
<head>
  <title>LadyBird Inverted Colours For Favicon On Some Sites</title>
  <link rel="icon" href="/favicon.ico">
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"
</head>
<body>

	<p> So this favicon seems to have inverted colours</p>

	<p> This page should have the favicon, I had to use the built in php -S server to see it here
        since I have no idea how paths work besides hrefs lol.<p>

	<p> Most other sites seem unaffected.</p>

	<p> The issue is really on this project <a href="https://github.com/ftde0/yt2009">yt2009</a> which a custom frontend
	for YouTube that uses real archives and such (doesn't matter much).</p>

	<p>On the top (FireFox) it is Red, on the bottom it is Blue</p>

	<image src="example.webp"></image>

	<image src="favicon.ico"></image>

</body>
</html>
```

### Log output and (if possible) backtrace

```shell
Ladybird PID file '/run/user/1000/Ladybird.pid' exists with PID 11472, but process cannot be found
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: upgrade-insecure-requests
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: default-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: connect-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: form-action
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: img-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: script-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: style-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: font-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: object-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: media-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: frame-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: worker-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: upgrade-insecure-requests
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: default-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: connect-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: form-action
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: img-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: script-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: style-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: font-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: object-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: media-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: frame-src
3803.856 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: worker-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: upgrade-insecure-requests
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: default-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: connect-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: form-action
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: img-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: script-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: style-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: font-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: object-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: media-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: frame-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: worker-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: upgrade-insecure-requests
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: default-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: connect-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: form-action
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: img-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: script-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: style-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: font-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: object-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: media-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: frame-src
3803.861 WebContent(11899): Potential FIXME: Creating unknown Content Security Policy directive: worker-src
```

### Screenshots or screen recordings

Image

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by aplefull**
When decoding 24-bit BMPs embedded in ICO files, colors were incorrectly displayed because we assumed RGBx8888 format. But 24-bit ICO-embedded BMPs use BGRA8888 format. We already had a note about this:
https://github.com/LadybirdBrowser/ladybird/blob/5d486528906ee1d0b56a084d506baf788f6a186a/Libraries/LibGfx/ImageFormats/BMPLoader.cpp#L1245-L1249

So now we properly handle such images. Fixes #4435.

### CODE REVIEW

File: Libraries/LibGfx/ImageFormats/BMPLoader.cpp [hunk 1]
```diff
@@ -1383,7 +1383,14 @@ static ErrorOr<void> decode_bmp_pixel_data(BMPLoadingContext& context)
                 u8 g = (pixel & 0x00FF00) >> 8;
                 u8 r = (pixel & 0x0000FF);
 
-                u32 rgbx_pixel = (r << 16) | (g << 8) | b;
+                u32 rgbx_pixel;
+                // 24bit ICO files use BGRA8888 format
+                if (context.is_included_in_ico) {
+                    rgbx_pixel = (b << 16) | (g << 8) | r | 0xFF000000;
```
Comment (AtkinsSJ) [inline Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1389]: Am I understanding right that if `is_included_in_ico`, that `b` isn't actually the blue channel, etc? (Because we're reading BGRA, not writing it.)

If so then it'd be clearer to assign `b`, `g` and `r` to the correct parts of the color data instead.

**Review by AtkinsSJ — APPROVED** [review]
