### PR TITLE
LibWeb: Add case when <br> has display other than 'none'

### LINKED ISSUE #5568: LibWeb: Crash when `br` has `display` set to `table-cell` or `table-caption`
### Summary

Description is in the title :) 

### Operating system

Linux

### Steps to reproduce

See reduced example.

### Expected behavior

N/A

### Actual behavior

N/A

### URL for a reduced test case

data:text/html;base64,PGJyIHN0eWxlPSJkaXNwbGF5OiB0YWJsZS1jZWxsOyI+DQo8YnIgc3R5bGU9ImRpc3BsYXk6IHRhYmxlLWNhcHRpb247Ij4=

### HTML/SVG/etc. source for a reduced test case

```html
<br style="display: table-cell;">
<br style="display: table-caption;">
```

### Log output and (if possible) backtrace

```shell
Thread 1 "WebContent" received signal SIGSEGV, Segmentation fault.
AK::HashTable<AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::Entry, AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::EntryTraits, false>::lookup_with_hash<AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::find(Web::CSSPixels const&)::{lambda(auto:1&)#1}>(unsigned int, AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::find(Web::CSSPixels const&)::{lambda(auto:1&)#1}) const () at /home/aplefull/Repos/ladybird/AK/HashTable.h:570
570	            if (bucket->state == BucketState::Free)
(gdb) bt
#0  AK::HashTable<AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::Entry, AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::EntryTraits, false>::lookup_with_hash<AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::find(Web::CSSPixels const&)::{lambda(auto:1&)#1}>(unsigned int, AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::find(Web::CSSPixels const&)::{lambda(auto:1&)#1}) const () at /home/aplefull/Repos/ladybird/AK/HashTable.h:570
#1  AK::HashTable<AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::Entry, AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::EntryTraits, false>::find<AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::find(Web::CSSPixels const&)::{lambda(auto:1&)#1}>(unsigned int, AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::find(Web::CSSPixels const&)::{lambda(auto:1&)#1}) ()
    at /home/aplefull/Repos/ladybird/AK/HashTable.h:376
#2  AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::find ()
    at /home/aplefull/Repos/ladybird/AK/HashMap.h:106
--Type <RET> for more, q to quit, c to continue without paging--c
#3  AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::find ()
    at /home/aplefull/Repos/ladybird/AK/HashMap.h:102
#4  AK::HashMap<Web::CSSPixels, AK::Optional<Web::CSSPixels>, AK::Traits<Web::CSSPixels>, AK::Traits<AK::Optional<Web::CSSPixels> >, false>::ensure ()
    at /home/aplefull/Repos/ladybird/AK/HashMap.h:255
#5  0x0000775fa1b4812e in Web::Layout::FormattingContext::calculate_min_content_height ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/FormattingContext.cpp:1524
#6  0x0000775fa1b9a049 in Web::Layout::TableFormattingContext::compute_cell_measures ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/TableFormattingContext.cpp:126
#7  0x0000775fa1b9e737 in Web::Layout::TableFormattingContext::run_until_width_calculation ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/TableFormattingContext.cpp:1601
#8  0x0000775fa1b4d16b in Web::Layout::FormattingContext::compute_table_box_width_inside_table_wrapper ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/FormattingContext.cpp:449
#9  0x0000775fa1b2d6bb in operator() ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:298
#10 Web::Layout::BlockFormattingContext::compute_width ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:302
#11 0x0000775fa1b3085b in Web::Layout::BlockFormattingContext::layout_block_level_box ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:741
#12 0x0000775fa1b31921 in operator() ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:851
#13 for_each_child_of_type<Web::Layout::Box, Web::Layout::BlockFormattingContext::layout_block_level_children(const Web::Layout::BlockContainer&, const Web::Layout::AvailableSpace&)::<lambda(Web::Layout::Box&)> > ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/TreeNode.h:312
#14 for_each_child_of_type<Web::Layout::Box, Web::Layout::BlockFormattingContext::layout_block_level_children(const Web::Layout::BlockContainer&, const Web::Layout::AvailableSpace&)::<lambda(Web::Layout::Box&)> > ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/TreeNode.h:321
#15 Web::Layout::BlockFormattingContext::layout_block_level_children ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:850
#16 0x0000775fa1b3118d in Web::Layout::BlockFormattingContext::layout_block_level_box ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:809
#17 0x0000775fa1b31921 in operator() ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:851
#18 for_each_child_of_type<Web::Layout::Box, Web::Layout::BlockFormattingContext::layout_block_level_children(const Web::Layout::BlockContainer&, const Web::Layout::AvailableSpace&)::<lambda(Web::Layout::Box&)> > ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/TreeNode.h:312
#19 for_each_child_of_type<Web::Layout::Box, Web::Layout::BlockFormattingContext::layout_block_level_children(const Web::Layout::BlockContainer&, const Web::Layout::AvailableSpace&)::<lambda(Web::Layout::Box&)> > ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/TreeNode.h:321
#20 Web::Layout::BlockFormattingContext::layout_block_level_children ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:850
#21 0x0000775fa1b31caf in Web::Layout::BlockFormattingContext::run ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:82
#22 0x0000775fa1b30a6b in Web::Layout::BlockFormattingContext::layout_block_level_box ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:790
#23 0x0000775fa1b31921 in operator() ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:851
#24 for_each_child_of_type<Web::Layout::Box, Web::Layout::BlockFormattingContext::layout_block_level_children(const Web::Layout::BlockContainer&, const Web::Layout::AvailableSpace&)::<lambda(Web::Layout::Box&)> > ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/TreeNode.h:312
#25 for_each_child_of_type<Web::Layout::Box, Web::Layout::BlockFormattingContext::layout_block_level_children(const Web::Layout::BlockContainer&, const Web::Layout::AvailableSpace&)::<lambda(Web::Layout::Box&)> > ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/TreeNode.h:321
#26 Web::Layout::BlockFormattingContext::layout_block_level_children ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Layout/BlockFormattingContext.cpp:850
#27 0x0000775fa16b0e08 in Web::DOM::Document::update_layout ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/DOM/Document.cpp:1381
#28 0x0000775fa18aa882 in Web::HTML::EventLoop::update_the_rendering ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:405
#29 0x0000775fa18ac809 in AK::Function<void ()>::operator()() const ()
    at /home/aplefull/Repos/ladybird/AK/Function.h:148
#30 Web::HTML::Task::execute ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/HTML/EventLoop/Task.cpp:47
#31 0x0000775fa18ab51d in Web::HTML::EventLoop::process ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:182
#32 0x0000775fa1c5cc5a in AK::Function<void ()>::operator()() const ()
    at /home/aplefull/Repos/ladybird/AK/Function.h:148
#33 operator() ()
    at /home/aplefull/Repos/ladybird/Libraries/LibWeb/Platform/TimerSerenity.cpp:24
#34 call () at /home/aplefull/Repos/ladybird/AK/Function.h:225
#35 0x0000775f9ffe4949 in AK::Function<void ()>::operator()() const ()
    at /home/aplefull/Repos/ladybird/AK/Function.h:148
#36 Core::Timer::timer_event ()
    at /home/aplefull/Repos/ladybird/Libraries/LibCore/Timer.cpp:97
#37 0x0000775f9ffd36ac in Core::EventReceiver::dispatch_event ()
    at /home/aplefull/Repos/ladybird/Libraries/LibCore/EventReceiver.cpp:158
#38 0x0000775f9ffe41af in Core::ThreadEventQueue::process ()
    at /home/aplefull/Repos/ladybird/Libraries/LibCore/ThreadEventQueue.cpp:121
#39 0x0000775f9ffee34c in Core::EventLoopImplementationUnix::pump ()
    at /home/aplefull/Repos/ladybird/Libraries/LibCore/EventLoopImplementationUnix.cpp:316
#40 Core::EventLoopImplementationUnix::exec ()
    at /home/aplefull/Repos/ladybird/Libraries/LibCore/EventLoopImplementationUnix.cpp:308
#41 0x0000775f9ffd2697 in Core::EventLoop::exec ()
    at /home/aplefull/Repos/ladybird/Libraries/LibCore/EventLoop.cpp:90
#42 0x000062d963662bee in ladybird_main ()
    at /home/aplefull/Repos/ladybird/Services/WebContent/main.cpp:228
#43 0x000062d963758f82 in main ()
    at /home/aplefull/Repos/ladybird/Libraries/LibMain/Main.cpp:43
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by Guizas14**
In the previous code there was no condition verifying if a <br> element had its display style set to something other than none, which caused the thread to crash in those cases (specially when display was set to table-cell or table-caption, as reported in the issue). Add a condition to ensure that in those cases, <br> elements are always treated as an inline box, preventing program from crashing.
Created  a test file called br-display-set-to-table-should-not-crash.html which tests both cases reported on this issue.
Fixes #5568

### CODE REVIEW

File: Libraries/LibWeb/HTML/HTMLBRElement.cpp [hunk 1]
```diff
@@ -64,6 +64,8 @@ void HTMLBRElement::adjust_computed_style(CSS::ComputedProperties& style)
     // https://drafts.csswg.org/css-display-3/#unbox
     if (style.display().is_contents())
         style.set_property(CSS::PropertyID::Display, CSS::DisplayStyleValue::create(CSS::Display::from_short(CSS::Display::Short::None)));
+    else if (!style.display().is_none())
+        style.set_property(CSS::PropertyID::Display, CSS::DisplayStyleValue::create(CSS::Display::from_short(CSS::Display::Short::Inline)));
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/HTML/HTMLBRElement.cpp:69]: This could do with a comment. The spec linked above explains why we replace `display: contents` with `display: none`, but replacing other `display` values is a bit ad-hoc. Something like:
```c++
// AD-HOC: Prevent other display values from applying, so that we always create a BreakNode
```

File: Tests/LibWeb/Crash/HTML/br-display-set-to-table-should-not-crash.html [hunk 2]
```diff
@@ -0,0 +1,7 @@
+<!DOCTYPE html>
```
Comment (AtkinsSJ) [inline Tests/LibWeb/Crash/HTML/br-display-set-to-table-should-not-crash.html:1]: If this test only cares about whether this crashes or not, you can make it a crash test: put it in `Tests/LibWeb/Crash` instead. It doesn't need the .txt file in that case.

**Comment by Guizas14** [comment]
Thank you for the feedback! I've added a comment and moved the test file to Tests/LibWeb/Crash as suggested.
