### PR TITLE
LibCore: MimeType for text/plain has base names with lines folded

### LINKED ISSUE #4859: LibCore: MimeType for text/plain has base names with lines folded
Most likely a very minor issue and maybe only really impacting Serenity OS, but was highlighted when I used static checker cppcheck 2.13.0 on ladybird code base.  I was checking the Libraries at the time and gave this output

```
LibCore/MimeData.cpp:64:15: error: There is an unknown macro here somewhere. Configuration is required. If sv is a macro then please configure it. [unknownMacro]
    ".shellrc"sv
              ^
```

Seems cppcheck is confused by the sv StringView suffix.  This kind of cppcheck "error" even blocks cppcheck from doing deeper verifications.  Anyway...

MimeType.cpp looks like this:

```
60     ".txt"sv,
61
62     // Base names
63     ".history"sv,
64     ".shellrc"sv
65     "CMakeLists.txt"sv,
66 };
```

Looked at line 64 and realized that a comma was missing at line end, causing the ".shellrc" and "CMakeLists.txt" strings to be folded together as ".shellrcCMakeLists.txt". It should be...

`64     ".shellrc"sv,`

with the comma at end of line.

I ran some manual file:// tests with ladybird, with and without the fix and noticed that CMakeLists.txt was always shown as expected in the browser, but .shellrc would fail to be shown until the fix was in.  So then it was obvious that any file with .txt extension will always work as that extension is already up higher on line 60.  So we can remove the CMakeLists.txt entry from the base names too, as it is unnecessary.

I wrote some tests to check the text/plain MimeType and a few others. Hope the tests are ok.

I have a small commit ready to correct this.

This is my first commit for ladybird! Enjoying getting familiar with ladybird and C++20. Hope this report is ok?!

Regards,

### PR DESCRIPTION
**Pull request by rcorsi**
Fix and tests for text/plain issue on .shellrc and CMakeList.txt lines folded in LibCore/MimeType.cpp

fixes #4859

### CODE REVIEW

File: Tests/LibCore/TestLibCoreMimeType.cpp [hunk 1]
```diff
@@ -0,0 +1,41 @@
+/*
+ * Copyright (c) 2025, Andreas Kling <andreas@ladybird.org>
```
Comment (ADKaster) [inline Tests/LibCore/TestLibCoreMimeType.cpp:2]: Andreas didn't write this test, you did :)

Feel free to put your name+email. Other contributors have opted to use a more generic "the Ladybird Developers" copyright line.

File: Tests/LibCore/TestLibCoreMimeType.h [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+ * Copyright (c) 2025, Andreas Kling <andreas@ladybird.org>
+ *
+ * SPDX-License-Identifier: BSD-2-Clause
+ */
+
+#pragma once
+
+#include <AK/Vector.h>
+
+void check_filename_mimetype(AK::Vector<StringView>const&, StringView const&);
```
Comment (ADKaster) [inline Tests/LibCore/TestLibCoreMimeType.h:11]: A header file for the test is not necessary. Make the helper function file-static instead.

File: Tests/LibCore/TestLibCoreMimeType.cpp [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+    for (auto const& filename : filepaths)
+    {
+        dbgln(filename, "\n");
+        auto const& guessed_mime_type = Core::guess_mime_type_based_on_filename(filename);
+        EXPECT_EQ(guessed_mime_type, expected_mimeType);
+    }
+}
+
+auto text_plain_filenames = Vector {"main.c"sv, "hello.txt"sv, ".history"sv, ".shellrc"sv, "CMakeList.txt"sv,};
+//FIXME: fails because .xht extension is in MimeType text/html and application/xhtml+xml
```
Comment (ADKaster) [inline Tests/LibCore/TestLibCoreMimeType.cpp:24]: It's kind of hard to find an authoritative reference for .xht files' preferred essence. But surely application/xhtml+xml is much more correct than text/html. A patch to fix up this duplication would be a good follow-up.

**Comment by rcorsi** [comment]
linter found that I had a blank line at end of TestLibCoreMimeType.cpp, removed it and pushed

File: Tests/LibCore/TestLibCoreMimeType.cpp [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+ * SPDX-License-Identifier: BSD-2-Clause
+ */
+
+#include "TestLibCoreMimeType.h"
+#include <AK/Vector.h>
+#include <LibCore/MimeData.h>
+#include <LibTest/TestCase.h>
+
+
+void check_filename_mimetype(AK::Vector<StringView> const& filepaths, StringView const& expected_mimeType)
```
Comment (ADKaster) [inline Tests/LibCore/TestLibCoreMimeType.cpp:13]: casing on the second parameter here is a bit off. `expected_mime_type` is more in line with project style.


No need to pass StringView by const ref, it's the size of two pointers (well, pointer + size).

Prefixing Vector with AK is not necessary or in-line with style either.

**Review by ADKaster — COMMENTED** [review]
Thanks for the patch! That kind of missing comma sure is insidious.

I saw you opened an issue for this. In general, we don't require or encourage PRs to have a matching issue. Just opening a PR is suitable. If you don't know how to fix an issue right away, that's when you should reach for the issue tracker to get feedback from the  community. However, now that it's open, you should link the two. In GitHub's PR flow, a comment with `fixes #NNNN` or `resolves #NNN` will do the right thing, and auto-close the issue when the PR is merged.

You don't need to reference the issue in the commit message either, it honestly is a bit more clutter than we normally have. Take a look at the commit history to get a sense of the sorts of commit messages we like to use.

Given the triviality of the fix compared to the test you added, it would be reasonable to add the test in its own, second commit. Keep in mind that we use a rebase workflow where commits from PRs are cherry-picked directly onto master. Fixups and review feedback should be amended and force-pushed rather than stacked.

File: Tests/LibCore/TestLibCoreMimeType.cpp (hunk 4 above)
Comment (rcorsi) [reply Tests/LibCore/TestLibCoreMimeType.cpp:13]: Sounds good. I'll fix those.

**Comment by rcorsi** [comment]
Fixes #4859

**Comment by rcorsi** [comment]
I see another issue #4860 created!  Did I do something wrong?!?

**Comment by rcorsi** [comment]
> 4860 is this pull request. Issues and pull requests are essentially the same thing in GitHub's backend, just with a different "type". Confusing and counterintuitive, but it's always been that way.

Ok, got it!

**Comment by ADKaster** [comment]
@rcorsi the final state of your PR looks reasonable. However like I mentioned, our PR merge workflow ends up cherry-picking PR commits directly onto master. That means all commits in the PR branch, without squashing. Please fixup-squash all your edits from code review into the relevant commits that first added the changes, per CONTRIBUTING.md.

If you're not sure how to hold git that way, this video has been helpful for contributors in the past: https://discord.com/channels/@me/855590734839939102/1232060991420760142

**Comment by rcorsi** [comment]
> @rcorsi the final state of your PR looks reasonable. However like I mentioned, our PR merge workflow ends up cherry-picking PR commits directly onto master. That means all commits in the PR branch, without squashing. Please fixup-squash all your edits from code review into the relevant commits that first added the changes and force-push to your branch, per CONTRIBUTING.md.

@ADKaster I struggled some, but I think managed to get the squashing done somehow.  I made a little mess in the commit history, triggering the ladybird-bot and had to fix it.  Hopefully it is all good now!?!?

**Comment by rcorsi** [comment]
@ADKaster Thank you for merging, and breaking up the commits into two commits (code and tests).  I would have done that, but I misunderstood your comment about that (thought it was so small it was not required, but it was).  Will know for next time.

I will push a new PR for the .xht file extension as mimetype application/xhtml+xml and also text/html
