### PR TITLE
LibWeb: Implement `ReadableStream`, `WritableStream` and `TransformStream` transfer

### LINKED ISSUE #3294: TypeError when processing data through DecompressionStream: Unable to decompress chunk
### Summary

Reduction comes from [0x40.mon.im](https://0x40.mon.im/custom.html?packs=HADES.zip) (photosensitive epilepsy warning!).

This website loads assets in a zip archive and uses decompression streams to unpack it. In Ladybird it results in a   
`[TypeError] Unable to decompress chunk: Reached end-of-stream without collecting the required number of bits` and prevents from loading songs there. 

### Operating system

Linux

### Steps to reproduce

Run reduced example.

### Expected behavior

No errors, readable should be locked by the end of code execution.

### Actual behavior

Errors, readable is unlocked.

### URL for a reduced test case

N/A

### HTML/SVG/etc. source for a reduced test case

```html
<!DOCTYPE html>
<body>
  <script defer>
    const main = async () => {
      const zipData =
        "data:@file/zip;base64,UEsDBBQAAAAIAF0px0TfyjcygwAAALQAAAAIAAAAaW5mby54bWxNjj0OwjAMhWeQuIMvQN2BCVmR2FjYeoFQ0iaiiaPGlXp8ErN0s/y+90MhTWwu5xMlG515bq7AK+zwIGwPVewmnlczeAf9futBocHZSPiXlPq4Mq4hS+B0iIErWIj14gkKp7kQHkA1LiF9jRfJd8SW76u5ey88l8zSjVxrGlJZQl37A1BLAQI/ABQAAAAIAF0px0TfyjcygwAAALQAAAAIACQAAAAAAAAAIAAAAAAAAABpbmZvLnhtbAoAIAAAAAAAAQAYAEBZsAu7gc8Bfo4xT8Ou2AG2ON55fKvPAVBLBQYAAAAAAQABAFoAAACpAAAAAAA=";
      const dataBlob = await fetch(zipData).then((response) => response.blob());

      const workerScript = document.querySelector(
        "script[type='worker']",
      ).textContent;

      const script = URL.createObjectURL(
        new Blob([workerScript], { type: "text/javascript" }),
      );

      const readable = new ReadableStream({
        start() {
          this.chunkOffset = 0;
        },
        async pull(controller) {
          const { size } = readable;
          const { chunkOffset } = this;
          const chunkSize = 524288;

          let arrayBuffer = await dataBlob.arrayBuffer();
          controller.enqueue(new Uint8Array(arrayBuffer));

          if (chunkOffset + chunkSize > size) {
            controller.close();
          } else {
            this.chunkOffset += chunkSize;
          }
        },
      });

      async function onMessage({ data }, workerData) {
        const { type, messageId } = data;
        const { worker } = workerData;

        if (type == "pull") {
          const message = {
            type: "data",
            value: undefined,
            done: true,
            messageId,
          };
          worker.postMessage(message);
        }
      }

      const worker = new Worker(new URL(script));
      const workerData = { worker };
      worker.addEventListener("message", (event) =>
        onMessage(event, workerData),
      );

      const message = {
        type: "start",
        readable: readable,
      };

      try {
        worker.postMessage(message, [readable]);
      } catch {
        message.readable = null;
        worker.postMessage(message);
      }

      // Ends up being true in Chrome and Firefox, false in Ladybird
      console.log(readable.locked);
    };

    main();
  </script>
  <script type="worker">
    let pendingResolve = null;

    addEventListener("message", ({ data: e }) => {
        const { type, value, done } = e;

        if (type == "start") {
            const readableStream = new ReadableStream({
            async pull(controller) {
                const promise = new Promise(resolve => pendingResolve = resolve);
                postMessage({ type: "pull", messageId: 0 });

                const { value, done } = await promise;
                controller.enqueue(value);
                if (done) controller.close();
            }
            });

            return readableStream
            .pipeThrough(new TransformStream({
                transform(chunk, controller) {
                controller.enqueue(chunk);
                }
            }))
            .pipeThrough(new DecompressionStream("deflate-raw"))
            .pipeThrough(new TransformStream());
        } else if (type == "data") {
            pendingResolve({ value: new Uint8Array(value), done });
            pendingResolve = null;
        }
    });
  </script>
</body>
```

### Log output and (if possible) backtrace

```shell
12561.181 WebContent(36602): ResponsePrototype::blob()
12561.181 WebContent(36602): WindowGlobalMixin::document_getter()
12561.181 WebContent(36602): DocumentPrototype::query_selector("script[type='worker']")
12561.181 WebContent(36602): NodePrototype::text_content_getter()
12561.181 WebContent(36602): BlobConstructor::construct([object Array], [object Object])
12561.182 WebContent(36602): DOMURLConstructor::create_object_url([object Blob])
12561.182 WebContent(36602): ReadableStreamConstructor::construct([object Object])
12561.182 WebContent(36602): DOMURLConstructor::construct("blob:file:///ee5bc67a-3cbd-498f-99b1-467d42336603")
12561.182 WebContent(36602): WorkerConstructor::construct([object DOMURL])
12561.182 WebContent(36602): DOMURLPrototype::to_string()
12561.183 Ladybird(36587): Destroying Thread ""(131831536027328) while it is still running undetached!
12561.183 WebContent(36602): EventTargetPrototype::add_event_listener("message", [object ECMAScriptFunctionObject])
12561.183 WebContent(36602): WorkerPrototype::post_message([object Object], [object Array])
12561.183 WebContent(36602): WorkerPrototype::post_message0([object Object], [object Array])
12561.183 WebContent(36602): DOMExceptionPrototype::message_getter()
12561.183 WebContent(36602): THROW! Cannot transfer type
12561.183 WebContent(36602): -> 
12561.183 WebContent(36602): -> main @ file:///home/aplefull/Downloads/streams.html:62,27
12561.183 WebContent(36602): -> main
12561.183 WebContent(36602): -> 
12561.183 WebContent(36602): -> 
12561.183 WebContent(36602): -> 
12561.183 WebContent(36602): WorkerPrototype::post_message([object Object])
12561.183 WebContent(36602): WorkerPrototype::post_message1([object Object])
12561.183 WebContent(36602): ReadableStreamPrototype::locked_getter()
12561.183 WebContent(36602): (js log) false
12561.184 WebContent(36602): BlobPrototype::array_buffer()
12561.184 WebContent(36602): ReadableStreamDefaultControllerPrototype::enqueue([object Uint8Array])
12561.234 WebContent(36602): MessageEventPrototype::data_getter()
12561.234 WebContent(36602): WorkerPrototype::post_message([object Object])
12561.234 WebContent(36602): WorkerPrototype::post_message1([object Object])
12561.235 WebWorker(36618): Unhandled JavaScript exception (in promise): [TypeError] Cannot close an errored stream
12561.235 WebWorker(36618):     at <unknown>
    at <unknown>

12561.235 WebWorker(36618): Unhandled JavaScript exception (in promise): [TypeError] Unable to decompress chunk: Reached end-of-stream without collecting the required number of bits
12561.235 WebWorker(36618):     at <unknown>
    at transform (blob:file:///ee5bc67a-3cbd-498f-99b1-467d42336603:22:35)
    at <unknown>
    at <unknown>
    at pull
    at pull
    at <unknown>
    at <unknown>
```

### Screenshots or screen recordings

_No response_

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by trflynn89**
For stream transfer to work, this requires `MessagePort::disentangle` to flush pending messages before the transport socket is closed.

Fixes #3294

### CODE REVIEW

File: Libraries/LibWeb/Streams/AbstractOperations.cpp [hunk 1]
```diff
@@ -50,6 +65,359 @@ GC::Ref<SizeAlgorithm> extract_size_algorithm(JS::VM& vm, QueuingStrategy const&
...
+            cross_realm_transform_send_error(realm, port, error);
+
+            // 3. Perform ! ReadableStreamDefaultControllerError(controller, error).
+            readable_stream_default_controller_error(controller, error);
+
+            // 4. Disentangle port.
+            port.disentangle();
+        });
+
+    // FIXME: 5. Enable port’s port message queue.
```
Comment (shannonbooth) [inline Libraries/LibWeb/Streams/AbstractOperations.cpp:222]: I believe this is basically just the same thing as calling `start()` on the message queue, which is basically a no-op with our current implementation (but I believe we need to change that at some point). When I had implemented the steps I just made a method on `MessagePort` that just called `start()` for this.

File: Libraries/LibWeb/Streams/AbstractOperations.cpp [hunk 2]
```diff
@@ -50,6 +65,359 @@ GC::Ref<SizeAlgorithm> extract_size_algorithm(JS::VM& vm, QueuingStrategy const&
...
+        return JS::js_undefined();
+    });
+
+    // 8. Let writeAlgorithm be the following steps, taking a chunk argument:
+    auto write_algorithm = GC::create_function(realm.heap(), [&realm, &port, backpressure_promise](JS::Value chunk) -> GC::Ref<WebIDL::Promise> {
+        // 1. If backpressurePromise is undefined, set backpressurePromise to a promise resolved with undefined.
+        if (!backpressure_promise->promise)
+            backpressure_promise->promise = WebIDL::create_resolved_promise(realm, JS::js_undefined());
+
+        // FIXME: The steps below ("Return a promise rejected/resolved with ...") seem to indicate we should be creating
```
Comment (shannonbooth) [inline Libraries/LibWeb/Streams/AbstractOperations.cpp:349]: huh, out of interest which WPT test runs into that? I guess a bunch of them, and maybe this is spec boog?

File: Libraries/LibWeb/Streams/AbstractOperations.cpp (hunk 1 above)
Comment (trflynn89) [reply Libraries/LibWeb/Streams/AbstractOperations.cpp:222]: I think it's the other way around - `start()` calls the enable steps.

The enable steps do a bunch of event loop / task shenanigans so I figured I'd kick that can down the road for now.
https://html.spec.whatwg.org/multipage/web-messaging.html#port-message-queue

File: Libraries/LibWeb/Streams/AbstractOperations.cpp (hunk 2 above)
Comment (trflynn89) [reply Libraries/LibWeb/Streams/AbstractOperations.cpp:349]: This was the first one I came across:
https://github.com/web-platform-tests/wpt/blob/5e54a28f3d9d6a5e63706381bbe899522b7b07ac/streams/transferable/readable-stream.html#L207-L215

We actually get 2 errors in that subtest if we implement it exactly as the spec says (or at least as I interpreted the spec):
```
▶ ERROR [expected OK] /streams/transferable/readable-stream.html
└   → Unhandled rejection: Cannot serialize platform objects

▶ Unexpected subtest result in /streams/transferable/readable-stream.html:
│ FAIL [expected PASS] transferring a non-serializable chunk should error both sides
│   → assert_throws_js: original stream should be errored function "() => rs.controller.enqueue()" did not throw
│
│     at <unknown>
│     at assert_wrapper (http://web-platform.test:8000/resources/testharness.js:1469:35)
│     at http://web-platform.test:8000/streams/transferable/readable-stream.html:206:19
│     at http://web-platform.test:8000/streams/transferable/readable-stream.html:201:3
│     at <unknown>
└     at <unknown>
```

It wasn't clear to me if this is a spec issue or if I'm interpreting the spec wrong

Comment (trflynn89) [reply Libraries/LibWeb/Streams/AbstractOperations.cpp:349]: The implementation being:
```c++
// 8. Let writeAlgorithm be the following steps, taking a chunk argument:
auto write_algorithm = GC::create_function(realm.heap(), [&realm, &port, backpressure_promise](JS::Value chunk) -> GC::Ref<WebIDL::Promise> {
    // 1. If backpressurePromise is undefined, set backpressurePromise to a promise resolved with undefined.
    if (!backpressure_promise->promise)
        backpressure_promise->promise = WebIDL::create_resolved_promise(realm, JS::js_undefined());

    // 2. Return the result of reacting to backpressurePromise with the following fulfillment steps:
    return WebIDL::upon_fulfillment(*backpressure_promise->promise,
        GC::create_function(realm.heap(), [&realm, &port, backpressure_promise, chunk](JS::Value) -> WebIDL::ExceptionOr<JS::Value> {
            // 1. Set backpressurePromise to a new promise.
            backpressure_promise->promise = WebIDL::create_promise(realm);

            // 2. Let result be PackAndPostMessageHandlingError(port, "chunk", chunk).
            auto result = pack_and_post_message_handling_error(realm, port, "chunk"sv, chunk);

            // 3. If result is an abrupt completion,
            if (result.is_error()) {
                // 1. Disentangle port.
                port.disentangle();

                // 2. Return a promise rejected with result.[[Value]].
                return WebIDL::create_rejected_promise_from_exception(realm, result.release_error());
            }
            
            // 4. Otherwise, return a promise resolved with undefined.
            return WebIDL::create_resolved_promise(realm, JS::js_undefined());
        }));
});
```

File: Libraries/LibWeb/Streams/AbstractOperations.cpp (hunk 1 above)
Comment (shannonbooth) [reply Libraries/LibWeb/Streams/AbstractOperations.cpp:222]: Right, I had just made a no-op function thing for it, but yeah fair enough to to kick the can. Only reason I mentioned it is since I knew we have one or maybe two places like this: https://github.com/LadybirdBrowser/ladybird/blob/7af188dc52e06ca3a22705ccd4efd70f1f19bdea/Services/WebWorker/WorkerHost.cpp#L211

File: Libraries/LibWeb/Streams/AbstractOperations.cpp (hunk 2 above)
Comment (shannonbooth) [reply Libraries/LibWeb/Streams/AbstractOperations.cpp:349]: Yeah FWIW I interpreted it the same, and implemented it the same on my attempt before I didn't get around to doing the message port thing

**Review by shannonbooth — APPROVED** [review]
