### PR TITLE
LibWeb: Handle MouseButton::None in mouse_button_to_button_code()

### LINKED ISSUE #7828: Double-clicking with mouse buttons 6 or higher will crash Ladybird
### Summary

Found this while testing #6946 and #6947. Fixing those may also fix this.

If you press any mouse button above the fifth one twice on seemingly any page, Ladybird will just crash after a second. I have no idea why.

### Operating system

Linux

### Steps to reproduce

1. Have a mouse with at least six buttons (they must also be bound accordingly rather than to macros or other keys)
2. Press mouse button 6 twice

### Expected behavior

Nothing should happen.

### Actual behavior

The page hangs for maybe a second before going to the crash screen.

### URL for a reduced test case

this works on any page

### HTML/SVG/etc. source for a reduced test case

```html
that page has rather simple source code (which is present in some of my other mouse button related reports)
```

### Log output and (if possible) backtrace

```shell
conputer@connor-b650gamingxax:~/other-dev/ladybird/20250807210822/ladybird$ ./Meta/ladybird.py run
ninja: Entering directory `/home/conputer/other-dev/ladybird/20250807210822/ladybird/Build/release'
ninja: no work to do.
VERIFICATION FAILED: false at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/UIEvents/MouseButton.h:41
Stack trace (most recent call first):
#0  (inlined)          in mouse_button_to_button_code at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/UIEvents/MouseButton.h:41:9
#1  0x000070f9f78e96c0 in create_from_platform_event at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/UIEvents/MouseEvent.cpp:152:25
#2  0x000070f9f77d6db8 in handle_doubleclick at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/Page/EventHandler.cpp:1160:26
#3  (inlined)          in operator() at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:306:37
#4  (inlined)          in visit<AK::Variant<Web::KeyEvent, Web::MouseEvent, Web::DragEvent, Web::PinchEvent>, AK::Variant<Web::KeyEvent, Web::MouseEvent, Web::DragEvent, Web::PinchEvent>::Visitor<(lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:284:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:293:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:312:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:315:17)>, (unsigned char)'\x01'> at /home/conputer/other-dev/ladybird/20250807210822/ladybird/AK/Variant.h:113:24
#5  (inlined)          in visit<AK::Variant<Web::KeyEvent, Web::MouseEvent, Web::DragEvent, Web::PinchEvent>, AK::Variant<Web::KeyEvent, Web::MouseEvent, Web::DragEvent, Web::PinchEvent>::Visitor<(lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:284:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:293:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:312:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:315:17)>, (unsigned char)'\x00'> at /home/conputer/other-dev/ladybird/20250807210822/ladybird/AK/Variant.h:119:20
#6  (inlined)          in visit<(lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:284:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:293:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:312:17), (lambda at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:315:17)> at /home/conputer/other-dev/ladybird/20250807210822/ladybird/AK/Variant.h:419:16
#7  (inlined)          in operator() at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:283:39
#8  0x000070f9f75278f5 in process_input_events at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:343:9
#9  0x000070f9f752820d in update_the_rendering at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:356:5
#10 (inlined)          in operator() at /home/conputer/other-dev/ladybird/20250807210822/ladybird/AK/Function.h:148:25
#11 0x000070f9f752ad37 in execute at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/Task.cpp:47:5
#12 0x000070f9f7526ad1 in process at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp:190:22
#13 (inlined)          in operator() at /home/conputer/other-dev/ladybird/20250807210822/ladybird/AK/Function.h:148:25
#14 (inlined)          in operator() at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibWeb/Platform/TimerSerenity.cpp:26:13
#15 0x000070f9f7836bc0 in call at /home/conputer/other-dev/ladybird/20250807210822/ladybird/AK/Function.h:225:20
#16 (inlined)          in operator() at /home/conputer/other-dev/ladybird/20250807210822/ladybird/AK/Function.h:148:25
#17 0x000070f9f63606c3 in timer_event at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibCore/Timer.cpp:94:9
#18 0x000070f9f635f567 in process at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibCore/ThreadEventQueue.cpp:0:0
#19 (inlined)          in pump at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibCore/EventLoopImplementationUnix.cpp:308:40
#20 0x000070f9f636505b in exec at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibCore/EventLoopImplementationUnix.cpp:300:9
#21 0x000070f9f6356af6 in exec at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibCore/EventLoop.cpp:100:20
#22 0x00005ee4ff48b9bd in ladybird_main at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Services/WebContent/main.cpp:230:23
#23 0x00005ee4ff5618ad in main at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Libraries/LibMain/Main.cpp:46:19
#24 0x000070f9f4e2a1c9 in __libc_start_call_main at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#25 0x000070f9f4e2a28a in __libc_start_main_impl at ./csu/../csu/libc-start.c:360:3
#26 0x00005ee4ff48a364 in _start at /home/conputer/other-dev/ladybird/20250807210822/ladybird/Build/release/libexec/WebContent
8878.334 Ladybird(55695): WebContent process crashed! Last page loaded: about:newtab
8878.334 Ladybird(55695): Consider raising an issue at https://github.com/LadybirdBrowser/ladybird/issues/new/choose
8878.337 WebContent(55718): FIXME: Handle null navigation_request in navigation response Content Security Policy check.
```

### Screenshots or screen recordings

Image

### Build flags or config settings

_No response_

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

Double-clicking with mouse buttons 6 or higher crashes Ladybird. The Qt and AppKit frontends map unknown buttons to `MouseButton::None`, which reaches `mouse_button_to_button_code()` and hits `VERIFY_NOT_REACHED()`.

## Changes

Added a `case MouseButton::None:` returning `-1` in `mouse_button_to_button_code()`. Per the [W3C UIEvents spec](https://www.w3.org/TR/uievents/#dom-mouseevent-button), `-1` indicates no button is associated with the event.

The crash path was:
1. Qt button 6+ -> `get_button_from_qt_mouse_button()` returns `MouseButton::None`
2. Double-click fires -> `handle_doubleclick()` -> `create_from_platform_event()`
3. `mouse_button_to_button_code(MouseButton::None)` -> `VERIFY_NOT_REACHED()` -> crash

Both `MouseEvent::create_from_platform_event()` and `PointerEvent::create_from_platform_event()` call this function, so both paths are fixed.

This does not add support for buttons 6+ as input events (#6947), only prevents the crash.

## Testing

- Verified the crash path exists in the code
- `MouseButton::None` (0) now returns -1 instead of crashing
- All other button mappings unchanged

Fixes #7828

This contribution was developed with AI assistance (Claude Code).

### CODE REVIEW

File: Libraries/LibWeb/UIEvents/MouseButton.h [hunk 1]
```diff
@@ -27,6 +27,8 @@ AK_ENUM_BITWISE_OPERATORS(MouseButton);
 constexpr i16 mouse_button_to_button_code(MouseButton button)
```
Comment (gmta) [inline Libraries/LibWeb/UIEvents/MouseButton.h:27]: You haven't modified it in this PR, but the correct spec URL is:

https://w3c.github.io/pointerevents/#dom-mouseevent-button

We always use the editor's draft of web specs.

Comment (gmta) [reply Libraries/LibWeb/UIEvents/MouseButton.h:27]: In fact, the actual link should probably be this:

https://w3c.github.io/pointerevents/#the-button-property

This clearly mentions the `-1` you're now introducing.

Comment (mvanhorn) [reply Libraries/LibWeb/UIEvents/MouseButton.h:27]: Updated both references in 0951d29.

Comment (mvanhorn) [reply Libraries/LibWeb/UIEvents/MouseButton.h:27]: Used this link for both spec references in 0951d29.

**Comment by gmta** [comment]
Thank you!

**Comment by mvanhorn** [comment]
Thanks for the review and the spec URL pointers, @gmta - those editor's draft links are much better.

**Comment by mvanhorn** [comment]
Thanks for the review and merge!
