### PR TITLE
LibWeb/CSS: Fix crash resolving `calc` with only percentages

### LINKED ISSUE #3006: Crash when resolving `transform: translateX(calc(10%))`
Repro:
```html
<!doctype html>
<style>
body {
    transform: translateX(calc(10%));
}
</style>
<body>
```

(Reduction from https://linear.app)

cc @AtkinsSJ

### PR DESCRIPTION
**Pull request by Jaycadox**
Fixes #3006 , (relates to) #648

From some analysis, it seems as if this issue only occurs with a only percentages in a `calc`.
- `calc(10%)` crashes.
- `calc(10% + 10%)` crashes.
- `calc(10% + 0px)` doesn't crash.
- `calc(10vw)` doesn't crash.

The `resolve` function returns a `Length` in the general case, but returns a `Percentage` if only percentages are provided.

As a sanity check, I looked at the code before it was changed (commit before change was [here](https://github.com/LadybirdBrowser/ladybird/commit/8d40550478b213bceb1b95f44197df5b8e02fb8a)), and it only handled the case of percentages and lengths, as I do in this commit.

The old code being:
```cpp
Optional<Length> CalculatedStyleValue::resolve_length_percentage(Length::ResolutionContext const& resolution_context, Length const& percentage_basis) const
{
    auto result = m_calculation->resolve(resolution_context, percentage_basis);

    return result.value().visit(
        [&](Length const& length) -> Optional<Length> {
            return length;
        },
        [&](Percentage const& percentage) -> Optional<Length> {
            return percentage_basis.percentage_of(percentage);
        },
        [&](auto const&) -> Optional<Length> {
            return {};
        });
}
```

Not sure if this is perfect, very open to constructive criticism.

### CODE REVIEW

**Comment by gmta** [comment]
Hi @Jaycadox, thanks for looking into this! Could you also add a test to expose the original issue?

File: Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp [hunk 1]
```diff
@@ -1890,7 +1890,7 @@ Optional<Length> CalculatedStyleValue::resolve_length_percentage(Layout::Node co
 Optional<Length> CalculatedStyleValue::resolve_length_percentage(Length::ResolutionContext const& resolution_context, Length const& percentage_basis) const
 {
     auto result = m_calculation->resolve(resolution_context, percentage_basis);
-    if (result.type().has_value() && result.type()->matches_length())
+    if (result.type().has_value() && (result.type()->matches_length() || result.type()->matches_percentage()))
         return Length::make_px(CSSPixels { result.value() });
```
Comment (AtkinsSJ) [inline Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp:1894]: This isn't correct. If a percentage gets returned (eg, `35%`) it'll return that number as a length (`35px`).

A more correct thing to do would be to return the percentage applied to the `percentage_basis` in that case.

The question is why this isn't getting converted to a length earlier on. `NumericCalculationNode::resolve()` should be doing that.

**Comment by Jaycadox** [comment]
I had a look again at the issue, it seems that `NumericCalculationNode::resolve`, when given a percentage, would convert it to a pixel value (via `percentage_of`) but not update the `CSSNumericType`, so it would stay as `Percentage`. When putting the expression as a sum, `SumCalculationNode` would call `add_the_types`, and I __think__ this would see the expression `"Percentage" + Length", and set the output type to `Length`, thus fixing the bug.

In my new patch, I visit all the variants of the percentage basis and set the `CSSNumericType` explicitly, which fixes the bug, though I'm not sure if it makes sense to allow all of these types to be a percentage basis. Still open for feedback.

File: Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp (hunk 1 above)
Comment (Jaycadox) [reply Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp]: From my analysis, I believe it would actually return the correct resolved pixel value (as `percentage_basis` was being called on it  in `NumericCalculationNode::resolve`), the issue was purely that it was being reported as the wrong type, and I do think that my original patch, did _fix_ the specific issue, but agree that it didn't fix the underlying problem.

File: Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp [hunk 2]
```diff
@@ -1728,8 +1748,31 @@ bool RemCalculationNode::equals(CalculationNode const& other) const
         && m_y->equals(*static_cast<RemCalculationNode const&>(other).m_y);
 }
 
+static Optional<CSSNumericType> numeric_type_from_value(CalculatedStyleValue::CalculationResult::Value const& value)
+{
+    return value.visit(
+        [](Number const&) -> Optional<CSSNumericType> { return {}; },
```
Comment (Jaycadox) [inline Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp:1754]: I don't know what `CSSNumericType` should occur in the case of `Number`, I assume there isn't a set one and it can change. But this code should probably be corrected if there is one.

File: Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp [hunk 3]
```diff
@@ -194,17 +194,32 @@ bool NumericCalculationNode::contains_percentage() const
     return m_value.has<Percentage>();
 }
 
+static Optional<CSSNumericType> numeric_type_from_calculated_style_value(CalculatedStyleValue::CalculationResult::Value const& value)
+{
+    return value.visit(
+        [](Number const&) -> Optional<CSSNumericType> { return {}; },
```
Comment (Jaycadox) [inline Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp:200]: I don't know what `CSSNumericType` should occur in the case of `Number`, I assume there isn't a set one and it can change. But this code should probably be corrected if there is one.

Comment (AtkinsSJ) [reply Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp:200]: This is actually a duplicate of what's done in `NumericCalculationNode::create()`, maybe that code can be pulled out and reused.

Comment (Jaycadox) [reply Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp]: Thanks for the suggestion :+1:

**Comment by Jaycadox** [comment]
My bad, I believe I have now fixed the linting errors.

**Review by AtkinsSJ — COMMENTED** [review]
Thanks, this is looking good. (And I finally understand what I messed up originally!) Just a couple of comments:

1. The commit message should be more descriptive of what the commit does. It's good to mention that it fixes a bug somewhere in the message, but the title itself should be what the code change is. Here, that'd be something like "Recalculate calc() numeric type when resolving percentages" (though you can probably word that better).
2. There are a few VERIFY()s sprinkled about, which seem like they might be from your debugging and testing? It's fine to leave them in but I just want to check they're supposed to be permanent. :^)

So really just the commit message needs adjusting, then this should be good to merge. (And then you won't have to keep waiting for someone to manually run CI. :sweat_smile: )

**Comment by AtkinsSJ** [comment]
Oh also, once a comment is resolved, press the `[Resolve conversation]` button on it. That makes it clear to reviewers that all the feedback has been dealt with.

**Comment by Jaycadox** [comment]
Thanks for the feedback, I believe that I have implemented your suggestions.

In this case, I left the VERIFY's on purpose, as I believe they express the intent, that is that the numeric type member should have to match the actual numeric type of the value.

File: Tests/LibWeb/Text/input/css/singular-percentage-calc-crash.html [hunk 4]
```diff
@@ -0,0 +1,12 @@
...
+    div {
+        transform: translateX(calc(10%))
+    }
+</style>
+<div></div>
+<script>
+    test(() => {
+        println(`PASS! (Didn't crash)`);
+    });
+</script>
```
Comment (LucasChollet) [inline Tests/LibWeb/Text/input/css/singular-percentage-calc-crash.html:12]: This file doesn't end with a new line. I'm surprised the CI didn't pick it up.

Comment (AtkinsSJ) [reply Tests/LibWeb/Text/input/css/singular-percentage-calc-crash.html:12]: We don't worry about that for tests. Back in the day I think we manually removed the trailing newlines for layout tests just so they wouldn't add the extra text node.

Comment (LucasChollet) [reply Tests/LibWeb/Text/input/css/singular-percentage-calc-crash.html:12]: Oh ok, I'm always fighting the pre-commit hook when I import WPT tests that don't have one.

Comment (AtkinsSJ) [reply Tests/LibWeb/Text/input/css/singular-percentage-calc-crash.html:12]: That's odd, maybe your commit hook is outdated? I don't think I've had that issue but maybe I've been importing tests that don't lack the newline.
