### PR TITLE
LibGfx: Fix BMPs and send RGBx data to Skia

### LINKED ISSUE #1132: BMP images not loading
Ladybird @ 2f3128333dcd5a781f35272800631d6cf03803ad

1. Go to any site with a BMP image (https://circl-lastname.github.io/test-bmp/)
2. There is no image load error in the console, but the BMP image is a white rect

### PR DESCRIPTION
**Pull request by shlyakpavel**
I was inspired by comments here https://github.com/LadybirdBrowser/ladybird/pull/1167 and I tried to implement passing RGBx data (w/o alpha channel) to Skia.
Fixes #1132

### CODE REVIEW

**Comment by shlyakpavel** [comment]
Ok, I got it to work. 4:05 am here. This requires massive rework/cleanup, but feel free to leave any helpful suggestions

File: Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp [hunk 1]
```diff
@@ -1372,7 +1373,14 @@ static ErrorOr<void> decode_bmp_pixel_data(BMPLoadingContext& context)
...
                     return Error::from_string_literal("Cannot read 24 bits");
-                context.bitmap->scanline(row)[column++] = streamer.read_u24();
+
+                u32 pixel = streamer.read_u24();
+                u8 b = (pixel & 0xFF0000) >> 16;
+                u8 g = (pixel & 0x00FF00) >> 8;
+                u8 r = (pixel & 0x0000FF);
+
+                u32 rgbx_pixel = (r << 16) | (g << 8) | b | 0xFF000000;
+                context.bitmap->scanline(row)[column++] = rgbx_pixel;
```
Comment (gmta) [inline Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: Not sure why this code is more complicated than what we already have in #1167 , but we'd now also have to rehash the conversation we had there: why would you set the alpha channel for a bitmap format that has no alpha channel?

Comment (shlyakpavel) [reply Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: Check your words there
> I agree with you that using RGB(A) as an output type makes more sense for Ladybird since Skia (and possibly other rendering libraries as well) natively supports both the version with and without the alpha channel.

This Pull Request reorders bytes to pass RGBx as output type. Without alpha channel. Last byte is a spacer, it does nothing important and is not rendered as Alpha channel. This is why this code is more complicated. It is written according to the discussion you had at https://github.com/LadybirdBrowser/ladybird/pull/1167 and on @ LucasChollet and your point that RGB(A) should be passed to Skia.

Comment (shlyakpavel) [reply Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: It's not possible to pass the image as is to Skia. Skia does not support BGRx8888. So we either add alpha channel as in https://github.com/LadybirdBrowser/ladybird/pull/1167 or we reorder bytes as in this PR.

Comment (shlyakpavel) [reply Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: I deleted the 0xFF000000 part to make code less confusing. Now, the spacer is undefined (perhaps some default value or 0)

Comment (shlyakpavel) [reply Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: I also want to mention that there's no other image format that we do not append alpha channel to. With this PR, BMP becomes the first one. So your question "why would you set the alpha channel for a bitmap format that has no alpha channel?" applied to any absolutely any image we render, be it PNG, JPEG, TIFF etc

Comment (gmta) [reply Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: I'm only talking about the referenced code, not the other changes in this PR which seem good! If we use RGBx, we should not care about the alpha channel.

Comment (shlyakpavel) [reply Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: It seems that my changes to remove the extra to_skia_color_type broke the CI. Do you have any ideas why? It builds fine on my Mac with AppKit Chrome. I could revert the change and keep to_skia_color_type as it was originally, but I’d prefer not to have duplicated code. Duplicated code can be confusing, especially since the functions with the same name are used in both the cacher and renderer. This can lead to unexpected behavior if they differ.

Comment (simonkrauter) [reply Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: hm, no idea why the CI fails with ``LibGfx/PainterSkia.h:12:10: error: 'core/SkImageInfo.h' file not found``.

Comment (shlyakpavel) [reply Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp:1383]: The point is, Skia _should_ be available at compile time and that issue is not reproducible on my local machine..

File: Userland/Libraries/LibGfx/Bitmap.h [hunk 2]
```diff
@@ -309,6 +314,14 @@ ALWAYS_INLINE void Bitmap::set_pixel<StorageFormat::RGBA8888>(int x, int y, Colo
     scanline(y)[x] = rgba;
 }
 
+template<>
+ALWAYS_INLINE void Bitmap::set_pixel<StorageFormat::RGBx8888>(int x, int y, Color color)
+{
+    VERIFY(x >= 0);
+    VERIFY(x < width());
+    scanline(y)[x] = color.value();
```
Comment (gmta) [inline Userland/Libraries/LibGfx/Bitmap.h:322]: The goal of these `set_pixel` template instances is that for a given `Color`, its value gets converted to the internal representation of the bitmap. This means converting the `ARGB32` value into `RGBx8888`, in this case. Currently this directly copies the value into the buffer, which doesn't seem right.

File: Userland/Utilities/image.cpp [hunk 3]
```diff
@@ -109,6 +112,9 @@ static ErrorOr<void> strip_alpha(LoadedImage& image)
     case Gfx::BitmapFormat::BGRA8888:
     case Gfx::BitmapFormat::BGRx8888:
         frame->strip_alpha_channel();
+        break;
+    default:
+        VERIFY_NOT_REACHED();
```
Comment (gmta) [inline Userland/Utilities/image.cpp:117]: Here (and on line 92) you add default cases to the switches. Please move the VERIFY_NOT_REACHED() to underneath the switch block and remove the `default:` case. Instead, implement the newly added enumeration value - even if it means adding a `FIXME`.

This way, the compiler will let you know whenever you add a new enumeration value and forget to expand the switch cases.

File: Userland/Libraries/LibGfx/Bitmap.cpp [hunk 4]
```diff
@@ -37,6 +37,7 @@ size_t Bitmap::minimum_pitch(size_t width, BitmapFormat format)
     switch (determine_storage_format(format)) {
```
Comment (gmta) [inline Userland/Libraries/LibGfx/Bitmap.cpp:37]: Overall: could you add a small test case so we can prevent regressions?

File: Userland/Utilities/image.cpp (hunk 3 above)
Comment (shlyakpavel) [reply Userland/Utilities/image.cpp]: I didn't know compiler checks that. As it does, we really don't need any VERIFY_NOT_REACHED here. I've fixed that

File: Userland/Libraries/LibGfx/Bitmap.cpp (hunk 4 above)
Comment (shlyakpavel) [reply Userland/Libraries/LibGfx/Bitmap.cpp:37]: Done

Comment (gmta) [reply Userland/Libraries/LibGfx/Bitmap.cpp:37]: Could you also test the actual color data?

Comment (shlyakpavel) [reply Userland/Libraries/LibGfx/Bitmap.cpp:37]: It looks like I do now
