### PR TITLE
LibWeb: Use correct specifier to pad font language override value

### LINKED ISSUE #2423: A reduced test case for a WebAnimation WPT crashes
I've noticed we're crashing on [accumulation-per-property-001.html](https://wpt.fyi/results/web-animations/animation-model/animation-types/accumulation-per-property-001.html?product=ladybird&product=safari%5Bstable%5D) WPT
The test is huge, and involves thousands of lines of code. 
This is why I made a reduced test case that crashes Ladybird. If we fix it, we're likely to significantly improve our WPT score as this crash involves 310 subtests at [accumulation-per-property-001.html](https://wpt.fyi/results/web-animations/animation-model/animation-types/accumulation-per-property-001.html?product=ladybird&product=safari%5Bstable%5D), 310 subtests at [addition-per-property-001.html](https://wpt.fyi/results/web-animations/animation-model/animation-types/addition-per-property-001.html?product=ladybird&product=safari%5Bstable%5D) and 385 subtests at [interpolation-per-property-001.html](https://wpt.fyi/results/web-animations/animation-model/animation-types/interpolation-per-property-001.html?product=ladybird&product=safari%5Bstable%5D)

```javascript
const element = document.createElement('div');
element.style.fontLanguageOverride = '"eng"';
document.body.appendChild(element);

const animation = element.animate(
  [
    { fontLanguageOverride: '"eng"' },
    { fontLanguageOverride: '"xyz"' }
  ],
  { duration: 1000, iterations: 1 }
);
animation.play();
```

### PR DESCRIPTION
**Pull request by tcl3**
Previously the browser would crash when parsing short font-language-override values.

Fixes #2423

### CODE REVIEW

**Comment by shlyakpavel** [comment]
image
image
image
I can confirm this PR fixes us 476 subtests

File: Libraries/LibWeb/CSS/Parser/Parser.cpp [hunk 1]
```diff
@@ -5777,7 +5777,7 @@ RefPtr<CSSStyleValue> Parser::parse_font_language_override_value(TokenStream<Com
         }
         transaction.commit();
         if (length < 4)
-            return StringStyleValue::create(MUST(String::formatted("{<4}", string_value)));
+            return StringStyleValue::create(MUST(String::formatted("{:4}", string_value)));
```
Comment (trflynn89) [inline Libraries/LibWeb/CSS/Parser/Parser.cpp:5780]: Don't we still want the `<`?
> Shorter strings are right-padded with spaces

The `<` is what tells formatters to right-pad instead of left-pad, so that'd be:
```c++
return StringStyleValue::create(MUST(String::formatted("{:<4}", string_value)));
```

Comment (tcl3) [reply Libraries/LibWeb/CSS/Parser/Parser.cpp]: My understanding was that, without the specifier, the default alignment will be used, which gives the value right-padding. I've added the `<` back in though, as that makes it clear that the value is intended to be left-aligned / right-padded.
