### PR TITLE
LibWebView: Better integration of sanitize_url with search

### LINKED ISSUE #142: Using address bar to search for a single word fails
When a search engine is enabled, if I type in the address bar a single word then the page loads as https://`thatword`/. However if I type multiple words it works as expected.

If I put in the following dbgln's
```
diff --git a/Ladybird/Qt/LocationEdit.cpp b/Ladybird/Qt/LocationEdit.cpp
index 7dc4336331..3a23be952c 100644
--- a/Ladybird/Qt/LocationEdit.cpp
+++ b/Ladybird/Qt/LocationEdit.cpp
@@ -38,6 +38,8 @@ LocationEdit::LocationEdit(QWidget* parent)
             search_engine_url = Settings::the()->search_engine().query_url;

         auto query = ak_string_from_qstring(text());
+        dbgln("query={}, engine_url={}", query, search_engine_url);
+        dbgln("sanitized_url={}", WebView::sanitize_url(query, search_engine_url));

         if (auto url = WebView::sanitize_url(query, search_engine_url); url.has_value())
             setText(qstring_from_ak_string(url->serialize()));
```

The I get the following in the logs:
```
294966.228 Ladybird(680721): query=a, engine_url=https://duckduckgo.com/?q={}
294966.228 Ladybird(680721): sanitized_url=https://a/
294966.280 RequestServer(680723:680748): ConnectionCache: Connection to https://a/ failed: Temporary failure in name resolution
294966.280 RequestServer(680723:680748): Request with a null socket finished for URL https://a/
294966.280 WebContent(680757): ResourceLoader: Failed load of: "https://a/", Error: Load failed, Duration: 45ms
294973.648 Ladybird(680721): query=a a, engine_url=https://duckduckgo.com/?q={}
294973.648 Ladybird(680721): sanitized_url=https://duckduckgo.com/?q=a%20a
```

So the issue is likely in `WebView::sanitize_url`

### PR DESCRIPTION
**Pull request by manuel-za**
With search enabled:
- For a single word that does not look like a url: search (fixes #142).
- If no suffix or a suffix that is not recognized: search (like Firefox).

In general:
- Respect the user's choice if they specified a scheme.
- Respect `localhost`.
- As before, add `file://` to filesystem files that exist.

### CODE REVIEW

File: Libraries/LibWebView/URL.cpp [hunk 1]
```diff
@@ -12,42 +13,77 @@
...
+    auto location_with_scheme = URL::create_with_url_or_path(ByteString::formatted("https://{}"sv, location_trimmed));
 
-    ByteString url_with_scheme = url;
-    if (!(url_with_scheme.starts_with("about:"sv) || url_with_scheme.contains("://"sv) || url_with_scheme.starts_with("data:"sv)))
-        url_with_scheme = ByteString::formatted("https://{}"sv, url_with_scheme);
+    if (!location_with_scheme.is_valid())
+        return search_or_error();
 
-    auto result = URL::create_with_url_or_path(url_with_scheme);
+    auto const host = location_with_scheme.host();
```
Comment (trflynn89) [inline Libraries/LibWebView/URL.cpp:67]: `auto const&` - no need to make a copy

File: Libraries/LibWebView/URL.cpp [hunk 2]
```diff
@@ -12,42 +13,77 @@
...
+            return search_or_error();
 
-        return URL::create_with_file_scheme(path.value());
+        return url_or_error();
     }
 
-    auto format_search_engine = [&]() -> Optional<URL::URL> {
-        if (!search_engine.has_value())
-            return {};
+    if (location_trimmed.contains(' ') || location_trimmed.contains('"')) // Space-separated terms or quotations: this is a search.
```
[the remark this answers is not in the document]
Comment (manuel-za) [reply Libraries/LibWebView/URL.cpp:55]: > I don't think we should be making this assumption. For example, consider navigating to: `https://www.example.com/some cool page`
> While technically an invalid URL, both Firefox and Ladybird (on the `master` branch) will percent-encode those spaces, and navigate to: `https://www.example.com/some%20cool%20page`

Good point.
But Firefox will search for "https://www.example.com some cool page"...
I guess the '/' indicates path and we should obey that. I'll split + make decisions based on the first fragment.

**Comment by manuel-za** [comment]
Thank you for the thoughtful review @trflynn89 .

File: Tests/LibWebView/TestWebViewURL.cpp [hunk 3]
```diff
@@ -25,6 +26,29 @@ static bool is_sanitized_url_the_same(StringView url)
...
+
+    auto sanitized_url = WebView::sanitize_url(url, search_engine_url, append_tld);
+
+    EXPECT(sanitized_url.has_value());
+    EXPECT_EQ(sanitized_url->to_string(), test_url);
+}
+
+static void expect_search_url_equals_sanitized_url(StringView url)
+{
+    dbgln("DBG: {}", url);
```
Comment (trflynn89) [inline Tests/LibWebView/TestWebViewURL.cpp:41]: Let's not include debug spam

**Review by trflynn89 — COMMENTED** [review]
hmm, so my main concern now is that the logic in this function is a bit...unruly. I think we can reach a reasonably good UX here with a simpler URL sanitizer.

I also noticed that when you return `url_or_error` (when the string contains a scheme already), we miss the AppendTLD feature. Firefox and Chrome disagree here - Chrome will append a missing TLD with ctrl+enter in both cases, whereas Firefox will not. I tend to side with Chrome here, feels less confusing.

And I'm still not sure about the explicit checks for spaces and quotes...For example, consider the URL `https://example.com/"what"`. Firefox and Chrome will both navigate to that URL, whereas with this patch, we will search.

How does something like this fare? I think it handles spaces without explicit checks, and only checks for quotes in the host part of the URL. It passes all of your added test cases:
```c++
static constexpr Array SUPPORTED_SCHEMES = { "about:"sv, "data:"sv, "file://"sv, "http://"sv, "https://"sv, "resource://"sv };

Optional<URL::URL> sanitize_url(StringView location, Optional<StringView> search_engine, AppendTLD append_tld)
{
    auto search_url_or_error = [&]() -> Optional<URL::URL> {
        if (!search_engine.has_value())
            return {};
        return URL::Parser::basic_parse(MUST(String::formatted(*search_engine, URL::percent_encode(location))));
    };

    auto url_or_error = [&](ByteString const& location, auto enforce_public_suffix) -> Optional<URL::URL> {
        auto url = URL::create_with_url_or_path(location);
        if (!url.is_valid())
            return search_url_or_error();

        if (auto const& host = url.host(); host.has_value() && host->is_domain()) {
            auto const& domain = host->get<String>();
            if (domain.contains('"'))
                return search_url_or_error();

            if (auto public_suffix = URL::get_public_suffix(domain); !public_suffix.has_value() || *public_suffix == domain) {
                if (append_tld == AppendTLD::Yes)
                    url.set_host(MUST(String::formatted("{}.com", domain)));
                else if (enforce_public_suffix && domain != "localhost"sv)
                    return search_url_or_error();
            }
        }

        return url;
    };

    location = location.trim_whitespace();

    if (FileSystem::exists(location)) {
        if (auto path = FileSystem::real_path(location); !path.is_error())
            return URL::create_with_file_scheme(path.value());
        return search_url_or_error();
    }

    if (any_of(SUPPORTED_SCHEMES, [&](auto scheme) { return location.starts_with(scheme); }))
        return url_or_error(location, false);

    return url_or_error(ByteString::formatted("https://{}", location), true);
}
```

File: Tests/LibWebView/TestWebViewURL.cpp (hunk 3 above)
Comment (manuel-za) [reply Tests/LibWebView/TestWebViewURL.cpp:41]: Yes cleaner! Much better!! Update coming soon.
- Using `create_with _url_or_path...has_value` to weed out "http://example.org hello" was clever! I should have thought of that!! Maybe next time :smiling_face_with_tear:
-  RFC2606 :white_check_mark: 
- SUPPORTED_SCHEMES :white_check_mark:

My changes:
- Relying on url -> domain -> host to catch quotes may not be future-proof. Quotes are illegal in domain names (RFC 1123). I have relaxed the requirement to "start with a quote" and moved it to the function body (supports your example)
- Rather than match prefix for supported schemes, extract them from `create_with_url_or_path` then decide
- second chance url with `https` in `url_or_error`
- `mailto:` FIXME + test for unsupported (`ftp:`) or invalid schemes

A few minor editorial changes (I'll roll them back if you disagree):
- Moved the `constexpr` arrays in the body (minimize scope). If anyone needs them later, they can be moved outside or to the class. 
- I know you guys are using declarations-embedded-in-if extensively and that's ok. I find them harder to read + a potential source of errors... would not add them in my PR (personal preference)
- Converted a couple of  `auto` to their type (left the `Optional`)+ added a couple of `const &` (personal preference)

Comment (trflynn89) [reply Tests/LibWebView/TestWebViewURL.cpp]: > Relying on url -> domain -> host to catch quotes may not be future-proof. Quotes are illegal in domain names (RFC 1123). I have relaxed the requirement to "start with a quote" and moved it to the function body (supports your example)

I don't understand this change. You're correct that it is illegal in a domain name, which is why my suggestion explicitly checked for quotes in the domain name. Note that the URL parse will accept such a URL. With your change, we digress from Firefox/Chrome for URLs like `https://exa"mple.com/what`. Chrome/FF will perform a search of this text, whereas with your change, we will try to navigate to it.

> second chance url with https in url_or_error

That's fine, but note that with that change, there's no reason for `url_or_error` to be a lambda - it can just all be in the body of the function.

Regarding style:

* I won't push back on the inlined `if` declare-and-check statements :) I prefer them, but it's not a big deal.

* But I will push back on `auto` - as a whole, the project strongly prefers them, and any competent IDE / text editor will tell you the type. We *especially* want `auto` when declaring the type would be redundant. e.g. in these cases, it is obvious we're getting a URL and String, so specifying the type directly is really just noise:
  ```c++
  URL::URL url = URL::create_with_url_or_path(location);
  String const& domain = host->get<String>();
  ```

Comment (manuel-za) [reply Tests/LibWebView/TestWebViewURL.cpp]: - Good catch on `https://exa"mple.com` -- was totally a bug. Thank you!!
   - Added a unit test
- I removed the lambda
- Added back `auto` on URL (I take your point).

File: Libraries/LibWebView/URL.cpp [hunk 4]
```diff
@@ -1,6 +1,7 @@
 /*
- * Copyright (c) 2023, Tim Flynn <trflynn89@serenityos.org>
+ * Copyright (c) 2023, 2025 Tim Flynn <trflynn89@serenityos.org>
```
Comment (trflynn89) [inline Libraries/LibWebView/URL.cpp:2]: FYI we separate years with a hyphen (I thought we had a linter for this, but I guess not).
```c++
* Copyright (c) 2023-2025 Tim Flynn <trflynn89@serenityos.org>
```

(You also don't need to include me in this change, no worries)

File: Libraries/LibWebView/URL.cpp [hunk 5]
```diff
@@ -12,42 +13,67 @@
...
+        if (!path.is_error())
+            return URL::create_with_file_scheme(path.value());
+        return search_url_or_error();
     }
 
-    auto format_search_engine = [&]() -> Optional<URL::URL> {
-        if (!search_engine.has_value())
-            return {};
+    if (location.starts_with('"'))
+        return search_url_or_error();
```
Comment (trflynn89) [inline Libraries/LibWebView/URL.cpp:35]: Does this add anything now? Are there any cases this catches that aren't caught by the check for quotes in the domain name below? If not, let's just remove it to keep the logic here simpler

File: Libraries/LibWebView/URL.cpp [hunk 6]
```diff
@@ -12,42 +13,67 @@
...
-        }
+        if (!url.is_valid())
+            return search_url_or_error();
+
+        https_scheme_was_guessed = true;
     }
 
-    if (!result.is_valid())
-        return format_search_engine();
+    static constexpr Array SUPPORTED_SCHEMES { "about"sv, "data"sv, "file"sv, "http"sv, "https"sv, "resource:"sv };
```
Comment (trflynn89) [inline Libraries/LibWebView/URL.cpp:50]: The `:` should be removed from `resource:`, no?

**Review by trflynn89 — COMMENTED** [review]
Looking good! just a couple small things

File: Libraries/LibWebView/URL.cpp (hunk 5 above)
Comment (manuel-za) [reply Libraries/LibWebView/URL.cpp:35]: Yes `"http://this.is.the.domain.name`

Comment (trflynn89) [reply Libraries/LibWebView/URL.cpp:35]: But with that example, we hit the check for quotes in the domain name, and thus search the location text.

Comment (manuel-za) [reply Libraries/LibWebView/URL.cpp]: You are right. The quotes fail it being a domain name, then https: is added, where it fails because it's a domain name with quotes.
Well played!

**Review by trflynn89 — APPROVED** [review]
Great! Thanks for sticking with this :)
