### PR TITLE
LibWeb/Streams: Ensure pending pull into's objects are visited by GC

### LINKED ISSUE #3286: Use-after-free in Streams::transfer_array_buffer()
Caught by ASAN while running tests. Not immediately reproducible, but obviously GC related.

cc @shannonbooth 

```
/Users/kling/src/ladybird/Libraries/LibJS/Runtime/ArrayBuffer.h:90:13: runtime error: member access within address 0x000152f600e0 which does not point to an object of type 'const JS::ArrayBuffer'
0x000152f600e0: note: object is of type 'GC::HeapBlock::FreelistEntry'
 00 00 fe 7f  18 46 bc 03 01 00 00 00  00 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'GC::HeapBlock::FreelistEntry'
    #0 0x112198644 in JS::ArrayBuffer::is_detached() const ArrayBuffer.h:90
    #1 0x1128f1d80 in Web::Streams::transfer_array_buffer(JS::Realm&, JS::ArrayBuffer&) AbstractOperations.cpp:3403
    #2 0x1128f13fc in Web::Streams::readable_byte_stream_controller_convert_pull_into_descriptor(JS::Realm&, Web::Streams::PullIntoDescriptor const&) AbstractOperations.cpp:1846
    #3 0x1128fdd84 in Web::Streams::readable_byte_stream_controller_commit_pull_into_descriptor(Web::Streams::ReadableStream&, Web::Streams::PullIntoDescriptor const&) AbstractOperations.cpp:3453
    #4 0x11290f0d0 in Web::Streams::readable_byte_stream_controller_enqueue(Web::Streams::ReadableByteStreamController&, JS::Value) AbstractOperations.cpp:3379
    #5 0x112994eac in Web::Streams::ReadableByteStreamController::enqueue(GC::Root<Web::WebIDL::ArrayBufferView>&) ReadableByteStreamController.cpp:90
    #6 0x114391d24 in Web::Bindings::ReadableByteStreamControllerPrototype::enqueue(JS::VM&) ReadableByteStreamControllerPrototype.cpp:228
    #7 0x107bbf434 in AK::Function<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>::operator()(JS::VM&) const Function.h:120
    #8 0x107bbd944 in JS::NativeFunction::internal_call(JS::Value, AK::Span<JS::Value const>) NativeFunction.cpp:164
    #9 0x10749430c in JS::Bytecode::perform_call(JS::Bytecode::Interpreter&, JS::Value, JS::Bytecode::Op::CallType, JS::Value, AK::Span<JS::Value const>) Interpreter.cpp:1239
    #10 0x1073d9fb8 in JS::Bytecode::Interpreter::run_bytecode(unsigned long) Interpreter.cpp:573
    #11 0x1073ba580 in JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) Interpreter.cpp:737
    #12 0x10792cb04 in JS::GeneratorObject::execute(JS::VM&, JS::Completion const&) GeneratorObject.cpp:113
    #13 0x10792d9f8 in JS::GeneratorObject::resume(JS::VM&, JS::Value, AK::Optional<AK::StringView> const&) GeneratorObject.cpp:159
    #14 0x1077ae790 in JS::AsyncFunctionDriverWrapper::continue_async_execution(JS::VM&, JS::Value, bool, JS::AsyncFunctionDriverWrapper::IsInitialExecution) AsyncFunctionDriverWrapper.cpp:125
    #15 0x1077ae004 in JS::AsyncFunctionDriverWrapper::create(JS::Realm&, JS::GeneratorObject*) AsyncFunctionDriverWrapper.cpp:27
    #16 0x1078b9e9c in JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() ECMAScriptFunctionObject.cpp:837
    #17 0x1078b64c4 in JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) ECMAScriptFunctionObject.cpp:421
    #18 0x107924430 in JS::FunctionPrototype::apply(JS::VM&) FunctionPrototype.cpp:79
    #19 0x107bbf434 in AK::Function<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>::operator()(JS::VM&) const Function.h:120
    #20 0x107bbd944 in JS::NativeFunction::internal_call(JS::Value, AK::Span<JS::Value const>) NativeFunction.cpp:164
    #21 0x10749430c in JS::Bytecode::perform_call(JS::Bytecode::Interpreter&, JS::Value, JS::Bytecode::Op::CallType, JS::Value, AK::Span<JS::Value const>) Interpreter.cpp:1239
    #22 0x1073d9fb8 in JS::Bytecode::Interpreter::run_bytecode(unsigned long) Interpreter.cpp:573
    #23 0x1073ba580 in JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) Interpreter.cpp:737
    #24 0x1078b9af0 in JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() ECMAScriptFunctionObject.cpp:815
    #25 0x1078b64c4 in JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) ECMAScriptFunctionObject.cpp:421
    #26 0x10749430c in JS::Bytecode::perform_call(JS::Bytecode::Interpreter&, JS::Value, JS::Bytecode::Op::CallType, JS::Value, AK::Span<JS::Value const>) Interpreter.cpp:1239
    #27 0x1073d9fb8 in JS::Bytecode::Interpreter::run_bytecode(unsigned long) Interpreter.cpp:573
    #28 0x1073ba580 in JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) Interpreter.cpp:737
    #29 0x1078b9af0 in JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() ECMAScriptFunctionObject.cpp:815
    #30 0x1078b64c4 in JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) ECMAScriptFunctionObject.cpp:421
    #31 0x107c55e0c in JS::PromiseConstructor::construct(JS::FunctionObject&) PromiseConstructor.cpp:280
    #32 0x107bbe5b0 in JS::NativeFunction::internal_construct(AK::Span<JS::Value const>, JS::FunctionObject&) NativeFunction.cpp:221
    #33 0x10749439c in JS::Bytecode::perform_call(JS::Bytecode::Interpreter&, JS::Value, JS::Bytecode::Op::CallType, JS::Value, AK::Span<JS::Value const>) Interpreter.cpp:1241
    #34 0x1073d9970 in JS::Bytecode::Interpreter::run_bytecode(unsigned long) Interpreter.cpp:575
    #35 0x1073ba580 in JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) Interpreter.cpp:737
    #36 0x1078b9af0 in JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() ECMAScriptFunctionObject.cpp:815
    #37 0x1078b64c4 in JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) ECMAScriptFunctionObject.cpp:421
    #38 0x110b5cb6c in AK::Function<JS::ThrowCompletionOr<JS::Value> (JS::JobCallback&, JS::Value, AK::Span<JS::Value const>)>::CallableWrapper<Web::Bindings::initialize_main_thread_vm(Web::HTML::EventLoop::Type)::$_3>::call(JS::JobCallback&, JS::Value, AK::Span<JS::Value const>) Function.h:187
    #39 0x10790fc24 in AK::Function<JS::ThrowCompletionOr<JS::Value> (JS::JobCallback&, JS::Value, AK::Span<JS::Value const>)>::operator()(JS::JobCallback&, JS::Value, AK::Span<JS::Value const>) const Function.h:120
    #40 0x107c637a0 in AK::Function<JS::ThrowCompletionOr<JS::Value> ()>::CallableWrapper<JS::create_promise_reaction_job(JS::VM&, JS::PromiseReaction&, JS::Value)::$_0>::call() Function.h:187
    #41 0x110b61404 in AK::Function<JS::ThrowCompletionOr<JS::Value> ()>::operator()() const Function.h:120
    #42 0x110b6072c in AK::Function<void ()>::CallableWrapper<Web::Bindings::initialize_main_thread_vm(Web::HTML::EventLoop::Type)::$_5::operator()(GC::Ref<GC::Function<JS::ThrowCompletionOr<JS::Value> ()>>, JS::Realm*) const::'lambda'()>::call() Function.h:187
    #43 0x110a0d2cc in AK::Function<void ()>::operator()() const Function.h:120
    #44 0x111b978cc in Web::HTML::EventLoop::perform_a_microtask_checkpoint() EventLoop.cpp:526
    #45 0x1120d08b4 in Web::HTML::ClassicScript::run(Web::HTML::ClassicScript::RethrowErrors, GC::Ptr<JS::Environment>) ClassicScript.cpp:143
    #46 0x111e2e978 in Web::HTML::HTMLScriptElement::execute_script() HTMLScriptElement.cpp:133
    #47 0x11200b4e4 in Web::HTML::HTMLParser::handle_text(Web::HTML::HTMLToken&) HTMLParser.cpp:3067
    #48 0x111fe9608 in Web::HTML::HTMLParser::run(Web::HTML::HTMLTokenizer::StopAtInsertionPoint) HTMLParser.cpp:221
    #49 0x111fefaa8 in Web::HTML::HTMLParser::run(URL::URL const&, Web::HTML::HTMLTokenizer::StopAtInsertionPoint) HTMLParser.cpp:242
    #50 0x11151584c in AK::Function<void ()>::CallableWrapper<Web::load_html_document(Web::HTML::NavigationParams const&)::$_0::operator()(AK::Detail::ByteBuffer<32ul>) const::'lambda'()>::call() Function.h:187
    #51 0x110a0d2cc in AK::Function<void ()>::operator()() const Function.h:120
    #52 0x1050178f8 in AK::Function<void ()>::operator()() const Function.h:120
    #53 0x10505fe7c in Core::ThreadEventQueue::process() ThreadEventQueue.cpp:118
    #54 0x1050778a4 in Core::EventLoopImplementationUnix::exec() EventLoopImplementationUnix.cpp:316
    #55 0x105007a74 in Core::EventLoop::exec() EventLoop.cpp:88
    #56 0x10285fb38 in serenity_main(Main::Arguments) main.cpp:224
    #57 0x102cd52a8 in main Main.cpp:39
    #58 0x193b87150 in start+0x9a8 (dyld:arm64e+0xfffffffffff4d150)
```

### PR DESCRIPTION
**Pull request by shannonbooth**
While PendingPullIntos are typically visted by their controller there were some cases that we were removing those references from the controller and storing them in a SinglyLinkedList on the stack which is not safe.

Instead, make PendingPullInto a GC::Cell type, which also allows us to remove an awkward copy of the struct where the underlying reference was previously being destroyed.

Fixes #3286.

### CODE REVIEW

**Comment by shannonbooth** [comment]
Cool, confirmed that this fixes the GC issue in that test :^)

File: Libraries/LibWeb/Streams/ReadableByteStreamController.h [hunk 1]
```diff
@@ -172,7 +194,7 @@ class ReadableByteStreamController : public Bindings::PlatformObject {
 
     // https://streams.spec.whatwg.org/#readablebytestreamcontroller-pendingpullintos
     // A list of pull-into descriptors
-    SinglyLinkedList<PullIntoDescriptor> m_pending_pull_intos;
+    SinglyLinkedList<GC::Ref<PullIntoDescriptor>> m_pending_pull_intos;
```
Comment (awesomekling) [inline Libraries/LibWeb/Streams/ReadableByteStreamController.h:197]: Would an `IntrusiveList` make even more sense here? Can a `PullIntoDescriptor` be in more than one list at once?
